### ISSUE TITLE
Include as options or add to README as examples for markdown?

### ISSUE THREAD

**Issue by erichiller** [bartosz-antosik/vscode-spellright#100]
This is _entirely_ a suggestion to see if others find this helpful, but I was finding it extremely irksome to have my codeblocks constantly in error, so I put together two quick regexes to prevent that. Ideally we could do this through the scope setting, but codeblocks don't fall into one of the current three categories.

```

	"spellright.ignoreRegExpsByClass": {
		"markdown": [
			// ignore codeblocks
			"/^ {3,}\\w.*/gm",
			// ignore backticks
			"/`[^`]*`/gm"
		]
	}
```

**Comment by bartosz-antosik** [comment]
Hi! Thanks for the idea & code. This is surprising to me though. Code blocks (from `\`\`\`` to another three ticks should be omitted in markdown. At least this is what is configured in the parser. Could you please show me an example where they are not? It may be some regression which introduced recently.

**Comment by erichiller** [comment]
Right you are sir! Looks like as far as the backtick regex goes, it is unnecessary. But the indentation one still is.

(example with all regex off)

![image](https://user-images.githubusercontent.com/5379325/33723034-6141ce68-db20-11e7-9ef9-b5b9e6dd85e7.png)

**Comment by bartosz-antosik** [comment]
Your request is done in just published version 2.0.14. There is new context 'code' but I am not very proud of it, because it does not spell taking code's syntax under consideration.

Please give me some feedback, in this thread, whether it works for you.

**Comment by bartosz-antosik** [comment]
Sorry for returning to this case, but I have #105 now and I got some doubts whether four spaces really do introduce a code block? Could you point me to some documentation about this? Should not such a code block be an inline code surrounded with `backticks`?

**Comment by bartosz-antosik** [comment]
Please never mind my recent comment. It has been cleared out in the #105 thread.
