### ISSUE TITLE
add .vue document

### ISSUE THREAD

**Issue by sldobri** [bartosz-antosik/vscode-spellright#102]

**Comment by bartosz-antosik** [comment]
Could you please tell me which extension adds `.vue` document and maybe give some example document?

**Comment by MaxMilton** [comment]
In VS Code the main way of dealing with vue component file is the [vetur extension](https://github.com/vuejs/vetur). The language server source is: <https://github.com/vuejs/vetur/tree/master/server>.

Example vue components (various UI libraries, look in the `.vue` files):

- https://github.com/museui/muse-ui/tree/master/src
- https://github.com/matsp/material-components-vue/tree/master/components
- https://github.com/primefaces/primevue/tree/master/src/components
- More: https://github.com/vuejs/awesome-vue#frameworks

Vue documentation for `.vue` files a.k.a. single file components: <https://vuejs.org/v2/guide/single-file-components.html>.

**Comment by bartosz-antosik** [comment]
Please see `Unknown document type` and description of `spellright.parserByClass` in README.md and try to apply e.g. `xml` parser to `.vue` files and see what are the results. If there is more actions required (e.g. some scopes need to be excluded) please post some info here.

**Comment by bartosz-antosik** [comment]
This has been added internally in version 2.1.2. The support is rudimentary on the basis of

**Comment by MaxMilton** [comment]
@bartosz-antosik that's amazing, thank you! In some quick testing just now everything seems to be working as expected. :star2: :100:
