### ISSUE TITLE
How to get Windows 10 additional dictionaries

### ISSUE THREAD

**Issue by aricov** [bartosz-antosik/vscode-spellright#103]
This is probably off topic here, but I couldn't find anywhere the "system guidelines for adding spelling dictionaries" for Windows 10.

When I use the extension the only available language is always "English" which corresponds to the single "en-US" directory under %APPDATA%\Microsoft\Spelling.

Maybe adding a link to the actual guidelines in the corresponding part of the README could help.

**Comment by bartosz-antosik** [comment]
Hi! Thanks for the notice on this - if it is an issue fo you may be for other. I will add the below information to the README very soon:

1. I have not found an Microsoft originated & simple guide. There is [this](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/add-language-packs-to-windows) but it is formal & not straightforward. I will add [this](http://www.tech-recipes.com/rx/56333/windows-10-change-or-add-another-language/) but it is not complete in some cases (e.g. you have to go to "Options" for language pack & download spelling part for the language to appear in VSCode).

2. There is also [this](https://github.com/bartosz-antosik/vscode-spellright/issues/23#issuecomment-314038083) on adding multiple languages to Windows Single Language editions. But this is probably less of your interest.

**Comment by aricov** [comment]
Thanks for the quick response!

I'm running a Windows 10 Pro image provided by my company with all sort of things locked down by the admins. So no option to download a language pack for me. I'll try to sort it out with them on Monday, and see if I can get what I need (mostly en-GB support as I need British spelling when writing content for EU bodies, French and Greek for personal stuff).

I don't run windows on my own machines, so I can't compare with an untainted setup.

Information on the internet is indeed very scarce with most google searches leading to Office related configuration instructions.  The second and third link you provided my be helpful in the README or some other document linked from there.

Extension is otherwise great!

**Comment by bartosz-antosik** [comment]
Then you may try an entirely different approach: set environment variable SPELLCHECKER_PREFER_HUNSPELL (Right Click on My Computer -> Properties -> Advanced system settings -> Environment Variables... -> System variables OR User variables for XXX -> New... -> Variable name = SPELLCHECKER_PREFER_HUNSPELL, Variable Value = 1) - of course if you can set these. 

Restart VSCode & then the extension should use HUNSPELL spelling API, not Windows native one.

You can then download and install dictionaries as it is described in "Linux and Windows 7" section of the README file. The dictionaries are maybe not as good as the Windows ones (or maybe it is my false impression) but they are OK for pretty large part of the world (macOS, Linux, Firefox, Chrome etc.)

Drop a line here if it works for you (It does for me but I have no policies imposed like you describe).

Thanks for nice words about the extension. I always appreciate reviews in this "Market" thing [here](https://marketplace.visualstudio.com/items?itemName=ban.spellright#review-details) but you have to be logged to add one. So no need to if that's a trouble.

**Comment by bartosz-antosik** [comment]
The changes proposed are included in README.md for just published version 2.0.18.
