### ISSUE TITLE
Tex quotation marks

### ISSUE THREAD

**Issue by quicky84** [bartosz-antosik/vscode-spellright#108]
In Tex source files quotation marks are typed as ``` `` '' ```. This notation confuses the spell checker as it (I think) treats the first ``` ' ``` as a possessive to whatever comes before the ``` ' ``` and expects an ```s```. For example, ``` ``up'' ``` does nor pass the spell check and suggest ```coup's```, while ``` ``up   '' ``` (space after ```up```) does pass.

PS: great extension.

**Comment by bartosz-antosik** [comment]
Hi! It should be corrected in just released version 2.1.8. Please drop me a line here whether it works for you which means that I understood the issue correctly.

**Comment by quicky84** [comment]
I does work! Thanks.
