### ISSUE TITLE
Adding mediawiki

### ISSUE THREAD

**Issue by tkonop** [bartosz-antosik/vscode-spellright#109]
Dear Bartosz.
Is it possible to add support for Mediawiki document type?
Best regards
Tomasz

**Comment by bartosz-antosik** [comment]
Can you tell me which extension adds this document type? And show some example `mediawiki` documents?

**Comment by tkonop** [comment]
The extension of document is .wiki.
Wikipedia using mediawiki markup:
Formatting: https://www.mediawiki.org/wiki/Help:Formatting/pl
Example:
'''Microsoft Visual Studio''' – [[zintegrowane środowisko programistyczne]] firmy [[Microsoft]]. Jest używane do tworzenia oprogramowania konsolowego oraz z [[Graficzny interfejs użytkownika|graficznym interfejsem użytkownika]], w tym aplikacje [[Windows Forms]], [[Windows Presentation Foundation|WPF]], Web Sites, Web Applications i inne. Aplikacje mogą być pisane na platformy: [[Microsoft Windows]], [[Windows Phone]], [[Windows CE]], [[.NET Framework]], [[Microsoft Silverlight]] oraz konsole [[Xbox|XBOX]].

== Elementy składowe ==
Visual Studio zawiera edytor kodu wspierający [[IntelliSense]] jak również [[refaktoryzacja|mechanizmy refaktoryzacji kodu]]. Zintegrowany [[debugger]] działa zarówno na poziomie kodu źródłowego jak i maszyny. Pozostałe narzędzia w ramach Visual Studio to: designer do tworzenia aplikacji [[Windows Forms]], [[Windows Presentation Foundation|WPF]] i web, narzędzie do tworzenia klas, projektowania baz danych itd. Funkcjonalność Visual Studio praktycznie na każdym poziomie tej aplikacji można rozszerzać za pomocą dodatków.

Visual Studio zawiera zestaw [[Narzędzie programistyczne|narzędzi programistycznych]] ([[Zintegrowane środowisko programistyczne|IDE]]), w skład którego wchodzi:
* Microsoft Visual [[C Sharp|C#]] (od wersji 2002)
* Microsoft Visual [[C++/CLI|C++]]
* Microsoft [[Visual Basic .NET|Visual Basic]]
* Microsoft Visual [[J Sharp|J#]] (wersje 2002-2005)
* Microsoft Visual Web Developer [[ASP.NET]] (od wersji 2005)
* Microsoft Visual [[F Sharp|F#]] (od wersji 2010)

**Comment by bartosz-antosik** [comment]
Hi! By extension I meant which of VSCode's extensions provide support for this document type. But I reckon it is [this one](https://marketplace.visualstudio.com/items?itemName=jakeboone02.mediawiki).

The support for mediawiki has been added in version 2.1.10.  Currently only HTML tags are removed from spelling.

Please let me know if it works for you.
