### ISSUE TITLE
Seems spellright gets confused with apostrophe

### ISSUE THREAD

**Issue by MichaCo** [bartosz-antosik/vscode-spellright#11]
Hi, just updated to 1.0.10 and found that in markdown for example, phrases with apostrophe do not get recognized correctly.

![image](https://cloud.githubusercontent.com/assets/5837539/25435932/0a25f5e4-2a92-11e7-9781-aaa554b0949a.png)

spellright actually suggests to replace it with `doesn't` and right after replacing it, you get the same warning for `doesn` again ;)

Thanks for the great extension btw!

**Comment by bartosz-antosik** [comment]
Oh, an regression. Sorry. Should be fixed in 1.0.11.
