### ISSUE TITLE
Spellcheck line doesn't show up correctly when the word is the last word in a parenthesis

### ISSUE THREAD

**Issue by jeffreymeng** [bartosz-antosik/vscode-spellright#114]
Steps to reproduce:

1. In an html file, add a new `<li>` element.
2. type, not copy/paste (is registereed). A line should show up
3. delete the d and re-type it.
4. The red spellcheck suggestion line disappears, and Cmd+. does not show the prompt.

Expected:
After step 3, the red spellcheck line show reappear.

it also seems that adding and then deleting a space after the `d` in registereed will cause the red line to show up again, but if you repeat steps 1-4, it shows up again.

I think this might be because it is detecting the parenthesis as part of the word?

**Comment by bartosz-antosik** [comment]
Hi! It is not an error. It is intended acting of the component, intended not to underline partially written words while typing.

I agree that it may be frustrating sometimes and I will think whether it could be improved. 

In my extension the word is not spellchecked until some kind of white space is typed. If you would type:

(is registereed

then when typing the closing parenthesis (as you stated) the word would get underline.

But when you return to the word and change it in case like this:

(is registereed)
                   x   ^

and then jump with cursor somewhere else (e.g. behind the word) and type anything it would re-get the underline.

BTW. The same exists in e.g. LibreOffice Writer:

![image](https://user-images.githubusercontent.com/20492548/35964053-e05f5644-0cb6-11e8-994e-285039f3f415.png)

P.S. Main problem is that VSCode does not have events that would inform extension about cursor jump (e.g. in Firefox when you re-type the 'd' from your example it will also not underline the word until you either type something like a white space (e.g. parenthesis) or jump with the cursor elsewhere).

**Comment by jeffreymeng** [comment]
I see. It's just confusing how the same word can be spell checked right and wrong.
