### ISSUE TITLE
Request: Add support for EN-GB

### ISSUE THREAD

**Issue by dialex** [bartosz-antosik/vscode-spellright#118]
Currently only supports EN, which defaults to EN-US. This gives me several false positives.
In the meantime I'll be using an [alternative extension](https://marketplace.visualstudio.com/items?itemName=swyphcosmo.spellchecker).

**Comment by bartosz-antosik** [comment]
I have already replied under your (bit quick I would say) review. ;-) 

Of course en-GB is supported from the very beginning! Please have a look at `spellright.groupDictionaries` configuration setting. Once you set it to `false` regional dictionaries will not be grouped under common name and so revealed both under the list to choose from and in the settings.

**Comment by dialex** [comment]
I was not aware of that config. Thanks for clarifying. I'll close this issue and update my review ;)

**Comment by bartosz-antosik** [comment]
Thanks for all the updates to the rating and here. You may want to have a look at the [readme](https://github.com/bartosz-antosik/vscode-spellright/blob/master/README.md) where all of the configuration is explained. Regional variants of the dictionaries are hidden intentionally by default as to simplify the usage as much as possible. But there is quite some more options underneath.
