### ISSUE TITLE
British English 

### ISSUE THREAD

**Issue by sitrobotsit** [bartosz-antosik/vscode-spellright#119]
Hello,

I'm on macOS High Sierra and my language is set to English (U.K.). However, spelllright does not appear to pick this up. e.g. "enrolment" is flagged as an incorrect spelling because "enrollment" is the American spelling of this word. 

Am I missing something? Or does the app only support American English?

**Comment by bartosz-antosik** [comment]
Hi! Excuse me taking shortcut, but could you please have a look at #118?

**Comment by bartosz-antosik** [comment]
Quoting from #118: Please have a look at `spellright.groupDictionaries` configuration setting. Once you set it to false regional dictionaries will not be grouped under common name and so revealed both under the list to choose from and in the settings.
