### ISSUE TITLE
Spell checking default to "off" on User Settings files

### ISSUE THREAD

**Issue by webluke** [bartosz-antosik/vscode-spellright#12]
- VSC 1.11.2
- WIndows 10 Pro 15063.138
- Spell Right 1.0.12

Files listed in spellright.documentType do not auto start spell checking. These files should default to the set spellright.language when VSC starts / loads the file. 

![image](https://cloud.githubusercontent.com/assets/5162188/25673666/5d1e92fc-2ff5-11e7-921e-eead8a653c64.png)

**Comment by bartosz-antosik** [comment]
The name of contributed setting was misspelled ;-). It should be "spellright.documentTypes". Corrected in version 1.0.16.
