### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by lbittarello** [bartosz-antosik/vscode-spellright#121]
Thanks again for the great package. :)

I'm suddenly getting a lot of new hints. I wrote a mock document to show it:

![test](https://user-images.githubusercontent.com/15511539/36829655-d6823f80-1ce5-11e8-87a0-c654c47e5586.PNG)

**Comment by bartosz-antosik** [comment]
Could I have  the document in paste-able format?

**Comment by lbittarello** [comment]
Here you go!
[test.zip](https://github.com/bartosz-antosik/vscode-spellright/files/1771464/test.zip)

**Comment by bartosz-antosik** [comment]
It seems that corrections in 2.1.25 remove the lighting you can see. I am sorry for the confusion but my proficiency in LaTeX is quite limited. I am a beginner actually. But I would very much like Spell Right be a good LaTeX speller. Many corrections come from my own experience which is as I have said limited.

Please let me know anything else you notice.

**Comment by lbittarello** [comment]
The update fixes almost everything. I've only found one remaining issue: commands are checked if they are the first word of the parameter of a command whose parameters are verified. For example, `\footnote{\bfseries blah}` shows an error, but `\footnote{blah \bfseries}`. I believe that line 38 of the [latex parser](https://github.com/bartosz-antosik/vscode-spellright/blob/master/lib/parsers/latex.js) is responsible. Because it matches on `[\\\W]+`, the slash of the command in the parameter is matched along with the brace of the main command. Replacing this bit with `[\\\W]?` seems to fix this issue, but it may have side effects I'm unaware of.

Sorry for the insistence. Trying to help!

**Comment by bartosz-antosik** [comment]
Do not be sorry! Many thanks for the help! I appreciate it.

**Comment by bartosz-antosik** [comment]
I did something that should heal the problem you indicated above. It is implemented in version 2.1.26. Please have a look.

**Comment by lbittarello** [comment]
It seems to do the trick!

Thanks for your great work!

**Comment by bartosz-antosik** [comment]
Great. Many thanks. Shall you notice anything else that might improve LaTeX spelling pleases start an issue.
