### ISSUE TITLE
In-Document Command spellcheck: off not always work

### ISSUE THREAD

**Issue by lucapavy** [bartosz-antosik/vscode-spellright#122]
First time in my life I report an issue here, sorry if I make mistake.

`spellcheck: off` in markdown files does not work in these situations:
- `<!-- spellcheck: off -->`, inside a comment
- `   ` `spellcheck: off`, with at least 4 spaces at the begging. In my configuration, 4 spaces is a tab 

I suppose, this problem appears just with last VSC versions. Actually I use 1.21.0, architecture x64

For example:

![image](https://user-images.githubusercontent.com/37207798/37197616-bd2ca84e-237b-11e8-915b-223029c43b07.png)

**Comment by bartosz-antosik** [comment]
Hi! Thanks for bringing up the issue.

This is a bit crazy! I mean, comments in Markdown!

There are two cases, each we will deal with separately:

* `<!--  -->` construct is considered by my parser as HTML tag and recently removed from spelling in markdown (in version 2.1.18).
* Indented `spellcheck: off` is considered inline code block and also removed from spelling in markdown parser. It will work not indented but will be visible in final markdown. When indented it will be visible as code block. Both options do not seem very elegant.

If you however try to discover what is considered comment in Markdown then you probably sooner or later come across [this article](https://stackoverflow.com/questions/4823468/comments-in-markdown) which says that most platform independent comment in Markdown is this:

`[//]: # (spellcheck: off)`

It is nasty but it works. And this was my intention during writing the parser.

Now I see however that `<!-- -->` can also be considered as "working" comment in Markdown. I will try to extend comments parsing to this construct so this should work for In-Document commands.

**Comment by lucapavy** [comment]
Hi! Thanks for the fast reaction. My compliment.

I'm using `<!-- -->` because VSC makes it with "Toggle Line Comment" command.

But the `[//]: # (comment)` is good for me, even better. I'm going to use it, also replacing actual comments.

Therefore, feel free to throw away my request. 

Thanks and Regards
