### ISSUE TITLE
Avoid spell checking inside certain \begin{...} blocks

### ISSUE THREAD

**Issue by ndmitchell** [bartosz-antosik/vscode-spellright#123]
Given the fragment:

```latex
\begin{minted}{haskell}
type Build c i k v = Compute c k v -> k -> Maybe i -> (k -> v) -> (i, k -> v)
\end{minted}
```

This complains that `i` should be `I`, but I'd really like to say don't spell check inside `minted` blocks as they are program code, so not something you can readily spell check. I couldn't find any existing toggles to achieve that, but please let me know if I missed one.

**Comment by bartosz-antosik** [comment]
Hi! Yes, there is kinda switch! You have to add this to either User or Workspace settings:

```latex
    "spellright.ignoreRegExpsByClass": {
        "latex": [ "/\\\\\\begin{minted}[^$]*\\\\\\end{minted}/gm" ]
    }
```

For more clue see the description of `spellright.ignoreRegExpsByClass` in README.

**Comment by ndmitchell** [comment]
Thanks, that works! I wonder if that should be a given example in the README, using something like the more standard `verbatim` tag?

**Comment by bartosz-antosik** [comment]
I have added exactly this example to the README. It will publish with any new release there will be, it's probably not worth a separate release.

Could you please elaborate a bit more on this `verbatim` tag?

**Comment by ndmitchell** [comment]
Agreed its not worth publishing a new version just for it. The example is really helpful!

The `\begin{minted}` blocks are used for formatting code by some people, as it provides advanced features like coloring, but there are many such modes. The "default" one that ships with Latex, and has least features but is well known by everyone, is `\begin{verbatim}`, so that might make for a better example - everyone knows verbatim, and only a much smaller number of people know minted.

Thanks for the very awesome spell checker!

**Comment by bartosz-antosik** [comment]
Oh, thank you, now I understand. There are many approaches to LaTeX sometimes you can miss something like this. But I am not very advanced with LaTeX so maybe this is the true reason.

If only you would spot anything that could improve LaTeX spelling please start a new issue!

**Comment by bartosz-antosik** [comment]
Oh, thank you, now I understand. There are many approaches to LaTeX sometimes you can miss something like this. But I am not very advanced with LaTeX so maybe this is the true reason.

If only you would spot anything that could improve LaTeX spelling please start a new issue!
