### ISSUE TITLE
Multiple languages support

### ISSUE THREAD

**Issue by Deilan** [bartosz-antosik/vscode-spellright#125]
What about simultaneous multiple languages support? Is it implemented in some way? Is there any roadmap for it?

It's quite a popular case when one writes code in english and use comments in a native language.

**Comment by bartosz-antosik** [comment]
Yes, you can switch languages in one document, however not in a manner you propose. You can switch language within document using In-Documment commands (see in README).

I will think whether it is doable to assign language to context class (see `spellright.spellContext` for details).

**Comment by bartosz-antosik** [comment]
It is implemented in version 2.2.0.

Please have a look at these configuration settings:

`spellright.languageContext` and `spellright.languageContextByClass`.

**Comment by GandalfSaxe** [comment]
Just to make sure: There's no way to have multiple languages enabled at the same time (i.e. in an additive manner)?

**Comment by bartosz-antosik** [comment]
Not at the moment. But I am willing to implement this ([#171](https://github.com/bartosz-antosik/vscode-spellright/issues/171)). Just cannot tell how soon.
