### ISSUE TITLE
Spell Right reports some otherwise valid RegExps as "malformed"

### ISSUE THREAD

**Issue by 0112358437189887641562819** [bartosz-antosik/vscode-spellright#129]
I'm writing LaTeX/TeX and Markdown that includes those. I'd like to ignore spelling of environment names -- I could add static entries for things like ``pmatrix`` , ``bmatrix``, ``Bmatrix``, etc., but then those won't be caught elsewhere. So I made the following rule:

``````javascript
"spellright.ignoreRegExpsByClass": {
    "markdown": [
      "/(\\\\(begin|end|start|stop)([\\[\\{][0-9a-z]+[\\]\\}])+)/ig"
    ]
   // and same for "latex" and "tex" ...
``````

I've successfully tested that expression (with ``\\`` converted to ``\``) with vscode's built-in find/replace and some online regex testers. With all those, it works as I expect.

However, *Spell Right* reports via notification that the regular expression is "malformed" and will be ignored. Am I misunderstanding something about how *Spell Right* uses regular expressions?

**Comment by bartosz-antosik** [comment]
Hi! Could you show me please an example (small doc) of what you would like to ignore?

**Comment by 0112358437189887641562819** [comment]
Example document below. I want *Spell Right* to ignore automatically ignore ``fancyarray``, ``rcl``, ``fancmatrix``, ``anotherfancymatrix``, ``yetanotherfancymatrix`` because they're part of the ``\begin`` and ``\end``  (or alternatively ``\start`` and ``\stop``) commands. I do not want to add those words to user or workspace dictionaries.

``````latex
\begin{fancyarray}{rcl}
  \begin{fancymatrix}
    a & b \\ c & d
  \end{fancymatrix}
  \cdot
  \begin{anotherfancymatrix}
    e & f \\ g & h
  \end{anotherfancymatrix}
  & = &
  \begin{yetanotherfancymatrix}
    {a \, e + b \, g} & {a \, f + b \, h}
    \\
    {c \, e + d \, g} & {c \, f + d \, h}
  \end{yetanotherfancymatrix}
\end{fancyarray}
``````

**Comment by bartosz-antosik** [comment]
Now I understand my confusion: it spells quite OK in LatTeX. I was missing the point that this is Markdown with LeTeX inserts.

Anyway, the expression should look like this:

`"/(\\\\\\(begin|end|start|stop)([\\\\[\\\\{][0-9a-z]+[\\\\]\\\\}])+)/ig"`

Don't ask me why. This is just JSON quoting followed by JavaScript quoting...
