### ISSUE TITLE
Spell checking not working in .mustache (HTML) files

### ISSUE THREAD

**Issue by webluke** [bartosz-antosik/vscode-spellright#13]
- VSC 1.11.2
- WIndows 10 Pro 15063.138
- Spell Right 1.0.12

With spell checking enabled on a .mustache template file that is HTML no spelling is checked. Need options to check spelling if it's in code or in strings or just text files.

![image](https://cloud.githubusercontent.com/assets/5162188/25673908/43f40298-2ff6-11e7-9543-a79c621b41f3.png)

**Comment by bartosz-antosik** [comment]
This is not a native document type. Added in 1.0.16.
