### ISSUE TITLE
Wrong error indicator in Markdown doc with HTML code

### ISSUE THREAD

**Issue by neilsustc** [bartosz-antosik/vscode-spellright#131]
![image](https://user-images.githubusercontent.com/7588612/37955382-0840d69e-31db-11e8-94eb-3712697d956a.png)

Test snippet

```markdown
<div></div>

The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy dog
The quick brownn fox jumps over thhe lazy dog
```

**Comment by bartosz-antosik** [comment]
Could you please confirm, that when you insert empty line atop the document the squiggles are placed in correct row?

**Comment by bartosz-antosik** [comment]
Should be fixed in version 2.2.0.

**Comment by neilsustc** [comment]
Just tested. The squiggles are in right places if there is a empty line at the beginning of the doc.

**Comment by neilsustc** [comment]
Another corner case 😂

```
<!-- <div
-->

The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy dog
The quick brownn fox jumps over thhe lazy dog
```

**Comment by bartosz-antosik** [comment]
Thanks for pointing this out. It has actually shown a very distant problem. I hope I have pinpointed it and it should be removed in next release (will have a note in CHANGELOG). It can be generalized as multi-line XML/HTML tag that is causing the problem.

Markdown is very tricky. It would call for a proper parser but there is so many varieties of Markdown out there that it is nearly impossible to do anything about this. Even VSCode itself is sometimes inconsistent about Markdown, as you can see e.g. [here](https://github.com/bartosz-antosik/vscode-spellright/issues/105#issuecomment-354291439).

**Comment by neilsustc** [comment]
👍
