### ISSUE TITLE
Suggestions are gibberish on Ubuntu

### ISSUE THREAD

**Issue by athosbr99** [bartosz-antosik/vscode-spellright#132]
I used to use (?) VS Code with this extension on Windows 10, but made the switch to Ubuntu a while ago. I still use VS Code and this extension to write LaTeX files.

However I noticed that while the app can get the words that are wrong, it does not gave sane suggestions. The suggestions are ofter unrelated to what I wrote or not what I expected (I usually make errors related to accents). 

I am using Portuguese (Brazil) as main language. It doesn't happen when I use English (American).

Example:

![screenshot example](https://user-images.githubusercontent.com/6440060/38283902-054df494-378f-11e8-9ffa-59c8906c3cf7.png)

The expected suggestions were educação and computação.

**Comment by bartosz-antosik** [comment]
Hello, thanks for reporting.

On Ubuntu unlike Windows Spell Right uses HUNSPELL backend. This may be the problem.

1. Could you please post these words in text so that I could make some inference?
2. Is the dictionary taken from the link in my README? Are you sure the dictionary is UTF-8 (how to described in README)?

**Comment by athosbr99** [comment]
The Hunspell page says that Firefox and Chrome uses it. Since both of them gave correct suggestions, Hunspell should work fine.

The three files on Dictionary folder are on utf8 encoding, and I took them from the repo on the README. 

The words used on the example are educacao, educassao, edicação, computassao, compotação, computacao.

**Comment by bartosz-antosik** [comment]
Sorry to say, but it looks like some problem with the dictionary. Once you use `Portuguese (European)` from the same source, it suggests a very different things:

![image](https://user-images.githubusercontent.com/20492548/38295065-1b7ef7c8-37ed-11e8-8dc5-2c56d4a410af.png)

I am to far from Portuguese to try to explain this. It may be necessary to search for another dictionary or maybe notify someone who maintains the dictionary.

**Comment by athosbr99** [comment]
The screenshot you posted is more close to what I want. I checked and indeed the files on https://github.com/titoBouzout/Dictionaries are old. Some feedback on progress:

I tried using dictonaries from Mozilla (https://addons.mozilla.org/en-US/firefox/addon/corretor/) but the .aff file from them has some difference in syntax and it doesn't work. The ones on LibreOffice (https://extensions.libreoffice.org/extensions/vero-verificador-ortografico-e-hifenizador-em-portugues-do-brasil) aren't on UTF-8. I tried the conversion suggested to UTF-8, but it seems to produce more gibberish corrections or it crashes the accents.

**Comment by bartosz-antosik** [comment]
If you would maybe eventually find some better dictionary for Brazilian Portuguese, please let me know in this thread. It may be very useful for other people. Thank you.

**Comment by gusbemacbe** [comment]
Just modify the dictionary file and change the ISO to UTF-8.

**Comment by athosbr99** [comment]
I used the files from the @gusbemacbe repo https://github.com/gusbemacbe/LanguagePortuguese and it works. Now I have some sort of dictionary again. Yay
