### ISSUE TITLE
Spellchecking of words in latex with diacritics

### ISSUE THREAD

**Issue by philipstarkey** [bartosz-antosik/vscode-spellright#133]
I have a LaTeX document that contains names where some letters have diacritics. For example, let's consider the example `Schrödinger`. In LaTeX, I write this as `Schr\"{o}dinger`. Spell-right reports that `Schr` is an unknown word (similarly, if `dinger` was not in the dictionary, it would report that as a separate misspelled word). 

There doesn't seem to be anyway to manually add this to the dictionary in a way that makes spellright treat the whole word as correct (unless you want to add `Schr` and `dinger` as separate entries which seems wrong since typing `Schr ` by itself would then not raise a spelling error).

**Comment by philipstarkey** [comment]
Additionally to this, words with numbers in the middle (typically product names, for example `h5py` or `H5py`) also exhibit this behaviour (where adding them to the dictionary doesn't stop spellright from marking them as misspelled)

**Comment by bartosz-antosik** [comment]
This second thing (digit inside a word not looked up in user dictionaries) should be corrected in just published version 2.2.3. Please do tell if it works for you.

**Comment by bartosz-antosik** [comment]
Unintentionally closed.

**Comment by bartosz-antosik** [comment]
Could you maybe as someone apparently more fluent in LaTeX provide a list of (some, all) diacritics that LaTeX can interpret? I can think of \", \^, \`, \', \, and maybe few others but I suspect there are more of them.

**Comment by philipstarkey** [comment]
I believe a complete list is [here](https://en.wikibooks.org/wiki/LaTeX/Special_Characters#Escaped_codes) (at least this is what I use as my reference because I always forget what they are). Obviously, the character inside the `{}` could be anything (or even apparently multiple characters in at least one case...).

Unfortunately my exposure to diacritics is only when using them to correctly spell peoples names, so I may not be aware of all of them if that list is not complete. But I think that's at least a good start.

**Comment by bartosz-antosik** [comment]
Thanks for the reference.

**Comment by iPieter** [comment]
I'd like to point out that, in addition to the list and examples provided by @philipstarkey, the characters don't have to be inside `{}`. For example, `re\"ele` (renders to `reële`) or `\'e\'en` (`één`) are valid inputs as well.

**Comment by bartosz-antosik** [comment]
Thanks for the notice @iPieter. It is even worse - you can write `Shr\"{odinger}` and it will render correctly!

I am still not sure what I can do about this.

**Comment by bartosz-antosik** [comment]
Should be done in just published version 2.3.0. Please have a look and if you would spot any regression or something that is not clear then please ask in this thread.

The extension does not implement all possible forms in which these diacritics can be used, but most canonical of them, e.g. it requires to enclose the letter combined in statement `\"{o}` and empty statement after `\AA{}` and `\o{}`. More sophisticated forms should work also in canonical forms, e.g.: `\^{\i}`. Also at the moment short forms will not work (`\"o` etc.)
