### ISSUE TITLE
Spellchecking of product names (in LaTeX) which are camelcase

### ISSUE THREAD

**Issue by philipstarkey** [bartosz-antosik/vscode-spellright#134]
When writing names (such as `We use the library NumPy to ...`) in a LaTeX document, spellright reports `NumPy` as two separate words (`Num` and `Py`). 

There does not seem to be a way to add the single word to the dictionary (or correct the spelling if, for example, you had mistyped it as `NumPx`) via the spellright context menu. 

While you could add the word manually to your dictionary (and this does then stop spellright from flagging the word as misspelled), it would be nice if you could do it from the spellright context menu like you can with every other word!

**Comment by bartosz-antosik** [comment]
Hi! There is currently a way to add such a case to the dictionary: You should select the whole word and then press `Ctrl+P` (or equivalent) and select `SpellRight: Add Selection to Workspace Dictionary`. 

I will consider adding a compound to the context menu, as you suggest.

**Comment by philipstarkey** [comment]
Ah, excellent! That makes things a bit easier for now :)

**Comment by bartosz-antosik** [comment]
In the new version there will be an option in the context menu to add the compound word to the dictionary:

![image](https://user-images.githubusercontent.com/20492548/38486041-26ce5cde-3bdc-11e8-89da-3e34acac9ad0.png)
