### ISSUE TITLE
plugin doesn't do anything at all

### ISSUE THREAD

**Issue by squinkylabs** [bartosz-antosik/vscode-spellright#137]
I've got the plugin installed, I can see it in the extensions window, but it doesn't ever find any spelling mistakes. 

Here's a screen shot from inside visual studio code:
![image](https://user-images.githubusercontent.com/16314838/38481629-96b95992-3b80-11e8-8b86-39e4bc4010d6.png)

Just tried "code spell checker", from side street software. It works nicely.

**Comment by bartosz-antosik** [comment]
Could you please post screenshot of  whole editor window?
What document type is this?
Have you turned spelling on for this document type (by default only plaintext, markdown and latex document types are spelled)?
What OS is this?

**Comment by squinkylabs** [comment]
It's a c++ file.
I didn't find any controllable options -> the "gear" only gives me global enable / disable. Do you have to hand-edit the JSON file to control your spell checker?
win 7 64.

**Comment by squinkylabs** [comment]
oh my goodness - there it is - the big gear shows me all the JSON. I think this will work!

**Comment by bartosz-antosik** [comment]
Please, read the [README](https://github.com/bartosz-antosik/vscode-spellright/blob/master/README.md) file for the extension. First: There is a switch for current document type in status bar (eye icon). Second, on Windows 7 you need to install dictionaries. It is all explained in the README mentioned above.

If you have any doubts beyond what's in README then please feel free to ask!

**Comment by bartosz-antosik** [comment]
Please drop me a line here whether it eventually worked for you.

**Comment by squinkylabs** [comment]
well - now that I enabled checking of cpp files is works. I can't install the dictionary, however, because I don't have a "code" folder in my app data. I know that a VSC issue, and not your issue, but I don't have one.  Instead my VSC keeps config data in a local file. I'll have to ask the internets why this is.

For some reason, while the readme on this github talks about downloading dictionaries, the documentation inside your plugin (as seen in VSC) doesn't mention this. I thought it did, but it's no longer there.

**Comment by bartosz-antosik** [comment]
I kind of don't know what do you mean by documentation in VSCode. To my knowledge it displays exactly the same README as I have pasted link to:

![image](https://user-images.githubusercontent.com/20492548/38506620-aa380ae6-3c1a-11e8-9386-62952e004765.png)

I am also surprised that it does spellcheck anything in Windows 7 without any dictionary.

VSCode is cerainly different than Visual Studio.

**Comment by c3er** [comment]
I have this issue since the last update (I think). Usually I see the current language in the status bar but currently, it is not visible.

If I try to change the language via the command palette (command "SpellRight: Select dictionary (Language)"), I get following error message:

> command 'spellright.selectDictionary' not found

**Comment by bartosz-antosik** [comment]
@c3er Could you please start a new issue, provide some information on what OS, VSCode's version you have?

**Comment by c3er** [comment]
[Done](https://github.com/bartosz-antosik/vscode-spellright/issues/138)
