### ISSUE TITLE
Spellcheck does not always respect "spellright.ignoreRegExpsByClass" setting

### ISSUE THREAD

**Issue by philipstarkey** [bartosz-antosik/vscode-spellright#139]
I have discovered a weird bug while using VS Code + Latex Workshop + Spell Right. I think the bug is to do with Spell Right, and how it uses the `spellright.ignoreRegExpsByClass` setting (but I could be completely wrong)

I currently have this set to
```
"spellright.ignoreRegExpsByClass": {
        "latex": [ "/\\\\\\begin{python}[^]*\\\\\\end{python}/gm" ],
    },
```
in order to ignore code between `\begin{python}` and `\end{python}` commands (which define a custom environment I have, using lstlisting, but I think that is irrelevant to this problem and would happen with anything). 

For the most part, this works correctly. However, if in the lower pane (containing problems/output/etc.) the "output" terminal is selected, Spell Right reports spelling errors in between these tags. If I switch to the "problems" tab, all the reported spelling errors quickly vanish and do not return. 

I find it really odd this only happens when the "output" tab is selected (you can also substitute the "problems" tab for either the debug or "terminal" tabs), but it seems to be reliably reproducible for me.

**Comment by bartosz-antosik** [comment]
Thanks! Could you please post here a simple document that replicates the thing?

**Comment by philipstarkey** [comment]
```
some words
\begin{python}
speling mistakes in here should be ignored
\end{python}
some more words and a speling mistake
```
![image](https://user-images.githubusercontent.com/2508881/38597829-2423db36-3d9d-11e8-9e4f-d63e440ea84e.png)
![image](https://user-images.githubusercontent.com/2508881/38597836-2e72518a-3d9d-11e8-903b-8d49c6d968a8.png)

More weird behaviour: If the output terminal has focus (e.g. you clicked "output" and then next to "ready" in the above picture), and you change focus to another window (e.g. Chrome or even just into the test.tex editor within VS Code) then it swaps from the incorrect behaviour to the correct behaviour. However, if the output terminal does not have focus (e.g. you clicked "output" only and did **not** click where it says "ready") and you change window focus, then it does not correct itself.

**Comment by bartosz-antosik** [comment]
Excuse e a bit off-topic, possibly unrelated question, but what do you have any idea why do you have `en-AU` as the language? It should rather be expanded to `English - Australia`. What other languages look like? What does language pick list look like in your case?

**Comment by philipstarkey** [comment]
Hmm, seems like for some reason I manually set the language in the settings file to "en-AU". Not sure why I thought I was supposed to do that. The language list only has "English" for me, however it seems to follow "Australian" spelling rather than "US" spelling anyway (presumably because my OS language is set to Australian?) so I've left it as "English" (which sets the relevant parameter in the settings file to "en")

Changing this doesn't seem to affect the original bug though!

**Comment by bartosz-antosik** [comment]
BTW: `spellright.groupDictionaries` controls using of region code (`-AU` etc.) in case you need this. I do not think this is related, but was just surprised.

**Comment by bartosz-antosik** [comment]
Hi, this should be fixed in just published version 2.2.10. Please drop me a line whether it works for you!

**Comment by philipstarkey** [comment]
Hi,

It's a lot better, but not 100% fixed. For short examples, it seems to work. For long examples (like a 1000 line long latex file), quickly switching focus between the "output" terminal, the document editor and then back to the "output" terminal seems to trigger the issue again.

Also, I realised that my regex was "greedy" when it shouldn't be. The correct version is `"latex": [ "/\\\\\\begin{python}[^]*?\\\\\\end{python}/gm" ],`. I don't think this effects this bug, but it probably makes sense to test with the correct version! 

FYI: I based the regex string off the one in your documentation on the VS code extension home page. I think it makes sense to update that example to be non-greedy too!

**Comment by bartosz-antosik** [comment]
Hi! Tried to reproduce. Can not. Could you provide please a synthetic document that could help me reproduce this?

I agree about the non greedy RegExps. I will correct this in next release.

**Comment by bartosz-antosik** [comment]
Sorry about the request above, but I have created a TEX file of over 1000 lines and tried to replicate the behavior but I was unsuccessful.

**Comment by philipstarkey** [comment]
Not a problem! I've created a dummy file [here](https://pastebin.com/E5v3hJNZ). I seem to be less reliably able to reproduce the error if the output terminal is on things like "tasks" or "extensions". It's more reliably reproduced when the Output tab is on the "LaTeX Compiler" option (which is provided by LaTeX workshop).

Strangely, it seems that swapping what is displayed in the "output" tab using that drop down menu seems to retrigger the document to be spellchecked. So sometimes you can trigger the bug just by swapping between what is displayed in the output terminal (without having to do the strange clicking sequence I described a couple of posts ago)

Hope that helps you track it down! If you still can't reproduce it, is there a way I can debug what is happening easily?
