### ISSUE TITLE
Add support for disabling per file

### ISSUE THREAD

**Issue by futagoza** [bartosz-antosik/vscode-spellright#14]
Would you please consider adding support for disabling the extension if the file has the comment block:

```js
/* spellright-disable */
```
```html
<!-- spellright-disable -->
```

**Comment by futagoza** [comment]
Although I wont be needing it, some people might also find it useful if, like ESLint, you can re-enable it:

```js
/* spellright-enable */
```
```html
<!-- spellright-enable -->
```

**Comment by bartosz-antosik** [comment]
These are "InDoc" commands. Starting from 1.0.17. So far there are spellcheck-off and spellcheck-on. Please see README.md for details.
