### ISSUE TITLE
Spellchecking symbols

### ISSUE THREAD

**Issue by AliZeineddine93** [bartosz-antosik/vscode-spellright#140]
I have some comment lines ("%%%%%%%") in my latex file to help me organize my text. Why are the percentage symbols spellchecked? I found it also applies to the "^" and the "@" symbols, but not to #, $, !, ~, &, ...

![capture](https://user-images.githubusercontent.com/16150497/38811947-3e1b7728-418b-11e8-82af-29f8ca486878.PNG)

I tried to search online how to write "ignoreRegExps" rules, I just couldn't grasp the syntax, and I didn't find any reference that helps.

What I want is to disable spellchecking symbols, and only apply it to words with letters. Any help would be really appreciated!

**Comment by bartosz-antosik** [comment]
Could you tell me what OS is this?

**Comment by AliZeineddine93** [comment]
OS: Windows 7 Ultimate, 6.1.7601 Service Pack 1 Build 7601
VS code: 1.22.2
Spellright: 2.2.14

**Comment by bartosz-antosik** [comment]
Should be fixed in version 2.2.16. Please drop me a line here whether this works for you or if you would encounter any side effect of the change.

**Comment by AliZeineddine93** [comment]
It works perfectly! Thank you!
