### ISSUE TITLE
Chinese punctuation

### ISSUE THREAD

**Issue by neilsustc** [bartosz-antosik/vscode-spellright#143]
I would suggest to add `，。、《》？！；：‘“’”「」（）【】` to the word split pattern since sometimes the spell checker is confused with them.

**Comment by bartosz-antosik** [comment]
Could you please provide some example?

**Comment by neilsustc** [comment]
`中文（Englis）`

![image](https://user-images.githubusercontent.com/7588612/38871597-e75f374a-4283-11e8-8a8f-5a1f7bfff403.png)

**Comment by neilsustc** [comment]
An easy solution is putting `cword = cword.replace(/[，。、《》？！；：‘“’”「」（）【】]/g, ' ');` [here](https://github.com/bartosz-antosik/vscode-spellright/blob/master/src/spellright.js#L710)

(I failed to build your extension, maybe I need some tricks)

**Comment by bartosz-antosik** [comment]
Sorry I have not let you know I have already done this. It is just waiting so maybe I will manage to add some another issue resolved. Especially #142 took some time to explain.

**Comment by bartosz-antosik** [comment]
Should be corrected in just published version 2.3.0.
