### ISSUE TITLE
")" is marked as spelling mistake

### ISSUE THREAD

**Issue by Karuso33** [bartosz-antosik/vscode-spellright#144]
Consider this latex document
```
\documentclass[a4paper]{article}
    \usepackage[utf8]{inputenc}
    \usepackage{mathtools}
\begin{document}

% Also doesn't work in equation*, align(*) <-- That shouldn't be marked as wrong either
% and probably a few others
\begin{equation}
    \label{my_ref}
    C = 2 n \sin \left(\frac{\pi}{n} \right)
\end{equation}

% It does however work properly here
\[C = 2 n \sin \left(\frac{\pi}{n} \right)\]

Also this should not be spell checked (Why is this wrong \ref{my_ref}).
Also this should not be spell checked (Why is this wrong \ref{my_ref} and this is not).
\end{document}

```
And now have a look what is being marked as spelling mistake:
![image](https://user-images.githubusercontent.com/1777464/39085819-b8f37f8a-4588-11e8-8816-fcb96607f458.png)

For some reason many of the closing parantheses ")" are marked as wrong. As you can see, this happens in math-environments (but not the \\[...\\] one) as well as in regular text.

As far as I can tell, this happens in every language (I only tried English and German). This was tested on Ubuntu 16.04.

**Comment by bartosz-antosik** [comment]
Should be corrected in just published version 2.3.0.

**Comment by gvallicrosa** [comment]
In 2.3.0 the whole last word is marked as wrong with the closing parentheses. Tested in latex.

![screenshot from 2018-04-28 10-27-02](https://user-images.githubusercontent.com/2340232/39394167-d372da7c-4ace-11e8-8edc-fcd352a10dd4.png)

**Comment by bartosz-antosik** [comment]
Should be fixed with next release. This is a problem with Hunspell back-end, with which I do not test every issue with (because it is not native to the system I work with). It cannot spell correctly a word with space at the end which is bit odd.
