### ISSUE TITLE
javascript keywords displayed as errors 

### ISSUE THREAD

**Issue by thisisPratzz** [bartosz-antosik/vscode-spellright#145]
Is there any way to ignore JS or any specific file format errors?

**Comment by bartosz-antosik** [comment]
Could you please be more specific about that?

Generally JavaScript is spelled using code parser which spells only comments & strings, so it should absolutely not spell JavaScript keywords:

![image](https://user-images.githubusercontent.com/20492548/39168793-7ee8c9d0-4795-11e8-8e67-849741d61421.png)

There are many ways to ignore specific words, they are described in README. For example you can create a file `javascript.dict` containing keywords you want considered spelled correctly (ignored) and place it in `.vscode` folder of your workspace itp.
