### ISSUE TITLE
Add to user dictionary doesn't work with custom Code build

### ISSUE THREAD

**Issue by kanru** [bartosz-antosik/vscode-spellright#147]
My settings directory name is `/Users/kanru/Library/Application Support/Code - OSS/User/`

I found the code here https://github.com/bartosz-antosik/vscode-spellright/blob/master/src/spellright.js#L1680-L1693 assumes the folder name so it cannot find the correct path.

**Comment by bartosz-antosik** [comment]
Hi! As far as I can tell extension cannot ask VSCode where is the user profile stored. Hence the solution. I had already problems (which were sorted out more or less) with portable version. But honestly I cannot do this for custom builds.

Most extensions which rely on just settings do not need this information. I could have thought of storing the words among settings but it would be extremely inconvenient.
