### ISSUE TITLE
Ignore <style> tag inside Markdown

### ISSUE THREAD

**Issue by neilsustc** [bartosz-antosik/vscode-spellright#148]
Could this extension skip the `<style>` section inside Markdown?

![image](https://user-images.githubusercontent.com/7588612/39302105-19184932-4984-11e8-9fa7-c45ed940b4a2.png)

**Comment by bartosz-antosik** [comment]
If you could please have a look at `ignoreRegExpsByClass` description in README. There is an example on how to ignore `<script></script>` sections in HTML. Should be similar.

**Comment by neilsustc** [comment]
Wow, have never expected such a setting. Works really well!

**Comment by bartosz-antosik** [comment]
Please have a look at the README. There are wonders there! ;-)

But seriously, I am very poor in advertising things, but over time there has gathered lot of useful settings!

**Comment by neilsustc** [comment]
In fact, I did found #78 before open this issue. But the setting name `ignoreRegExpsByClass` is kind of misleading I think 😳
