### ISSUE TITLE
Possible regression due to parenthetical plurals

### ISSUE THREAD

**Issue by philipstarkey** [bartosz-antosik/vscode-spellright#149]
I have the word "globals" added to my user dictionary. 

If I write "(blah blah globals blah blah globals)" then spell right thinks the first instance of "globals" is spelt correctly but the second instance is not. 

However:

-  "global(s)" is fine (as is "(global(s))".
- "globals(s)" is fine but "(globals(s))" is not (I know this one is a nonsense word, it's just meant as a demonstration).

Looks like maybe the regex for matching parenthetical plurals might be getting confused for words that end a sentence inside brackets? I'm pretty sure it didn't used to have this problem.

**Comment by philipstarkey** [comment]
Actually, I've just discovered the bug also exists when you have "(globals ....)" as well which might mean it's not related to parenthetical plurals.

**Comment by bartosz-antosik** [comment]
Should be OK in 2.3.2.

**Comment by cilkay** [comment]
Confirmed that it is working in 2.3.2. Thank you.
