### ISSUE TITLE
Wrong file type handling in split view

### ISSUE THREAD

**Issue by neilsustc** [bartosz-antosik/vscode-spellright#15]
If you have a `.tex` file in the left editor group and a `.txt` file in the right editor group, the `.tex` file seems to be checked with the rules for `.txt` file.

![spell-iloveimg-compressed](https://cloud.githubusercontent.com/assets/7588612/25941766/3869af4a-366d-11e7-8406-438dc6e1bd58.gif)

**Comment by bartosz-antosik** [comment]
Should be fixed in 1.0.17!
