### ISSUE TITLE
Possessive apostrophes with user dictionary words (possible regression?)

### ISSUE THREAD

**Issue by philipstarkey** [bartosz-antosik/vscode-spellright#150]
I don't think this was a problem before so I think it's a regression but I'm not 100% sure.

Names that I've added to my user dictionary seem to be reported as misspelled is they are followed by an possessive apostrophe.

Example, add `Steck` to the user dictionary
Spell right reports `Steck` as correctly spelled but `Steck's` as incorrectly spelled.

However names that are presumably in the dictionary (like `John`) do not not exhibit this behaviour. You can currently work around it by adding `Steck's` to the dictionary, but I'd rather not have to do that for everyone's name! Interestingly, `Steck'` is fine.

**Comment by bartosz-antosik** [comment]
Hi! I suppose I did it in 2.3.2, but I have a mixed feelings about it.
