### ISSUE TITLE
Since I have updated the extension today, the eye icon has disappeared. 

### ISSUE THREAD

**Issue by gusbemacbe** [bartosz-antosik/vscode-spellright#152]
Hello, 

In the former version, eye icon appeared normally in the bottom bar. But as you have upgraded the version today, I have updated, the eye icon has disappeared. 

![image](https://user-images.githubusercontent.com/2257024/39607296-7fdd8952-4f10-11e8-9e09-cfb88fe2059c.png)

* Ubuntu 18.04 64 bits
* VSCode Insiders 1.23.0
* Shell 1.7.12
* Renderer 58.0.3029.110
* Node 7.9.0
* HP EliteBook 8460P [(click details)](https://support.hp.com/au-en/document/c02753879)

* `settings.json`:
```json
    "spellright.documentTypes": 
    [
        "html",
        "markdown",
        "latex",
        "plaintext",
        "php"
    ],
    "spellright.language": "pt",
    "spellright.suggestionsInHints": false,
```

**Comment by gusbemacbe** [comment]
It appeared after 20 minutes. It seems to be debugging or loading bug. 

As it appeared after 20 minutes, spelling checker interprets some symbols as wrong:
* «», 
* «anything»,
* –
* C (only one letter)

I also ran one command in a HTML file:
```html
<!-- %% spellcheck-language en_GB -->
<!-- %% spellcheck-language pt_PT -->
```
And the eye icon appeared as red with "multi" and alerted it was an error, saying: "Spell Checking - Multiple Languages (missing: en_GB -->, pt_PT -->)".

**Comment by bartosz-antosik** [comment]
Hi! Thanks for detailed report with a lot of details. I think what you describe are three distinct things actually:

1) There are sometimes issues with "Insders" build (#142). Often they are not Spell Right related. I cannot reproduce the 20 minutes starting time, maybe you can see `Developer Tools` (`Help` -> `Toggle Developer Tools`) to see whether there is something related to Spell Right?

2) I will have a look, these may be related to the spelling back-end that you use (Hunspell, native on Linux). There was a change related to these recently (#143).

3) This is true, it may be considered a bug, but it has changed in version 2.1.32. These `spellcheck-langiage` in-document switches will work fine when in line comments (e.g `//` in c++). They fail when put in block comments as you did. I will address this shortly.

**Comment by gusbemacbe** [comment]
Hi,

1. Ah, I have just started VSCode and open the HTML file, and the eye appears quickly in milliseconds because it is already cached/cookied. But I believe it is CPU/GPU problem or cache or cookie problem. 
2. And do not forget of taking all these quotation marks: https://en.wikipedia.org/wiki/Quotation_mark#Summary_table and look at the table of typography at the right: https://en.wikipedia.org/wiki/Question_mark
3. Yes, `//` is supported only in C, C++ PHP and Python. And `##`?

**Comment by bartosz-antosik** [comment]
Could you show me how it gets wrong on point 2 (quotation marks)? My instance is seem to be working ok with these. As you might have examined #143 has added these symbols.

**Comment by gusbemacbe** [comment]
* European Portuguese:
![image](https://user-images.githubusercontent.com/2257024/39678202-a7365448-515e-11e8-8daa-d7f9dab7f1bb.png)

* French:
![image](https://user-images.githubusercontent.com/2257024/39678234-12b0557a-515f-11e8-8c00-2f854e7bf447.png)

* Italian:
![image](https://user-images.githubusercontent.com/2257024/39678252-518a500c-515f-11e8-84c6-9b78da6b4221.png)

* Spanish
![image](https://user-images.githubusercontent.com/2257024/39678265-817b49a6-515f-11e8-8335-d6b52cbfdbca.png)

* Swiss German:
![image](https://user-images.githubusercontent.com/2257024/39678317-8e9154ea-5160-11e8-8629-875470d3f93d.png)

* Germany German:
![image](https://user-images.githubusercontent.com/2257024/39678324-b45d7d8e-5160-11e8-9b0e-a0b371942a02.png)

**Comment by bartosz-antosik** [comment]
Also, I don't get this "C (only one letter)" situation. Could you please shed some light in this?

**Comment by bartosz-antosik** [comment]
Could I see the suggestions they get?

**Comment by gusbemacbe** [comment]
* European Portuguese:

![image](https://user-images.githubusercontent.com/2257024/39712042-ff67957a-51f7-11e8-9705-2c81eced6a3e.png)
![image](https://user-images.githubusercontent.com/2257024/39712057-09d18296-51f8-11e8-9a7c-db209a4bebd6.png)
![image](https://user-images.githubusercontent.com/2257024/39712068-1284a38c-51f8-11e8-8e4c-fb1c69e45868.png)
![image](https://user-images.githubusercontent.com/2257024/39712075-1a903a78-51f8-11e8-9e00-daf1835ace73.png)

**Comment by gusbemacbe** [comment]
* Spanish:
![image](https://user-images.githubusercontent.com/2257024/39712110-3aaf32a0-51f8-11e8-9212-d5c81d609ecc.png)
![image](https://user-images.githubusercontent.com/2257024/39712117-41df37f0-51f8-11e8-9526-a03f8553b78a.png)
![image](https://user-images.githubusercontent.com/2257024/39712125-4bccb3b4-51f8-11e8-8f12-0b6dcc6e71f2.png)
![image](https://user-images.githubusercontent.com/2257024/39712136-54230982-51f8-11e8-9aa6-a459c02e95cf.png)
![image](https://user-images.githubusercontent.com/2257024/39712143-59c55fe8-51f8-11e8-993a-6b128960c359.png)

**Comment by bartosz-antosik** [comment]
Yes, they do, just the language has to be in double quotes. Please see README or CHANGELOG.

**Comment by bartosz-antosik** [comment]
Regarding things combined in this issue:

1) I will not do anything about the Insiders build as a) it works in my installation of Insiders build so I am eager to speculate that it is some other extension which holds Extension Host and causes the delay you describe.

2) Punctuation symbols have been added in version 2.3.4. I will not do anything about misspelling of separate letters in some dictionaries as it turns out it is a dictionary issue. Id does not happen/happens only for selected letters in other languages (dictionaries):

![image](https://user-images.githubusercontent.com/20492548/39750171-d7332bce-52b4-11e8-9700-e556e4724d6c.png)

![image](https://user-images.githubusercontent.com/20492548/39750200-e78f0434-52b4-11e8-87f9-73b7029c42a4.png)

3) In-Document command: `spellcheck-language` has been changed to have the parameter in double quotes to allow for dictionaries which contain space in filenames on some platforms.
