### ISSUE TITLE
Digits in parentheses

### ISSUE THREAD

**Issue by lbittarello** [bartosz-antosik/vscode-spellright#153]
Hi! Digits in parentheses are being flagged as spelling mistakes. For example, "(1)" is underlined. Multiple-digit numbers, such as "(11)", are not flagged. I tried adding the ten digits to the workspace dictionary to no avail...

**Comment by bartosz-antosik** [comment]
Could you pleases name OS you use it with (e.g. Windows 7 or Linux)?

**Comment by lbittarello** [comment]
Windows 10

**Comment by bartosz-antosik** [comment]
Should be corrected in yesterday released version 2.3.4.
