### ISSUE TITLE
Curly quotes throw off word boundaries

### ISSUE THREAD

**Issue by brehaut** [bartosz-antosik/vscode-spellright#154]
If I type a curly apostrophe (`’`)instead of a vertical quote (`'`), the spell checker will check the text on either side of the quote as if they were separate words rather than as one complete unit. For example:

This (vertical quotes) is correct:

```I've```

And (curly quote/apostrophe) this is incorrect:

```I’ve```

With `ve` being flagged as a misspelling.

**Comment by bartosz-antosik** [comment]
Can this curly apostrophe be used for possessive case (boy's)?

**Comment by brehaut** [comment]
Yes I believe so

**Comment by bartosz-antosik** [comment]
It has been added. It will be included in next release.

**Comment by brehaut** [comment]
Thanks!

**Comment by PeteX** [comment]
This doesn't seem to be working for me.  For example, I'm getting `isn’t` flagged as a spelling error, even though the spellchecker will accept `isn't`.

**Comment by PeteX** [comment]
Oh I see.  The spellchecker recognises `isn’t` as a single word, which can be added to the user dictionary.  IMO it should also recognise that `isn’t` is the same as `isn't` when checking the system dictionary. 

If English isn't your first language, I should explain that `isn’t` and `isn't` mean exactly the same thing.  Whether you use the straight quote or the curly quote is a matter of typesetting, not grammar.

**Comment by bartosz-antosik** [comment]
Could you please tell me the platform (OS)?

Various platforms use various spell checking back ends and it may be that some of them do accept this apostrophe and some don not. My spell checker does not interpret this just passes it to native speller.

**Comment by PeteX** [comment]
Oh sorry, the platform is Linux, Ubuntu 18.04.

**Comment by bartosz-antosik** [comment]
Thanks. I have tested it and it is hunspell background which does not understand curly apostrophes. I will meditate whether I can do anything about it or not.

**Comment by bartosz-antosik** [comment]
It should be resolved in just released version 2.5.16. Please give it a try.

**Comment by PeteX** [comment]
Perfect, thanks for fixing this so quickly!
