### ISSUE TITLE
Code actions (suggestions/lightbulb) no longer working

### ISSUE THREAD

**Issue by erikvullings** [bartosz-antosik/vscode-spellright#158]
I am using vscode v1.24.0-insider on Windows, and although the spell checker is still working and showing me errors, code actions (CTRL+.) are no longer working.
![image](https://user-images.githubusercontent.com/3140667/39966519-cfdadb6a-56b5-11e8-9dc9-6671e1d4de0e.png)

After pressing CTRL+.
![image](https://user-images.githubusercontent.com/3140667/39966518-c5a0f030-56b5-11e8-98d9-792a39ce0f7f.png)

I've uninstalled and installed spellright again, but that didn't work either.

**Comment by bartosz-antosik** [comment]
Hi! Yes, I can reproduce this, but it is strange as when I click on the diagnostics in lower panel the lightbulb does appear and code action is available. Cannot find any mention about this in WEB so I guess I will simply wait few days it may turn out to be an Insider's glitch.

**Comment by bartosz-antosik** [comment]
It turns out it is a small change in extension API. Probably it is not going to go so I have adapted the extension to work with it. It should be working in version 2.4.8.

**Comment by lesikv1** [comment]
need change in user setting
`"keyboard.dispatch": "code" `
on 
`"keyboard.dispatch": "keyCode"`

**Comment by bagustris** [comment]
I face this issue. VS Code version:

```

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z (2 wks ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.4.0-197-generic
```
