### ISSUE TITLE
Reporting line numbers and highlights desynchronized on the line continuation with `\`

### ISSUE THREAD

**Issue by luav** [bartosz-antosik/vscode-spellright#159]
Lines continuation with the ending `\` causes both desynchronization of the reporting line numbers in the `Problems` tab and highlights.
![spellringt_linesdesync](https://user-images.githubusercontent.com/6162969/39997279-a250b264-5782-11e8-98a7-740abfa6297f.png)

**Comment by bartosz-antosik** [comment]
The real reason is LF type of file. But thanks for reporting. Should be fixed in version 2.4.0.
