### ISSUE TITLE
command spellcheck-off not working in LaTeX documents

### ISSUE THREAD

**Issue by mweberUKL** [bartosz-antosik/vscode-spellright#161]
Spell Right version 2.4.8
OS: MacOS 10.13.4
VSCode version: 1.23.1

Turning spellchecking of using a in-document comment as shown in the screenshot does not work for me in the current version:

![image](https://user-images.githubusercontent.com/7224008/40069736-729252e0-586c-11e8-9d2a-96d79a5de76e.png)

**Comment by bartosz-antosik** [comment]
It was actually introduced few versions ago but sadly yes, there was a regression. Should be resolved in version 2.4.9. Thanks.
