### ISSUE TITLE
spellright finds all words wrong.

### ISSUE THREAD

**Issue by clsmt** [bartosz-antosik/vscode-spellright#162]
I am using win 7, VS Code 1.23.1 zip. updated spellright.

### How to reproduce:

1. Download VS Code 1.23.1 x64 zip. Install spellright through Extension store. Download English (American) .dff and .dic from the [recommended site](https://github.com/titoBouzout/Dictionaries), and place into `AppData\Roaming\Code\Dictionaries` subfolder.

2. Start a new file in VS Code. Start writing any correct word. Spellright will now list English (American) as a language to check. But Spellright marks all words wrong, untill you've written too many words, and Spellright stops marking after that.

**Comment by bartosz-antosik** [comment]
Could you tell me what is `VS Code 1.23.1 zip`? Is this regular edition from VSCodes site or some other like e.g. portable edition?

I do not have Windows 7 but I have checked this in Windows 10 running in a mode identical to Windows 7 (that is with hunspell background) and everything seems to be fine. So I really have no clue.

If you would download & install two dictionaries can you switch between them?
Could you maybe show me Spell Right's configuration?
A screenshot of the situation (there sometimes on can spot important things like e.g. line endings etc.)?

**Comment by clsmt** [comment]
Ah I mean the latest official version of VS Code 1.23.1, I downloaded the official x64 .zip instead of the installer. 

I tried English (American) and English (Britain). I can see both, and select either.

![image](https://user-images.githubusercontent.com/25810085/40217474-c7675aac-5a21-11e8-8403-ca3f7f5a13de.png)

**Comment by bartosz-antosik** [comment]
Could you please try the version with the installer?

I did not realize there is something like ZIP version...

**Comment by bartosz-antosik** [comment]
I have tested an unzipped version in windows 7. It works as it should. I cannot reproduce the error.

Need more clues.

**Comment by bartosz-antosik** [comment]
Oh, I forget to say: Spell Right uses native dependencies (binaries). In other words it runs a DLL library. It may be limited by many things like corporate policies, virus protection mechanisms etc.

**Comment by clsmt** [comment]
Hmm.. I will check on another machine later. 
Did you place the dictionary files in `AppData\Roaming\Code\Dictionaries`, or `AppData\Code\Dictionaries` as suggested in the manual? The latter path doesn't exist on my computer.

**Comment by bartosz-antosik** [comment]
The first one. The second one is not suggested in the manual. %APPDATA% resolves to: `C:\Users\{user}\AppData\Roaming`.

**Comment by bartosz-antosik** [comment]
Maybe open `Developer Tools` from Help menu to see if there is anything related to Spell Check?

**Comment by clsmt** [comment]
This is weird. I just reproduced this issue on another machine, with fresh VS Code, and just spellright installed.

No alerts or what so ever in the Devtools console. 

When you tested it on Win 7, were you testing it in a system that had VS Code installed before?

**Comment by clsmt** [comment]
I just installed SpellRight on my machine. Still the same...

**Comment by bartosz-antosik** [comment]
I have recreated the problem and find out what you did wrong!

See:

![image](https://user-images.githubusercontent.com/20492548/40269516-0f2bc85a-5b80-11e8-9b99-e472f8b3a0c4.png)

You have downloaded dictionaries and/or affixes file incorrectly. It is remarked in the README that you have to download RAW files. You have most probably right-clicked and downloaded them as "target" which downloads a GitHub web page instead of the file. Then both Dictionary and Affixes file malfunction.

**Comment by clsmt** [comment]
Damn! You are right. Now it works like a charm. Thanks!
