### ISSUE TITLE
Spellright omits files specified in the "files.associations"

### ISSUE THREAD

**Issue by luav** [bartosz-antosik/vscode-spellright#164]
I have an HTML template with the extension .tpl and would like to have there both a) *syntax highlighting* and b) *spellchecking*.

The spellchecking works fine for the file `test.tpl`:
```html
<h1>hesdfal</h1>
```
*until the syntax highlighting is enabled* by the following user settings:
```json
    "files.associations": {
        "*.tpl": "html"
    },
```

**Note:** addition / removal of `"html", "xml"` from `    "spellright.documentTypes": [...]` does not help also as specification of the parser type for the `"html"` in `"spellright.parserByClass"`.

**Comment by luav** [comment]
It seems all .html files are ignored... Should there be some specific configuration for HTML or why could it happen?

**Comment by bartosz-antosik** [comment]
Again, no idea. HTML class spelling is off by default, but once I choose e.g. English from the status bar button it spells it correctly. Also `*.httt` file once I add it to VSCode's `files.associations` setting:

![image](https://user-images.githubusercontent.com/20492548/40254551-2ecc4640-5ae4-11e8-9fc8-3de3272327fa.png)

**Comment by luav** [comment]
Thank you. The language could not be selected for `.tpl/.html` in my environment because I added `html` to ` "spellright.documentTypes"` in the User but not in the Workspace setting and the latter overwrites the former...

It was my mistake.
