### ISSUE TITLE
Start (^) and end ($) of the string markers are not supported in the spellright RegExps

### ISSUE THREAD

**Issue by luav** [bartosz-antosik/vscode-spellright#165]
I would like to skip the python commands in the HTML templates and use a regexp that unquoted looks like: `/^\s*%\s+.*$/` (any expressions that start with the `%` symbol).  
This regexp does not work in the `"spellright.ignoreRegExpsByClass"` until the start(`^`) and the end(`$`) of the string markers are removed (which, obviously changes the scope of the regexp).

**Comment by bartosz-antosik** [comment]
Could you please show some example of what you would like to eliminate?

**Comment by luav** [comment]
I would like to eliminate statements like:
```html
% if get('errmsg'):
<pre class="err">{{errmsg}}</pre>
% end
```

But the fundamental problem is that I can't much the whole line/string using standard RegExp notation, which is a bug  if the regexp is correct (I verified it in the https://regex101.com/ but might be some additional decoration is required for the Spellright).

**Comment by bartosz-antosik** [comment]
It seems to be working for me when looking like this (this "m" seems critical):

`"/^\\\\s*%\\\\s+.*$/gm"`

Am I wrong?

**Comment by luav** [comment]
You are right, thanks a lot, it works!
I haven't tried `gm` before because `g` means global, i.e. more than 1 match per line is possible and `m` means multi-line regexp, but here we have at most a single match per line.  
Anyway, it works!

PS It might be useful for others if you list somewhere on the documentation how the full string match regexp works in `ignoreRegExpsByClass` and `ignoreRegExps`, since it's not standard.

**Comment by bartosz-antosik** [comment]
If I understand things correctly it is other way round.  It is `^` and `$` which mean different things in normal matching and in multi-line matching.

But happy it served you.

**Comment by luav** [comment]
At least in `https://regex101.com/`, `vim`, `grep`, `sed` and all other cases when I used regexp the target expression is `/^\s*%\s+.*$/`. Anyway, thanks for the hint!

**Comment by bartosz-antosik** [comment]
Forgive me, it's not to `win` or anything, but look, here is your expression in https://regex101.com/ WITHOUT `m` (it does not select anything):

https://regex101.com/r/oGcClw/1

And here it is WITH `m`:

https://regex101.com/r/oGcClw/2

I understand it that `^` and `$` are meta symbols mean different thing when they are applied globally and when they applied in `m` mode. Then they match beginning/end of line which they do not mean in global mode alone (when they mean beginning/end of input pattern).

Anyway, there are dialects of regular expressions and I am far from being an expert. And I have not checked it with `grep`, `vim` and `sed` of course.

**Comment by luav** [comment]
You are right, sorry, I have not noticed the default `gm` in the regex101.
In grep it works as `grep -E '^\s*%\s+.*$' views/webui.tpl` but `-E` means extended regex, so the semantic might vary from the standard. `sed` accepts `^`, `$` fine but it's a stream editor.  
regex101 should really match the standard.

**Comment by bartosz-antosik** [comment]
I do not think this behavior in grep is due to extended regular expressions, but instead I think it is because grep parses file line-by-line so `^` & `$` are equivalents to line start & end. Never mind. Still happy it worked for you.
