### ISSUE TITLE
Spellchecker trys to correct corerrect abbreviation

### ISSUE THREAD

**Issue by LokiMidgard** [bartosz-antosik/vscode-spellright#166]
I have some abbreviations in my text.

e.g.: `inkl.` which means inklusive (German for inclusive).

The Spellchecker finds an error in the `inkl` part of the string (without the period). It suggests using `inkl.` and when this suggestion is accepted it adds an period resulting in `inkl..` and again finds the error `inkl` suggestion to add more periods.

I assume there is a problem submitting the words to the spellchecker, omitting the period. Worde does not show this error.

**Comment by LokiMidgard** [comment]
I have Windows 10 Pro (x64)
Version 1803

VS Code:  
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Datum 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

[Dokument where problem occurs](https://github.com/nota-game/nota/blob/bbd1094ee17f389788bf666ae175a777ec8f6045/input/books/Regelwerke/Grundregeln/Kampf/Kampf.md?utf8=%E2%9C%93) Line 31.

As a Workaround I have added rules to ignore like ` /inkl\\\\./g`.

Screenshoot:
![image](https://user-images.githubusercontent.com/389101/40278507-4acbe4be-5c32-11e8-872d-439575918b82.png)

**Comment by LokiMidgard** [comment]
The problem does not occurs when I add an additional word between the open parenthesis and `inkl.` e.g. `(auch inkl. Bewegung)`

**Comment by bartosz-antosik** [comment]
Oh, I understand, then it is most probably related to parenthetical plurals (#135) which when implemented have messed a lot... I will have a look, thank you for the feedback provided.

**Comment by bartosz-antosik** [comment]
Should be resolved in version 2.4.10
