### ISSUE TITLE
StatusBarItem

### ISSUE THREAD

**Issue by neilsustc** [bartosz-antosik/vscode-spellright#17]
![image](https://cloud.githubusercontent.com/assets/7588612/26275929/a34109a2-3d9e-11e7-96d0-6efa7fe2351c.png)

1. It seems that the config doesn't work
2. It would be better to remove the default white foreground as it overrides the theme color

**Comment by bartosz-antosik** [comment]
Could you please tell me what theme you use?

That would save me few seconds looking for one that changes Status Bar colors...

**Comment by neilsustc** [comment]
[This one](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme)

**Comment by bartosz-antosik** [comment]
Version 1.0.18 should resolve both problems.

**Comment by neilsustc** [comment]
Cool!

Last little question, could you please tell me the font name in your screenshots? It looks good.

**Comment by bartosz-antosik** [comment]
It's Consolas. It has drawbacks though (e.g. gradual sizing). Se more here:

https://www.slant.co/topics/67/viewpoints/11/~best-programming-fonts~consolas

**Comment by neilsustc** [comment]
👌
