### ISSUE TITLE
Markdown code blocks break subsequent spelling check again...

### ISSUE THREAD

**Issue by luav** [bartosz-antosik/vscode-spellright#170]
The spelling check works correctly only until the first code block (`sdf` is detected as miss-spelled) and afterwards the spelling is verified only in the subsequent code blocks instead of the surrounding text:
![spellright_markdown_codeblocks](https://user-images.githubusercontent.com/6162969/40567228-c93c999c-6074-11e8-91d9-5eab933b3bf3.png)

> Unlike #163, the ending punctuation sign does not matter here.

*Environment:*
Spellright v.2.5.0 with the `"spellright.parserByClass": { "markdown": "markdown"}`, Linux OS.

**Comment by bartosz-antosik** [comment]
Could you please investigate it a bit more, e.g. try to reduce the document to a paste-able example? I have troubles reproducing it or maybe I do not get something.

![image](https://user-images.githubusercontent.com/20492548/40578130-fbdc4fd8-610e-11e8-9d38-45bbb2bdcd96.png)

**Comment by luav** [comment]
You are right! The cause is in the URL ending the block,  which is inappropriately processed by the RegExp:
![spellright_markdown_codeblocks-url png](https://user-images.githubusercontent.com/6162969/40580006-c17b54a2-6135-11e8-9d47-838c1ab19a76.png)
And here is the unquoted `spellright.ignoreRegExps` regexp, which causes the issue: `/\\bhttp(s)?://[^,; )"']*/g`.

Note that:
- the regexp is NOT multi-line;
- after the codeblock URL, one more line with `}` is located before the codeblock closing, which seems somehow omitted together with the URL and first ` ` ` symbol of the closing block expression  <code>```</code>;
- everything works fine IF we put a **space** or one of the "closing symbols" ``` ^,; )"' ```

So, the *bug is in the regex stopping condition*:  
a) this regexp was unexpectedly processed as multi-line, which was not specified and might be caused by the difference of processing `\n` on Linux vs `\r\n` on Windows; and  
b) I do not understand why the ending space in the URL string makes everything works fine.

**Comment by bartosz-antosik** [comment]
Could you please show me the regexp quoted, exactly as you entered it into settings?

**Comment by luav** [comment]
Here is the exact simplified version that does not require multiple quoting and causes the same issue: `"/http(s)?://[^,; )\"']*/g"`.  
And the file, `tmp.md`:
```markdown
Spelling woks hereee
sdf:
```
turned off in the code block
````
!! As it found, still works heree but not after the following code block

```
@misc{pyexpool,
	url = {https://github.com/eXascaleInfolab/PyExPool}
}
```
Does not workkk here

```codeblock3
Unexpectedly workssss herewer 
```
dsdgj
```
Note that I'm working on Linux.

**Comment by bartosz-antosik** [comment]
I gave the thing short examination and there are two questions:

1. What is wrong with the expression being evaluated as multi-line?

It i actually quite normal. The expression matches everything BUT selected characters and line ending is matched as well. Sadly it also matches code block characters this is why it consumes the beginning of next code block: 

https://regex101.com/r/m1hxD4/1

I am unsure with a tendency NOT TO intervene here. Yes, it requires some prudence with regular expressions but it allows e.g. to eliminate blocks in LaTeX as well as other useful things. I do understand that debugging regular expressions in Spell Right is a bit of a hassle. But I see no way to help with it at the moment.

2. There already is URL removal functionality in Markdown parser so without your expression it actually DOES remove URLs, no need to do this!

You can have a look inside Markdown parser to see what it does but unlike your expression it does not match line endings, so it finishes before `}` character in the above example.

**Comment by luav** [comment]
> What is wrong with the expression being evaluated as multi-line?

It was my error caused by counter-intuitive regex interpretation. Usually, multi-line regex must be explicitly enabled by the *dedicated mode* and otherwise the regexp is evaluated until the line end.

> Why do you need to remove URLs when they are already removed?
> There already is URL removal functionality in Markdown parser ...

Because I would like to omit URIs spelling anywhere (code, comments, etc.) besides the markdown.

@bartosz-antosik, I'm sorry for the False alarm and thank you for the clarifications.
