### ISSUE TITLE
how to make spellright replace the mispelled word with the suggestion?

### ISSUE THREAD

**Issue by hcientist** [bartosz-antosik/vscode-spellright#175]
there doesn't seem to be a spellright command or context menu item?

**Comment by bartosz-antosik** [comment]
I am not sure if I understand correctly, but isn't it what appears after pressing `Ctrl+.` (on Windows, on other OSs please see README)?

It is not context or right click menu because this mechanism is independent from Spell Right, but provided entirely by VSCode.

**Comment by hcientist** [comment]
<kbd>ctrl</kbd>+<kbd>space</kbd> for me on mac. Like the same shortcut as general code completion? THough I shoudl have the caret at the end of the word...

**Comment by bartosz-antosik** [comment]
If I will remember I will try to add a snapshot of the diagnostics menu somewhere around this topic.
