### ISSUE TITLE
Strange wording split

### ISSUE THREAD

**Issue by neilsustc** [bartosz-antosik/vscode-spellright#176]
Type `algebra` in a HTML file

![image](https://user-images.githubusercontent.com/7588612/42630491-87ee0e20-8609-11e8-97a0-289fe11c3457.png)

**Comment by bartosz-antosik** [comment]
Hi! Could you please try to give bit more information, e.g. OS on which it runs? Various platforms have various spelling back-ends. Also, could you please try whether it is not interaction with other extensions? I cannot recreate this problem:

![image](https://user-images.githubusercontent.com/20492548/42633345-867c65e2-85e0-11e8-8615-e6cd59e721f2.png)

**Comment by neilsustc** [comment]
Thanks for the quick reply.

I am on Windows 10 1803 17134.165. VSCode 1.26.0-insider.

But I cannot reproduce on my laptop, which is the latest Windows insider build. I will investigate it and get back to you later.

**Comment by neilsustc** [comment]
OK, I find it. I have such a setting

```
"spellright.ignoreRegExpsByClass": {
    "html": [
        "/(href|br)/g"
    ]
},
```

**Comment by bartosz-antosik** [comment]
Ok, so do I understand correctly, that I do not have to do anything about it? ;-)

**Comment by neilsustc** [comment]
I mean I find the reproducing step, setting `/(href|br)/g` ignorance pattern.

Do you think the spell checking in the very first picture works as designed? It is weird to me since `algebra` is a correct word.

**Comment by bartosz-antosik** [comment]
Then I do not get this - if you set such a regexp then it will broke (probably all the words that contain "br" in them). But do you use such a regexp or you just created it to show the problem?

As I have shown in my picture, it spells correctly on Windows 10.

**Comment by neilsustc** [comment]
I use it. The full story is, at first, I have this (with no regexp)

![image](https://user-images.githubusercontent.com/7588612/42687992-332d1dc6-86cd-11e8-9fce-44c51f750ade.png)

And then I set `/(href|br)/g`, it becomes

![image](https://user-images.githubusercontent.com/7588612/42688059-67ab3290-86cd-11e8-8a58-d4cafa07daa1.png)

What do you suggest to deal with this situation? maybe using other regexp?

**Comment by bartosz-antosik** [comment]
It seems legit as SpellRight spells comments and everything apart tags.

The regexp should be bit more elaborate describing these as tags (with angle braces or the whole "a href" sequence etc.

**Comment by neilsustc** [comment]
Alright, thank you.
