### ISSUE TITLE
spellright ignores /*...*/ comment blocks in Go source files

### ISSUE THREAD

**Issue by pirivan** [bartosz-antosik/vscode-spellright#178]
Go source code supports the classic /*...*/ comment blocks as well as the common //... line comment. But when enabling spelling on a Go source file, spellright ignores the classic comment blocks; it shouldn't.

spellright 2.5.16, VSCode 1.25.0

**Comment by bartosz-antosik** [comment]
Could you please help me identify the problem? GO parser is exactly the same as CPP and few other similar syntax languages and it seemed to me that it works with both line `//...` and block `/*...*/` style comments:

![image](https://user-images.githubusercontent.com/20492548/42733321-d1dad6ee-882f-11e8-9d04-e25da41f1fc5.png)

Is there something I have missed?

**Comment by pirivan** [comment]
I can't give you a systematic way to reproduce this, but it just happened now while trying to provide you with more information:

![helloworld](https://user-images.githubusercontent.com/22241116/42739196-6e976c1a-8860-11e8-8709-92c23836a120.png)

Saving the file fixes the issue, which is a simple way to get around the problem. I will play with this a bit more to see if I can tell you how exactly this happens.

**Comment by bartosz-antosik** [comment]
Please, do! Spell Right uses differential information when editing of the document and tries spell as little as possible with each edit, not to add to CPU load etc. This is quite unique as far as I can tell but of course there may be a situation that I have not discovered so far which misses something from spelling. What's worse it may also be an interaction with some other extension, which you use. 

Saving of the document initiates whole document spell (it may also be disabled in configuration).

**Comment by pirivan** [comment]
Please feel free to close this ticket as I cannot provide you with a systematic way to reproduce the issue. I will reopen the ticket if I ever figure out how is it that I get into this problem.

Thank you for your support!
