### ISSUE TITLE
spellright.dict in portable version

### ISSUE THREAD

**Issue by barriteau** [bartosz-antosik/vscode-spellright#179]
Hi,

After migrating a VSCode installation to portable mode (https://code.visualstudio.com/docs/editor/portable), file `spellright.dict` is not readed nor created anymore. Tried deleting it to create a new one adding words but no success, it isn't created, trying again with the same word results in a notification saying: *the word "x" has already been added to user dictionary*.

Everything else is working as expected, correction and suggestions are working correctly. Any ideas?

Thanks!

**Comment by bartosz-antosik** [comment]
Hi! Thanks for reporting. Official portable version is something rather new. I have had adapted Spell Right to unofficial portable version some ago, but there may be differences. I will have a look.

**Comment by barriteau** [comment]
Thanks a lot!

**Comment by gandalfsaxe** [comment]
Same issue here. Since it effectively means that I can't make additions to the standard dictionary, I will be disabling it for now. Looking forward to a working build 😃

**Comment by barriteau** [comment]
Gandalf, meanwhile, if you are using Win8 (it seems this works at least for Win10 too) you can copy all words from `spellright.dict` to the `default.dic` file inside your system language directory (`%APPDATA%\Microsoft\Spelling`), then set `"spellright.addToSystemDictionary": true` in VSCode, this way you'll be able to use your word list and keep it up to date.

**Comment by bartosz-antosik** [comment]
@barriteau Very clever!

**Comment by bartosz-antosik** [comment]
Just published version 2.5.18 should have this sorted out. Please let me know if it works for you!

**Comment by barriteau** [comment]
Gandalf is the clever one, he knew you would solve this in seconds :)

**Comment by barriteau** [comment]
It's done, working perfectly. Again, thanks Bartosz.

**Comment by bartosz-antosik** [comment]
Thank you.

**Comment by gandalfsaxe** [comment]
Awesome! Tested on Windows, works 👍
