### ISSUE TITLE
One wrong regex will prevent other regexs to be applied

### ISSUE THREAD

**Issue by neilsustc** [bartosz-antosik/vscode-spellright#18]
I want to ignore two expressions,

- `\verb|something|` in LaTeX
- Chinese words, e.g. `中文词语`

I have tried many regexs but can't get them to work.

Finally, I tried `abc` and `/abc/g` to ignore `abc` and found they don't work too...

Could you please have a check whether the regexs are applied to ignore words?

![image](https://cloud.githubusercontent.com/assets/7588612/26547114/01cbda1c-44a0-11e7-909e-5962dc321616.png)

**Comment by bartosz-antosik** [comment]
These were set in Workspace or User configuration?

**Comment by neilsustc** [comment]
in user settings

**Comment by bartosz-antosik** [comment]
Hm. Seems to be working here (to say the truth I did this "abc" test). Are you sure you do not override User Settings with some Workspace settings?

**Comment by neilsustc** [comment]
Disable all other extensions and create a new folder (so that there is no Workspace setting)

`abc` is still not ignored 😞

![image](https://cloud.githubusercontent.com/assets/7588612/26565777/ed3d568a-4520-11e7-8f6d-bdbcd2c63aeb.png)

I found this error from the console
```
Cannot read property '_documentData' of undefined: TypeError: Cannot read property '_documentData' of undefined
    at C:\Users\zhang\.vscode-insiders\extensions\ban.spellright-1.0.18\src\spellright.js:130:35
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:45778)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code
...
```

---

My vscode info:

Version 1.13.0-insider
Commit 8c1c1d14df3c2f819078484aeffee37c3f00a7a8
Date 2017-05-29T05:13:44.347Z

**Comment by neilsustc** [comment]
I tried to find out the root cause (the above error message seems not to be relevant), but I can't build your project. This is the output after `npm install`

```
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! spellchecker@3.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spellchecker@3.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spellchecker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spellchecker
npm ERR! There is likely additional logging output above.
```

**Comment by neilsustc** [comment]
Finally I figured it out.

Use `/[\\u4e00-\\u9eff]+/g` (or `/[\\u4e00-\\u9eff，。；：‘“’”]+/g`) to ignore Chinese words

The only issue is that a wrong regex will stop other regexs to be applied.

Thanks for your great work!

**Comment by bartosz-antosik** [comment]
No, no - thank you for great work! And perseverance!

I will try to do something about it in next release.

BTW. Does the spell checker work with Chinese dictionaries at all? Can you spell something in Chinese using Spell Right?

**Comment by neilsustc** [comment]
IMO, Chinese spell check is a hard problem. It is not necessary if there are no other people requesting for it 😂.

(BTW, it seems that the statusbaritem is still visible when editing LaTeX (with statusbaritem disabled in user settings). Please have a check)

**Comment by bartosz-antosik** [comment]
Probably it is. Obviously to someone who do not speak Chinese, like me. :-) But I wonder - if MS Windows 10 does support spell check in Chinese (this page says it does: https://www.microsoft.com/en-us/download/details.aspx?id=52668) that would only be a matter of proper separation of words to spell. This is what I have tried hard to do properly for Latin based languages (considering important punctuation). Maybe it could be done for Chinese. Just asking.

I will have a look at the status bar indicator.

**Comment by neilsustc** [comment]
> a matter of proper separation of words to spell

That's the hard problem because there is no space between Chinese 'words'.

---

I'm wondering whether the workspace setting should have all the config fields.
My workspace setting was auto created when I ignored some words. At that time, I enabled the statusbaritem. So this config was copied into the workspace setting but I didn't know...

We can **only** add the required field (e.g. ignoredWords) into the workspace setting. And for other fields, fall back to user setting.

**Comment by bartosz-antosik** [comment]
Oh, I was just finishing my investigation... (see below).

-------------------------

About the status bar Indicator - I have done some quick checks and looked at the code and it seems that if only `spellright.statusBarIndicator` is properly initialized (bearing in mind User/Workspace inheritance) it should be displayed/hidden properly. There are few hints however: Spell Right watches for changes in Workspace configuration but does not watch User configuration. It means it has to be restarted to consider it.

**Comment by bartosz-antosik** [comment]
About Chinese words separation - is it that there is no space or is it that it is not noted in writing?

It's like with Roman numerals which HAD zero, just they did not write it down which made it hard to make progress in algebra until Arab invented (well copied from Hindu) zero...

So you say there are no generalized rules to separate parts to spell?

**Comment by bartosz-antosik** [comment]
I will think about the settings shadowing or limiting thereof - maybe something could be done here.

Do you have in mind an extension which does this properly?

**Comment by neilsustc** [comment]
Yes, I didn't notice that the auto generated workspace setting would have a copy of `statusBarIndicator` field from user setting. So I recommend to only add `ignoredWords` field when auto generating workspace setting (to prevent unexpected workspace setting).

---

Yes, no general rules to separate.

> Chinese is standardly written without spaces between words (as are some other languages). This software will split Chinese text into a sequence of words, defined according to some word segmentation standard. It is a Java implementation of the CRF-based Chinese Word Segmenter described in
>
> -- [Stanford Word Segmenter](https://nlp.stanford.edu/software/segmenter.html)

Chinese word segment is a research topic in NLP...

**Comment by bartosz-antosik** [comment]
Yes, I have noticed that all the settings are updated. Unnecessary can be removed manually. It could be possible to do something about this. Let me think about it.

Thanks for the clarification about Chinese language. That's tough. I wonder how good does MS Word etc. do this...

**Comment by neilsustc** [comment]
As you read user setting and workspace setting into a single global variable `settings`, you might need another global variable `wsSettings` to store the workspace settings. Then you can only write `wsSettings` to workspace config file 😉.

**Comment by bartosz-antosik** [comment]
Thaks! This I can probably figure out. :-) I was thinking rather of saving only difference between User/Workspace settings as a bit more clever resolution.

**Comment by neilsustc** [comment]
Crazy perfectionist 😄

**Comment by bartosz-antosik** [comment]
It's an honor! Thank you!

**Comment by bartosz-antosik** [comment]
Version 1.0.19 will display an error message on every RegExp that thrown an error. Should resolve the general problem. Thanks for help.

**Comment by acharkq** [comment]
That helps a lot
