### ISSUE TITLE
Is there a way to sync dictionaries across devices / platforms?

### ISSUE THREAD

**Issue by GandalfSaxe** [bartosz-antosik/vscode-spellright#180]
Ideally I'll soon be using [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) extension for syncing my user preferences, extensions, keycaps etc. across devices and platforms. In practice, I'm waiting for them to support the portable version.

What about Spell Right? Is there a way of easily syncing dictionary across platforms?

**Comment by bartosz-antosik** [comment]
Sadly - No! It would be useful to have such a mechanism, but I think it is way beyond scope of the extension. 

I was pretty sure, until today, that [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) does this!

**Comment by GandalfSaxe** [comment]
Fair enough. I actually haven't been able to use that extension yet since it just work with portable version (yet), so you may be right.
