### ISSUE TITLE
a mispelling of ".abc" suggests adding ".abc" to the dictionary rather than "abc"

### ISSUE THREAD

**Issue by Alexendoo** [bartosz-antosik/vscode-spellright#181]
To reproduce create a text file with ".abc" in it, the context menu to add to user/workspace dictionary will add ".abc" and mark the spelling as valid. However when next opening the file it will still show up as an error.

Suggesting & adding "abc" checks the spelling correctly on re-open

**Comment by bartosz-antosik** [comment]
Thank you! Should be corrected in 2.5.20.
