### ISSUE TITLE
Change squiggly line form red?

### ISSUE THREAD

**Issue by GandalfSaxe** [bartosz-antosik/vscode-spellright#183]
How about changing the color marker from red to something less "errorly" and more "warningly"?

At a glance it's hard to see if something is a serious error from e.g. pylint such as an undefined variable that will crash the program, or just a spelling error / suggestion.

**Comment by bartosz-antosik** [comment]
The only thing about this that can be done (because it is beyond what VSCode's extension can do) is `spellright.notificationClass` setting. Please have a look at the README.md to see whether this is what you need!

**Comment by GandalfSaxe** [comment]
Ah perfect. Sorry, I overlooked that option 👍

**Comment by GandalfSaxe** [comment]
(`information` should probably be the default)

**Comment by bartosz-antosik** [comment]
That's very subjective! ;-)

**Comment by bartosz-antosik** [comment]
Kinda blackmail, isn't it? ;-) Spell Right was designed for classes of documents, it had parser for code from the very beginning.  But you have a point. There is a hierarchy and it is different for documents than source code.

I will deliberate on this and see whether it it possible to add a context setting (e.g. information for code and error for documents).

**Comment by tecosaur** [comment]
***bump**

I'm working with a mix of documents / languages and this would be a **huge** QOL improvement.

_Huge._

**Comment by bartosz-antosik** [comment]
In just published version 2.5.24 there is a new setting `spellright.notificationClassByParser` to do what you need. Please tell me whether it works as desired.

**Comment by GandalfSaxe** [comment]
Great 👍 As far as I can tell it works right. I'll let you know if I find it doesn't.

**Comment by AHillsie** [comment]
:1st_place_medal: Thanks. Really needed this and works great!
