### ISSUE TITLE
Settings names should be wrapped in quotes

### ISSUE THREAD

**Issue by fontaines** [bartosz-antosik/vscode-spellright#185]
Hello,

In your README, you explain settings exposed by your extension. (Your documentation was a pleasure to read, by the way. I wish all documentations were like yours!) However, I couldn't get any of your settings snippets to work. For example, this one:

`spellright.statusBarIndicator: false`

It turns out that (on my Mac computer, at least) settings names must imperatively be surrounded by double quotes:

`"spellright.statusBarIndicator": false`

**Comment by bartosz-antosik** [comment]
Great idea! I think will do this on next release.

Thank you for kind words about documentation and I am very happy someone actually read it! ;-)

**Comment by bartosz-antosik** [comment]
Should be done in version 2.5.24. Please let me know if I have missed something.

**Comment by fontaines** [comment]
Fantastic! Thank you for your responsiveness and thank you for the hours you spend maintaining and supporting this extension.
