### ISSUE TITLE
error count > 1K

### ISSUE THREAD

**Issue by bkircher** [bartosz-antosik/vscode-spellright#186]
It seems that spell checking a document ends when 1000 errors are found. Is there a way to increase that number or better check an entire document even if very large?

**Comment by bartosz-antosik** [comment]
This limit is imposed by VSCode. Extension produces so called diagnostics and after crossing some number (not long ago it was 250) VSCode does not allow to add any more. Sadly I can do nothing about it and I am not quite sure whether anything can be done about it apart from creating custom version of VSCode.

**Comment by bkircher** [comment]
Can you point me to an API call or to an VS Code issue?
