### ISSUE TITLE
Support of AsciiDoc?

### ISSUE THREAD

**Issue by jgoldhammer** [bartosz-antosik/vscode-spellright#188]
Thanks for your project!
It is planned to support AsciiDoc?
http://asciidoc.org

**Comment by jgoldhammer** [comment]
Thanks for the quick answer.
I just tried it again with a file extension adoc. The first time it does not work- no spelling problems were shown. After selecting the English dictionary, it works now and there are several entries in the problems view.

Nevertheless spell right also shows suggestions for built-in commands of Asciidoc like here:
<img width="180" alt="image" src="https://user-images.githubusercontent.com/3872101/43366689-3349b6b2-9342-11e8-99fa-9d7bbc734651.png">

<img width="781" alt="image" src="https://user-images.githubusercontent.com/3872101/43366712-7f9c121c-9342-11e8-82ec-124425ffedca.png">

**Comment by bartosz-antosik** [comment]
Spell Right is OFF by default for most document types and ON for markdowx/planitext/latex only. Once you turn it ON (by selecting language) it will (in default configuration) remember that it is ON for this document type. So this is "by design".

Regarding asciidoc commands: I have very little idea about asciidoc - could you please provide some example (paste-able) of what parts of asciidoc document should not be spelled?

**Comment by jgoldhammer** [comment]
Hi,
ok, I understand now.

There are several examples out there- I think every command beginning with colon should not be parsed:

```
:toc: left
:toclevels: 4
:xrefstyle: full
```

Besides that there are options for commands which should not be parsed...
```
[cols=",,",options="header",]
```

We have images which can be embedded:

```
image:images/db_scheme.png[image,width=642,height=593]
```
The complete line should not be spell checked...

Asciidoc is very complex
For more info, see

https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
https://asciidoctor.org/docs/user-manual/#builtin-attributes

**Comment by bartosz-antosik** [comment]
I have added elementary support for AsciiDoc (attributes, but no all of them e.g. :toc: is removed form spelling but :summary: is not and options - single line with something enclosed in square brackets - in version 2.5.24. Please have a look and if you would find any annoyances please let me know.
