### ISSUE TITLE
Add support reStructuredText

### ISSUE THREAD

**Issue by AlexMAS** [bartosz-antosik/vscode-spellright#19]
Hello!

Firstly, thank you for your work.

In our projects we use readthedocs.org and as consequence reStructuredText (*.rst files). I tried to configure Spell Right using spellright.json as described below but it didn't give a result.

```json
{
    "language": "en",
    "documentTypes": [
        "restructuredtext",
        "markdown",
        "latex",
        "plaintext"
    ],
    "groupDictionaries": true,
    "statusBarIndicator": true,
    "suggestionsInHints": true,
    "ignoreWords": [],
    "ignoreRegExps": [],
    "ignoreFiles": [
        "**/.gitignore",
        "**/.spellignore"
    ]
}
```

**Comment by bartosz-antosik** [comment]
Support is added in version 1.0.21.

**Comment by bartosz-antosik** [comment]
I have very limited knowledge of reStructuredText. If there are any structures that should be excluded from spelling let us know. They can be either removed using User/Workspace configuration or internally by parsers.
