### ISSUE TITLE
Bug in LaTeX diacritic spell check

### ISSUE THREAD

**Issue by philipstarkey** [bartosz-antosik/vscode-spellright#192]
In #133 you introduced proper detection of LaTeX diacritics (again many thanks for adding that feature!). I've just discovered that when I type n\\'{e}e (for née) that it thinks the word has been spelt nèe (a grave accent instead of an acute accent). I assume they're just switched around somewhere in the source code for this extension?

**Comment by bartosz-antosik** [comment]
Should be fixed in 2.5.28.
