### ISSUE TITLE
No language available on Windows10

### ISSUE THREAD

**Issue by HB25** [bartosz-antosik/vscode-spellright#194]
After installing, Spell Right does not show any language but only "Turn Off". 
OS is Windows 10 with English US and German installed, VS Code version info below.

Setting   global.SPELLRIGHT_DEBUG_OUTPUT = true;   does not output anything in the debug console so I don't know what else to provide to analyze.

Visual Studio Code
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

**Comment by bartosz-antosik** [comment]
Sadly, I have had a similar situation in the past, but I have not found any resolution. Please have a look at [#106](https://github.com/bartosz-antosik/vscode-spellright/issues/106) and [#53](https://github.com/bartosz-antosik/vscode-spellright/issues/53). It is even noticed in README (see Known Issues).

Sorry about this but it seems outside of the extension.

Could you try whether it works on some other machine?

The only advice which works I had is that it is possible to use Hunspell Backend with dictionaries downloaded like in Windows 7 where there is no built in spelling API.

**Comment by HB25** [comment]
Okay, I saw #53 but not #106.  Last one helped me to get the console output but that does not help I guess (it's below).

I have not found any additional information about policy settings or registry entries which could help. I try another machine later. My PC is quite new.

As soon as I copy the hunspell files to the Dictionaries directory I can select that language.

--
log.ts:159  INFO no standard startup: not the explorer viewlet
console.ts:136 [Extension Host] [spellright] Bindings: "spellchecker-win32-1.7.7-x64.node".
console.ts:136 [Extension Host] [spellright] Activated (win32, x64).
console.ts:136 [Extension Host] [spellright] Dictionaries path: "C:\Users\xxxxx\AppData\Roaming\Code\Dictionaries"
console.ts:136 [Extension Host] [spellright] System locale: "de_DE", set locale: "".
console.ts:136 [Extension Host] activating extension
console.ts:136 [Extension Host] starting language server

**Comment by bartosz-antosik** [comment]
Do I understand correctly the you CAN use the extension with hunspell dictionaries?

This requires setting an environment variable (SPELLCHECKER_PREFER_HUNSPELL=1) - have you done this?

**Comment by bartosz-antosik** [comment]
That is strange. It means the back-end has decided it cannot detect speller and switched. I will investigate it further but I am happy it works for you this way.

**Comment by HB25** [comment]
I could only select the language. Spellchecking did not work until I added the SPELLCHECKER_PREFER_HUNSPELL=1.

Before this, I saw only the same effect that kubics commented in #106 on Jan 8: "Adding dictionary.." and other messages on every keypress. No idea if that means something.

**Comment by bartosz-antosik** [comment]
I will close this thread for now. Hope one day it happens on my machine so that I can debug the problem properly.
