### ISSUE TITLE
Suggestion: Ignore occurrence  

### ISSUE THREAD

**Issue by MrZeusTheCoder** [bartosz-antosik/vscode-spellright#197]
I thought it might be a good idea, because you have the "add to user dictionary", and the  "add to workspace dictionary", but at times it may be better to just ignore that occurrence of the the mistake. Just a thought.

**Comment by pke** [comment]
It would be nice to be able to provide an "in document" dictionary (similar to In-Document Commands) to ignore certain words (in technical docs) without having to add them to the workspace or user dictionary.

An example could be for md files YAML frontmatter

```markdown
---
# spellcheck-ignore: Posteo, Runbox
---

[...]
Using "E-Mail Address Extensions" supported by [GMail](https://www.lifewire.com/easy-gmail-address-hacks-1616186/), Posteo, Mailbox.org, Yahoo, FastMail, Runbox, outlook.com and others users could use specially annotated emails [...]
```

Posteo and Runbox would not be considered wrong spelled anymore.

**Comment by MrZeusTheCoder** [comment]
Isn't this fixed with the new(-ish?) "Ignore Word" feature? It is mentioned on the [marketplace page](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)(scroll down to "In Document Settings" or ctrl+f to the third match of "ignore") I can't find a commit to provide proof, but the feature is working in my VS Code install. :P

**Comment by bartosz-antosik** [comment]
Hi @MrZeusTheCoder! I think you link/mention the "other" spell checker. I have similar feature on my mind just do not have a lot of time to develop SpellRight recently.

**Comment by pke** [comment]
Yeah that's the source code spellchecker ;)

**Comment by pke** [comment]
@bartosz-antosik Am I correct that I would have to add the new command inside this block?
https://github.com/bartosz-antosik/vscode-spellright/blob/master/src/spellright.js#L1170

I would simply create an "on the fly" dictionary for the parsed document that has higher priority than workspace and user dictionaries.

Sounds reasonable? Then I would start implementing that. 
I just wonder how one debugs a vscode extension. Any pointers to that?

**Comment by MrZeusTheCoder** [comment]
Whoops. Sorry about that, @bartosz-antosik.
