### ISSUE TITLE
Request: Elixir Support

### ISSUE THREAD

**Issue by cmuhire** [bartosz-antosik/vscode-spellright#198]
Hi!

Thanks so much for building Spell Right, it's really great! It would be even greater with support for [Elixir](https://elixir-lang.org/) documentation syntax :smile: 

Elixir provides a number of ways to document code:

## Comments

Any line starting with a hash symbol `#`

```elixir
# Applies my_function/1 over my_list
Enum.map(my_list, &my_function/1)
```

## @doc annotations

These are Markdown-formatted _heredocs_ used to document a handful of language constructs:

  * `@moduledoc`: [documents a module](https://elixirschool.com/en/lessons/basics/documentation/#documenting-modules)
  * `@doc`: [documents a function](https://elixirschool.com/en/lessons/basics/documentation/#documenting-functions)
  * `@typedoc`: [documents a custom type specification](https://elixirschool.com/en/lessons/advanced/typespec/#documentation-of-types)

```elixir
defmodule CartesianPlane do
  @moduledoc """
  Utility functions for a Cartesian coordinate system
  """

  @typedoc """
  Type that represents a 2-D point
  """
  @type point :: {integer, integer}

  @doc """
  Computes the `Euclidian` distance between two points on the plane.

  ## Examples

      iex> CartesianPlane.euclidian_distance({0, 0}, {3, 4})
      5.0
  """
  @spec euclidian_distance(point, point) :: float
  def euclidian_distance(a, b) do
    [a, b]
    |> Enum.map(&Tuple.to_list/1)
    |> Enum.zip
    |> Enum.map(fn ({a, b}) -> :math.pow((a - b), 2) end)
    |> Enum.sum
    |> :math.sqrt
  end
end
```

The following VS Code extesions may come in handy:

  * [vscode-elixir](https://github.com/fr1zle/vscode-elixir): adds language support.
  * [vscode-elixir-ls](https://github.com/JakeBecker/vscode-elixir-ls): additionally implements the [Language Server Protocol](https://github.com/Microsoft/language-server-protocol). This is the more feature-rich and frequently updated of the two.

Bonus points for skipping [doctests](https://elixir-lang.org/getting-started/mix-otp/docs-tests-and-with.html#doctests) (line that starts with `iex>` or `...>` for multi-line commands and its output line that comes right after). These are documentation code examples meant to be evaluated by the test runner.

Thank you!

**Comment by bartosz-antosik** [comment]
I have added support for elixir in just published version 2.5.32. Please have a look. Lines with `doctest` prompt are removed from spelling. Removing the line with expected response is very problematic at the moment. If something is not OK carry on in this thread.

**Comment by cmuhire** [comment]
@bartosz-antosik thank you for delivering so promptly!

I've just tested all the above and it works as expected :tada: 

Don't worry about the output line, it's a negligible concern at this stage and a tricky one to implement.

Dziękuję Ci bardzo!

**Comment by bartosz-antosik** [comment]
Proszę!

https://www.youtube.com/watch?v=Wf_KCVA9JXE&t=1m47s
