### ISSUE TITLE
Avoid mutating globals

### ISSUE THREAD

**Issue by Alexendoo** [bartosz-antosik/vscode-spellright#199]
Some general additions to global that could be replaced with exports:

https://github.com/bartosz-antosik/vscode-spellright/blob/601d3555144565121f6c73dfacaecde016076b48/src/extension.js#L8-L12

https://github.com/bartosz-antosik/vscode-spellright/blob/601d3555144565121f6c73dfacaecde016076b48/lib/parser.js#L10-L43

Mutating prototypes is much more troublesome than those however, since it can cause bugs to surface in other libraries (e.g. https://github.com/ymotongpoo/vsc-licenser/issues/37), as well as the same problems as the whole mootools saga

https://github.com/bartosz-antosik/vscode-spellright/blob/601d3555144565121f6c73dfacaecde016076b48/lib/parser.js#L45-L60

**Comment by Alexendoo** [comment]
I certainly agree with the convenience point, it would be great if there a way to have extension functions in js without any of the problems.

Adding things to `global` isn't as much of an issue, it would only be a problem if somebody else tried to also use e.g. `global.COMMAND` in their extension.

You can export/import values in the same way you do functions, export from one module and `require()` that module in others when you want to use them.

**Comment by bartosz-antosik** [comment]
Removed in recently published version 2.5.32. Thanks.
