### ISSUE TITLE
LaTeX commands false positives 

### ISSUE THREAD

**Issue by GandalfSaxe** [bartosz-antosik/vscode-spellright#203]
I use Spell Right with LaTeX documents sometimes, and it picks up a lot of false positive from latex commands. Is there currently a good solution to this?

**Comment by bartosz-antosik** [comment]
Could you show me please these commands?

**Comment by GandalfSaxe** [comment]
I'm using this template which is very popular for students in my university department: https://bitbucket.org/_laursen/laursens-xelatex-thesis-template

Then I have to add these words to a dictionary:

```
Adventor
Chapterstyle
Hunspell
Hypersetup
Laursen's
Prefrontmatter
Texmaker
bookmarksnumbered
bookmarksopen
breaklinks
captiontitlefinal
chapternamenum
citebordercolor
colorlinks
deletekeywords
dist
dtu
dtugray
dtured
dtx
escapeinside
filebordercolor
hidelinks
jobname
keywordstyle
leftmark
linkbordercolor
linktoc
morekeywords
mychapterstyle
myruled
numbersep
numberstyle
opentype
pdfbookmark
pdfdisplaydoctitle
pdfsubject
pdftitle
plainpages
rulecolor
showspaces
showstringspaces
showtabs
stepnumber
stringstyle
tabsize
texlive
texmf
todonotes
urlbordercolor
```

Come to think if it, they actually all look like user defined commands, in which case there's probably no better solution than adding these in a dictionary manually? I'm curious, what is actually being done to prevent false positives on standard LaTeX commands, which I now realize are actually not detected?

**Comment by bartosz-antosik** [comment]
Could you please be bit more specific? The template contains dozens of documents and forces me to download, search and pinpoint what and where `Adventor` or `stringstyle` is. Can I count for a snippet showing few of those problems or maybe bit more precise locations?

**Comment by bartosz-antosik** [comment]
I am still counting upon receiving some more detailed examples for the above - am I right?

**Comment by GandalfSaxe** [comment]
Yes I will post them at some point, just got very busy with finishing my MSc thesis but it’s firmly in my task manager! :)

**Comment by bartosz-antosik** [comment]
Shall you have some more info on this please let me know in this thread.
