### ISSUE TITLE
Workspace dictionary doesn't work?

### ISSUE THREAD

**Issue by EnCey** [bartosz-antosik/vscode-spellright#204]
I can't get workspace dictionaries to work 🙁

When I use the command "Add Selection to Workspace Dictionary", this error is reported:

`Running the contributed command:'spellright.addFromSelectionToWorkspaceDictionary' failed.` 

Things I tried that didn't help:
* I created a `.vscode` folder
* I put a `customWords.dict` file in that folder
* I put a `spellright.dict` file in that folder

I also tried the "Open Workspace Dictionary File" command, which responds with: 

`SpellRight: Workspace dictionary file does not exist. It will be created when first word is added.`

**Comment by EnCey** [comment]
Strange, now it suddenly works. I have a suspicion what might have happened:

I had an empty `.code-workspace` file (to which I haven't yet added any files or folders).  
In the same directory was the `.vscode` folder with the `spellright.dict` in it.

After I added the current folder to the workspace (which includes the `.vscode` folder), the SpellRight commands started to work – or at least I think that was it.

Is that working as expected or should the `.vscode` folder be recognized regardless of a `.code-workspace` file?

**Comment by bartosz-antosik** [comment]
I am sorry, I have done an attempt to recreate the situation but I failed. Could you maybe please write step-by-step guide how to recreate the situation?

**Comment by bartosz-antosik** [comment]
Hi, I have analyzed this a bit further and it seems it worked as designed. Folder will not be recognized until it is a part of multiroot workspace.
