### ISSUE TITLE
Profiler shows a lot of CPU time spent in Spell Right

### ISSUE THREAD

**Issue by borekb** [bartosz-antosik/vscode-spellright#208]
Hi, I'm trying extension profiler for the first time for unrelated reasons but when I turned on recording after a start of my VSCode, this was the result after about 20 seconds (can't remember exactly):

![image](https://user-images.githubusercontent.com/101152/45623087-6eacc300-ba86-11e8-95cb-1153a0d2a6b0.png)

I only had a single Markdown file open at that time so this seems excessive. If you'd be interested in more performance reports, I'll be happy to gather them.

- Extension Name: spellright
- Extension Version: 2.5.32
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.27.2

**Comment by bartosz-antosik** [comment]
1. Could you point me to some documentation/information on how to use profiler?
2. Could you share the document or choose some common document so that we can compare results etc.?

**Comment by borekb** [comment]
I'm very new to this myself, was advised here: https://github.com/Microsoft/vscode/issues/57697#issuecomment-421915959

I'll try to reproduce it on a public repo we have; this one is private. My suspicion is that the problem is that it's a monorepo with many Markdown files and VSCode might be opening these files in the background even though it shouldn't (https://github.com/Microsoft/vscode/issues/50874). Need to play with it more.

**Comment by bartosz-antosik** [comment]
Hi! Do you have any new development around this issue?

**Comment by borekb** [comment]
Yes, it's reproducible on our [public repo](https://github.com/versionpress/versionpress): just clone it locally and start VSCode on it.

![image](https://user-images.githubusercontent.com/101152/46028332-86bcbc00-c0f0-11e8-9e33-a032cde61ab1.png)

**Comment by borekb** [comment]
(and sorry for the delay)

**Comment by bartosz-antosik** [comment]
Sorry, I cannot reproduce this. I have opened VSCode on the folder, displayed profiler - nothing really happens... Could you maybe tell which document(s) open to spell from this repository?

**Comment by bartosz-antosik** [comment]
I have randomly clicked few files here and there but it results in something like this:

![image](https://user-images.githubusercontent.com/20492548/46029442-b91be880-c0f3-11e8-9907-e001cbeec2e5.png)

**Comment by borekb** [comment]
Strange, I'm on a PC now (the previous screenshot was a Mac) and I can't reproduce either. This is my user settings BTW:

```
    "spellright.language": "en",
    "spellright.addToSystemDictionary": true,
    "spellright.notificationClass": "information",
    "spellright.documentTypes": [
        "markdown"
    ],
    "spellright.spellContext": "body comments strings",
    "spellright.spellContextByClass": {
        "markdown": "body",
        "typescript": "comments",
        "json": "comments",
        "html": "body",
        "typescriptreact": "body comments strings",
    },
```

Do you also get a _lot_ of spelling issues in the Problems panel?

![image](https://user-images.githubusercontent.com/101152/46041171-79b0c480-c112-11e8-8bf0-9a4d6d724b0c.png)

Note that I don't have any files open, only the Running Extensions tab. Maybe my other Markdown extensions are triggering processing MD files which includes spell checking? Again, that might be because of https://github.com/Microsoft/vscode/issues/50874.

**Comment by borekb** [comment]
It seems that it's related to the MarkDown Link Suggestions extension, with a recent comment here: https://github.com/Microsoft/vscode/issues/50874#issuecomment-424496388

I think we're on a tangent now, maybe my initial issues were related to that. Sorry for a confusing issue, I feel it will be best to close it and if I ever spot anything suspicious regarding performance, I'll create a new one. Thanks for your cooperation!

**Comment by bartosz-antosik** [comment]
Absolutely, shall you have any new development let me know.

Maybe you could switch the problematic extension off for a test and see if it changes anything?

**Comment by borekb** [comment]
I did. On my PC (unlike on Mac), with both the problematic extension enabled and disabled, I could not reproduce the original report – Spell Right was never consuming too much CPU time. Strange things happen :)
