### ISSUE TITLE
Citation in Rmd are not considered as code string

### ISSUE THREAD

**Issue by chasset** [bartosz-antosik/vscode-spellright#209]
Hello,

I write texts using Rmd (Markdown for R) files in vscode. Usually, in a paragraph, I cite my sources using an inline bit of code such as *@Minnameier:2010uc*.

The problem is that the checker indicates that this code is wrong spelled.

Could you add a pattern in order to ignore to spell citations code?

Thank you very much for your very useful extension.

Best regards,

Pierre-Olivier

**Comment by chasset** [comment]
Please find an example of a paragraph mixing text and one citation.

> The theory discussed by @Minnameier:2010uc is very interesting because…

The compilation process will transform this code like this:

> The theory discussed by Gerhard Minnameier [1] is very interesting because…
>
> 1. « The logicality of abduction, deduction, and induction », dans Ideas in action, 2010.

**Comment by bartosz-antosik** [comment]
One last question: Which extension registers `rmd` document type?

**Comment by chasset** [comment]
I don't understand your question

**Comment by bartosz-antosik** [comment]
I suppose that to work with R Markdown you deploy some extension for VSCode. Which one?

**Comment by chasset** [comment]
Not at all. I just use the [vscode-R](https://github.com/Ikuyadeu/vscode-R) extension in order to highlight my [R](https://www.r-project.org) code. To transform Rmd files in PDF, I follow the [bookdown](https://bookdown.org/yihui/bookdown/) format, which is also a library of R, and I launch a small bash script to compile:
```
R -e 'rmarkdown::render_site(encoding = "UTF-8")'
```
So, the spell check task happen just before compiling.

**Comment by chasset** [comment]
A Rmd file is just a text file formatted using the markdown version of [pandoc](http://pandoc.org/MANUAL.html#pandocs-markdown).

**Comment by bartosz-antosik** [comment]
You can stop Spell Right from spelling references in the documents by setting:

```
"spellright.ignoreRegExpsByClass": {
    "rmd": [ "/@\\S+/g" ]
}
```

in either User or Workspace settings. Here is your example without this setting:

![image](https://user-images.githubusercontent.com/20492548/45756259-bcf5c980-bc20-11e8-9d9a-2ed9c56e484c.png)

And here is with:

![image](https://user-images.githubusercontent.com/20492548/45756227-aa7b9000-bc20-11e8-87af-68debed83228.png)

Beware that it will prevent anything like `@something` from spelling!

**Comment by chasset** [comment]
Excellent. I will certainly expand it

**Comment by chasset** [comment]
Many thanks

**Comment by bartosz-antosik** [comment]
You are welcome. 

What I meant earlier is that bare VSCode does not "understand" what `.rmd` is and there is an extension which does this. I have tried to locate it and got confused because there is more than one. You pointed this out in your first line. The rest I knew. Cheers!

**Comment by chasset** [comment]
Alright ;o)
