### ISSUE TITLE
Not able to switch from English to Dutch and visa versa in separate documents.

### ISSUE THREAD

**Issue by Esther85** [bartosz-antosik/vscode-spellright#21]
Previous I could set the spelling check  into English or Dutch, unfortunately  it is currently not possible to switch.

I hope this can be resolved.

Thank you in advance.

**Comment by bartosz-antosik** [comment]
Should be fine in version 1.0.22 available in few moments.

**Comment by Esther85** [comment]
Thank you very much this bug is resolved.
