### ISSUE TITLE
Dictionary directory is hardcoded

### ISSUE THREAD

**Issue by yannakopoulos** [bartosz-antosik/vscode-spellright#211]
If you build Code from source rather than using Microsoft's binaries (for example, by installing from the Arch User Repository), the application is by default called "Code - OSS" and user configuration files live in `~/.config/Code - OSS/` on Linux. However, it looks like Spell Right only ever looks in `~/.config/Code/` for dictionaries. It works fine if you symlink `~/.config/Code/` to `~/.config/Code - OSS/`, but it would be better if Spell Right checked the correct config folder to begin with.

**Comment by bartosz-antosik** [comment]
Do you know an VSCode's API call that would tell you this directory's name?

Because I do not hence even `Insiders` poses a problem and the name is produced manually...

**Comment by yannakopoulos** [comment]
I don't think there is one yet, although it's been requested here: https://github.com/Microsoft/vscode/issues/2741

Maybe a solution like this? https://github.com/alefragnani/vscode-project-manager/issues/178

**Comment by bartosz-antosik** [comment]
Many thanks for pointing these out. It will be changed in next release.

**Comment by yannakopoulos** [comment]
Yes, that version works fine. Thanks!
