### ISSUE TITLE
Latex commands in markdown produce false positives

### ISSUE THREAD

**Issue by danmackinlay** [bartosz-antosik/vscode-spellright#212]
If I have markdown with mathematical markup in it (i.e. between `$` markers) I get lots of false positives for math markup such as `\cos`, `\mathcal` and other LaTeX math commands.

There doesn't appear to be a scope for these, so I disabled them using a regexp that ignores all commands starting with `\`:

```json
    "spellright.ignoreRegExpsByClass": {
        "markdown": [
            "/\\\\[^\\\\ {]*/g"
        ]
    },
```

Is this the recommended style? If so, should we document it as such?

Aside: Although this was working just fine, I've noticed this setting appears occasionally unreliable; e.g. I restarted VS Code and noticed that I am once again getting LaTeX-related spelling errors. If that problem recurs I will open a new issue.

**Comment by bartosz-antosik** [comment]
Hi! This is exactly how it should be done! This approach has some limits of course (e.g. see description of `latexSpellParameters` but I am really unable to cover all specific aspects of all document types. Especially as VSCode does not share any syntactic information about the document with extensions.

I think this is documented around the description of `ignoreRegExpsByClass` not with this specific use but generally, how to do this sort of things. I will maybe add this example to the README.md.
