### ISSUE TITLE
ERR [spellright] Spell checker not initialized properly.

### ISSUE THREAD

**Issue by jonathanbell** [bartosz-antosik/vscode-spellright#215]
I haven't used this plugin for a couple of months but today I started writing a Markdown file and noticed that misspelled words were not underlined. When I checked in Developer Tools, I noticed this error: 

> ERR [spellright] Spell checker not initialized properly.

I'm not sure what the issue could be but thought you might. My OS is Windows 10 and my VS Code version is 1.27.2

**Comment by bartosz-antosik** [comment]
Thanks for the report. It may be related to the recent multiple-language changes.

Could you tell me please whether you can click in taskbar item ("eye") and change language?

**Comment by jonathanbell** [comment]
Sincere apologies! Clicking the "eye" and selecting English turned on the spellright spell checking!

**Comment by bartosz-antosik** [comment]
It is fine that it recovers after selecting language but still I would love to know how was the situation in the first place. You do not have any clue per chance? Like you do not remember what was the configuration when you first started the spellchecker? Also - have you maybe changed your primary language in the meantime?

BTW you can turn updating configuration off if you are unhappy about this.  Please have a peek at README for details.

**Comment by bartosz-antosik** [comment]
I think I know what has lead to this situation. Please check what language do you have set in User (global) settings. After switching language Spell Right updated Workspace (local) settings. But most probably when you switch to another workspace (folder) you may have the same problem because something which Spell Right cannot identify as a proper dictionary is set in User settings. If you could please confirm the findings.

**Comment by jonathanbell** [comment]
It's true, I do have the same issue when switching to another folder/workspace. Clicking the "eye" only adds the local (folder scoped) configuration via the `.vscode` directory. I'll copy/paste the SpellRight section of my `settings.json` below. I notice that I do not have `spellright.language` set. Should I add that to my customized user settings? I don't know why that wouldn't be set default to English. Perhaps this changed with an update to VS Code? 

```json
// Enable/disable adding words to system custom spelling dictionary instead of user dictionary.
  "spellright.addToSystemDictionary": false,

  // Scope for automatic configuration update.
  "spellright.configurationScope": "workspace",

  // Enable/disable automatic update of configuration from GUI operations.
  "spellright.configurationUpdate": true,

  // Document types for which spelling will be turned ON by default.
  "spellright.documentTypes": [
    "markdown",
    "latex",
    "plaintext"
  ],

  // Enable/disable grouping of dictionaries by language.
  "spellright.groupDictionaries": true,

  // List of file patterns ignored during spelling.
  "spellright.ignoreFiles": [
    "**/.gitignore",
    "**/.spellignore"
  ],

  // Regular expressions to eliminate from spelling.
  "spellright.ignoreRegExps": [],

  // Regular expressions to eliminate from spelling per document type.
  "spellright.ignoreRegExpsByClass": {},

  // Default language set (dictionary/region) used for spelling.
  "spellright.language": "",

  // Decide which language is used to spell syntactic parts of documents.
  "spellright.languageContext": {},

  // Decide which language is used to spell syntactic parts of documents per document type.
  "spellright.languageContextByClass": {},

  // List of LaTeX commands that will have the parameter list spell checked.
  "spellright.latexSpellParameters": [
    "author",
    "title",
    "subtitle",
    "date",
    "chapter",
    "section\\*?",
    "subsection\\*?",
    "subsubsection\\*?",
    "part",
    "paragraph",
    "subparagraph",
    "text(rm|sf|tt|md|bf|up|it|sl|sc|normal)",
    "underline",
    "emph",
    "item",
    "footnote(text)?",
    "caption(of)?",
    "multicolumn",
    "href",
    "hyperref",
    "institute",
    "frametitle",
    "framesubtitle",
    "begin\\{frame\\}"
  ],
```

**Comment by bartosz-antosik** [comment]
Thanks for investigation! I will have another look at this. I already did some changes to notify about such a situation, but maybe there is more.

Could you tell me what is your primary language of Windows (It's not necessarily same as interface language) and do you have a spell checking dictionary for this language installed?

**Comment by jonathanbell** [comment]
No problem - happy to help. Thanks for your attention.

Here is the PowerShell output when I check my language via `Get-Culture`:

```
-> jonat $ Get-Culture | Format-List -Property *

Parent                                                 : en
LCID                                                    : 4105
KeyboardLayoutId                              : 4105
Name                                                  : en-CA
IetfLanguageTag                                 : en-CA
DisplayName                                      : English (Canada)
NativeName                                        : English (Canada)
EnglishName                                       : English (Canada)
TwoLetterISOLanguageName             : en
ThreeLetterISOLanguageName           : eng
ThreeLetterWindowsLanguageName : ENC
CompareInfo                                       : CompareInfo - en-CA
TextInfo                                                : TextInfo - en-CA
IsNeutralCulture                                   : False
CultureTypes                                        : SpecificCultures, InstalledWin32Cultures, FrameworkCultures
NumberFormat                                    : System.Globalization.NumberFormatInfo
DateTimeFormat                                  : System.Globalization.DateTimeFormatInfo
Calendar                                               : System.Globalization.GregorianCalendar
OptionalCalendars                                : {System.Globalization.GregorianCalendar, System.Globalization.GregorianCalendar}
UseUserOverride                                  : True
IsReadOnly                                           : False
```

And here is a screenshot of my language settings:

![screenshot of my image settings on Windows 10](https://user-images.githubusercontent.com/1707639/46367470-85c8e480-c632-11e8-990e-048a889a1304.png)

Let me know if you need anything.

**Comment by bartosz-antosik** [comment]
This issue should be fixed in just released version 3.0.4. Cheers.

**Comment by Leedehai** [comment]
> Thanks for the report. It may be related to the recent multiple-language changes.
> 
> Could you tell me please whether you can click in taskbar item ("eye") and change language?

Sorry, where's the "eye" icon? What is taskbar in VSCode? Is it the bar at the bottom (whose name is "status bar")?

**Comment by Leedehai** [comment]
Follow up: the "eye" icon seems to have been removed by VSCode (Ubuntu, version 1.47). To select language, use Ctrl+P, type "> spellright" to get the list of commands, select `Spellright: Select dictionary (language)`. Also, for Linux specifically, users have to ensure appropriate `*.aff` and `*.dic` files are at the right place (see Spellright README.md). Problem resolved!
