### ISSUE TITLE
SpellRight not working on VSCode 1.27.1 for macOS 10.14?

### ISSUE THREAD

**Issue by Leedehai** [bartosz-antosik/vscode-spellright#217]
Hi, SpellRight is not working.
I verified SpellRight is not disabled in extension panel and in settings.json, but it does not give any indication on wrongly-spelled words in my files (README.md,  by the way). Wondering if this can be reproduced on your machine.

This is a great tool, BTW:)

Suggest: add an option to force SpellRight to run on the editor in order to quickly find out the problem.

**Comment by bartosz-antosik** [comment]
Hi! Seconds ago I had a situation like this: #215. Your's is not similar in any way? I mean do you see the "eye" icon in the status bar? What language is selected?

You can force spelling of the document with `"spellright.recheckOnSave": true`. Do you mean something like this or you meant something different?

**Comment by bartosz-antosik** [comment]
Thanks for the update. It will be fixed in next release.

**Comment by bartosz-antosik** [comment]
This issue should be fixed in just released version 3.0.4. Cheers.
