### ISSUE TITLE
[Off Topic] Word list used in this extension

### ISSUE THREAD

**Issue by tecosaur** [bartosz-antosik/vscode-spellright#219]
Hello,

Something I really like in this extension is the very comprehensive word list, with technical terms such as `eigenvalue` and `endosymbiosis`, which I have yet to find in other word lists. I would find this handy for other applications but I'm having trouble finding it - would you be able to point it out to me?

Thanks.

Edit for clarity: "_it_" = the word list file

**Comment by bartosz-antosik** [comment]
Spell Right uses system spelling engines. Please have a look in README it is explained in details there. The vocabulary is as rich as the dictionaries available for particular platform. Vocabularies for macOS and Windows seem generally richer and better maintained than those available for Hunspell, mostly used by other spellcheckers.
