### ISSUE TITLE
Spell problems prevent debugging

### ISSUE THREAD

**Issue by neilsustc** [bartosz-antosik/vscode-spellright#22]
If there are some spell problems in a file such as `README.md`, when launching debug, a warning will popup and I need to click `debug anyway`.
For some specific 'spell errors', I don't want to either fix them or add them to `.ignore`.
But it's not good to have one more `debug anyway` click since they are not crucial errors.

![image](https://user-images.githubusercontent.com/7588612/27566175-fa8118d0-5b15-11e7-93d0-b4aaf6e6f6eb.png)

**Comment by bartosz-antosik** [comment]
Do I understand it correctly that if you would have Spell Right OFF and it will not populate the diagnostics ("PROBLEMS") list with spelling errors the popup would not show?

**Comment by neilsustc** [comment]
Yes. I guess vscode simply don't care what kind of errors they are, so it will alert when there are spelling errors. It's a upstream issue of vscode logic I think.

**Comment by bartosz-antosik** [comment]
Is there a chance you could find out whether this comes from any of the extensions you have installed or from VSCode itself? If you could e.g. search fo the message text in your extensions folder?

The more I think of it & experiment the more obvious it seems to me that not much can be done about it in Spell Right. I could change diagnostic's severity property from Error to Warning which would probably make the popup stop appearing but it would display underlines in green which is totally counterintuitive & incoherent with every other spell checker out there (like Firefox I am writing this message in)...

**Comment by neilsustc** [comment]
I've moved this issue to the vscode repo [#29730](https://github.com/Microsoft/vscode/issues/29730).

**Comment by bartosz-antosik** [comment]
I have up-voted both your & original referring to the problem, but it does not seem as pressing issue judging by the number of votes... ;-)

**Comment by neilsustc** [comment]
😂
