### ISSUE TITLE
User setting spellright.ignoreRegExpsByClass seems to only accept a single regexp

### ISSUE THREAD

**Issue by jeblad** [bartosz-antosik/vscode-spellright#221]
Added something like this
```
	// Regular expressions to eliminate from spelling per document type.
	"spellright.ignoreRegExpsByClass": {
		"markdown": [
			"/[@#^](?:[eE]q:|[fF]ig:)?[-a-z0-9]+/g"
		]
	}
```
which works, but if I add another regexp for `"markdown"` then it fails.

One additional I used and could not get to work when there were more than one entry in the array were `"/\\\\$.*?\\\\$/g"`. I tried this in several variants, with exclusion of dollar signs, with repetition, etc. It seems like it is somewhat random what is excluded.

The same seems to happen with the class-less version.

Version is 3.0.4 in vscode 1.28.0 on Ubuntu 18.04

**Comment by jeblad** [comment]
Seems like this works
```
	// Regular expressions to eliminate from spelling per document type.
	"spellright.ignoreRegExpsByClass": {
		"markdown": [
			"/[@#^](?:[eE]q:|[fF]ig:)?[-a-z0-9]+/g",
			"/\\$.+?\\$/g",
			"/m(?:oa)+r/g"
		]
	}
```

Note single double escape on dollar sign ($), and a plus (+) instead of a asterix (*) on the second regexp. The third regexp is to verify that following regep's work.

My test file
```
# Test

This is a test.

Here comes an inline code blocff $n+m+\operatorname(iffypiffypaffy)$, this is flofftex.

lijhiuhhblkjb

$$n+m+\operatorname(iffypiffypaffy)$$  {#eq:foobar}

This is moar test.

This is even moaoar test.

kjhghljkkjl.
```

Do you merge these regexp's into a larger one?

This issue can probably be closed, it seems like an user issue. ;/

**Comment by jeblad** [comment]
Nope, there is something strange here. It seems like *sometimes* it happen, but so far I have no clue on how to reproduce it. Perhaps it has something to do with an internal rearrange of the regexp, as it comes and goes after saves…

**Comment by bartosz-antosik** [comment]
What you experience may be emanation of [#60394](https://github.com/Microsoft/vscode/issues/60394) of VSCode, reported by me few days ago in the raise of issues (starting with #218). If you maybe observe similar behavior, which may be related to the way diagnostics are update, it may be a good idea to upvote the issue because it seems it has not gained any traction so far.

**Comment by jeblad** [comment]
Yes, this is flaky behaviour and not predictable. I would not be surprised if this has something to do with vscode as such. Perhaps let it stay open for a short time and see if any other might have an explanation?

**Comment by bartosz-antosik** [comment]
An error in VSCode has been fixed ([#60394](https://github.com/Microsoft/vscode/issues/60394)) and I have applied a workaround (in 3.0.5) which should fix things before the fix propagates to regular version of VSCode. I am closing the thread - please report here whether it has fixed the issue for you.

**Comment by jeblad** [comment]
Bumped into this again, and it is real. It is an issue with looping over the object keys.

**Comment by jeblad** [comment]
I had a section in `.vscode/settings.json` like
```json
{
	"spellright.documentTypes": [
		"markdown",
		"latex",
		"plaintext"
	],
}
```

Removing `"plaintext"` fixed the regexp problem. Either a bug in the plaintext parser or a memory allocation issue. I suspect the later. Note in particular that line 614 in spellright.js does not verify whether a valid object is returned, thus this weird behaviour exist without being logged.

I have not made any attempt on debugging plaintext (or latex), I just removed them as they are not necessary for the specific project.
