### ISSUE TITLE
Doesn't react fully to manual settings changes.

### ISSUE THREAD

**Issue by oltodosel** [bartosz-antosik/vscode-spellright#226]
When I directly edit settings.json and change `"spellright.documentTypes": ["plaintext"]` to `"spellright.documentTypes": []` spellcheck does stop working, but if I do it in reverse - it doesn't react.

I need this to bind on/off to a hotkey with [settings-cycler](https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler).

**Comment by bartosz-antosik** [comment]
Thanks for pointing this out. Should be fixed in next release.

**Comment by oltodosel** [comment]
Works. Thanks.
