### ISSUE TITLE
Weird behavior

### ISSUE THREAD

**Issue by athosbr99** [bartosz-antosik/vscode-spellright#23]
I installed this extension on my Visual Studio Code and I couldn't figure it out how it works or if it is working properly on my computer.

The spell check didn't worked ever on new plain text files. I tried with LaTeX files (with syntax plugins) and it only works if I reselect the language that I want to correct (I already set it by default on settings.json).

Any help would be appreciated. I'm using Windows 10 Home Single Language with Creators Update.

**Comment by bartosz-antosik** [comment]
Could you please help me and answer the questions below:

1. What have you set in in settings as the language?
2. If you switch it using the list (I mean using GUI, like you describe if I understand it correctly) then it spells correctly until it is restarted?
3. If you would switch it using the list (like in 2) and then select `SpellRight: Create/Update Workspace Settings` and then restart would it spell correctly?
4. After 3. what would be the value of `language` in `spellright.json` workspace file in `.vscode` directory?

**Comment by athosbr99** [comment]
1. I set "Portuguese". I tried "pt_BR" (since there is two kinds of portuguese) but it didn't worked.
2. It makes the corrections immediatly when I reselect the language when using LaTeX files. It has no effect on plain text

**Comment by bartosz-antosik** [comment]
If you could please try 3 (Selet `Ctrl+Shift+P` and then select `SpellRight: Create/Update Workspace Settings`) and after that see what is written to workspace settings (4).

Ad. 1. I would rather try `pt` or `pt-BR` with Windows native spell checking API, but doing 3 + 4 will tell us what is the name of the dictionary you have. Then it would be easier to us to proceed with some sort of refinement/resolution for your situation.

**Comment by bartosz-antosik** [comment]
Also, please, if you could have a look at the DEBUG output if there is any debug output at the moment e.g. when you switch to PlainText document (which is as you say not spelled at all).

**Comment by athosbr99** [comment]
Doing 3. created this:

`//
// Spell Right workspace configuration file.
//
{
    "language": "Portuguese",
    "documentTypes": [
        "markdown",
        "latex",
        "plaintext"
    ],
    "groupDictionaries": true,
    "statusBarIndicator": true,
    "suggestionsInHints": true,
    "ignoreWords": [],
    "ignoreRegExps": [],
    "ignoreFiles": [
        "**/.gitignore",
        "**/.spellignore"
    ]
}`

It also made no effect. I had to reselect the language to make it work.

I made a GIF to explain it better:

![2017-07-01_18-38-38](https://user-images.githubusercontent.com/6440060/27765610-9f59f592-5e8c-11e7-8ad6-62d325f5dd7b.gif)

**Comment by athosbr99** [comment]
I setted `pt-BR` on settings.json and it seemed to work on everywhere now.

**Comment by bartosz-antosik** [comment]
Please give version 1.0.23 a try. It should fix what you observe. Should also set default language to Portuguese without need to set it anywhere in settings.

**Comment by athosbr99** [comment]
It seemed to work. However I had to remove pt-BR from settings to work.

Is there anyway to choose between Portuguese and English?

**Comment by bartosz-antosik** [comment]
Generally the extension integrates all dictionaries with one region (e.g. en-UK, en-US, en-CA etc.) into one entry in the list ("English") and selects the dictionary by setting e.g. "en" in settings. So in your case "pt" would be sufficient to select Portuguese. It's done to avoid mess of having e.g. 15 English dictionaries for exotic regions. This will be maybe changed in the future or made optional etc.

**Comment by athosbr99** [comment]
I mean if it there is a way to use English as a dictionary. When I click in the eye icon it only shows Portuguese and Spanish (don't know why, since my computer doesn't have anything in spanish)

**Comment by bartosz-antosik** [comment]
To spell in English you have to have english spelling installed in Windows. I have no idea whether "Windows Single Language" is any different but normally you have to add languages in `Control Panel`'s `Language` section as you can see below:

![langugage](https://user-images.githubusercontent.com/20492548/27825069-b33ef2f0-60ae-11e7-998b-9dce46d56599.png)

Why do you have Spanish language in the list I cannot tell, but the extension is supposed only to list dictionaries returned by the Windows Spelling API - so it looks, somehow, like it has returned Spanish dictionary.

**Comment by athosbr99** [comment]
the whole point of "Single Language" is that... Windows only supports one language. so no english spelling for me until I update my Windows version 😢 

since my only language and dictionary is Portuguese (Brazil) it shouldn't have Spanish dictionary. but thats a minor detail I guess. you can close the issue now since it was fixed

**Comment by bartosz-antosik** [comment]
I have not closed this since I had to check this thoroughly but it seems you are absolutely right - Windows Single Language does not allow to install more than one language pack.

There is another option for you: You can set system variable (there where you set PATH) named "SPELLCHECKER_PREFER_HUNSPELL" to 1 and the extension will use Hunspell spellchecker in Windows 10. Then you have to install dictionaries as described in the README.md under the **Note on Windows 7 Installation** heading. This procedure will allow you to have as many languages/dictionaries as you wish. Please remember that the variable you set in `spellright.language` is the name of the dictionary (also see recently updated README.md for more on this).

**Comment by bartosz-antosik** [comment]
Once again: I was wrong! My initial intuition & searches in the web (the reason I was not closing the issue for so long) were correct.

Single Language Windows edition does not allow one thing: Change of display language. It does however install other spelling dictionaries & work with them correctly. Here see Windows Single Language EN/US spelling in Polish:

![windows-single-language-1](https://user-images.githubusercontent.com/20492548/28008827-584e9440-6559-11e7-975a-15c5c1cdc5f4.png)

Here is Control Panel with two languages installed:

![windows-single-language-2](https://user-images.githubusercontent.com/20492548/28008843-62418124-6559-11e7-909b-c24d6488eb9f.png)

And here is the information that what you cannot change is Display Language:

![windows-single-language-3](https://user-images.githubusercontent.com/20492548/28008858-6fc6bcd8-6559-11e7-9b63-72877e31bed8.png)

P.S. Please let me know if this messages get to you!

**Comment by athosbr99** [comment]
Gonna try here. I tried to install from the "new" Settings thing on Windows 10 so perhaps thats why didn't worked.

**Comment by athosbr99** [comment]
witchcraft, it works!

![image](https://user-images.githubusercontent.com/6440060/28029793-a2e97290-6577-11e7-9503-fd3e1df827f2.png)

**Comment by bartosz-antosik** [comment]
Great! Thanks for cooperation.
