### ISSUE TITLE
Question: How to ignore acronyms

### ISSUE THREAD

**Issue by AceTheWiz** [bartosz-antosik/vscode-spellright#230]
How do I configure SpellRight to ignore acronyms. They are usually 3 to 4 UPPERCASE characters.
Example acronyms. STD, VSD, BMS etc.

I have tried setting ```"spellright.ignoreRegExps": ["\\b[A-Z]{3,4}\\b"]``` but I get a "malformed" error.

_Note: This regex works in VSCode search._

**Comment by bartosz-antosik** [comment]
Hi! Thanks for self-resolving issue! I will modify the documentation. There are actually two issues here one is that these are complete regular expressions to make this more elastic (e.g. they can work as multi line etc.) and there is the issue of quoting charactes in JSON settings document.But
