### ISSUE TITLE
Accented character bug

### ISSUE THREAD

**Issue by free-easy** [bartosz-antosik/vscode-spellright#233]
In Ubuntu (I'm using 18.04), accented characters are not recognized (at least for Italian).

![screenshot from 2018-12-06 15-28-45](https://user-images.githubusercontent.com/20483759/49590322-e5fa4080-f96b-11e8-9e52-29a47b474443.png)

**Comment by bartosz-antosik** [comment]
Could you tell mem please tell me where did you get your dictionary from? Also, could you please paste here, below, in text format, word (or few) which should be spelled properly and are not? Just to have some material to test...

**Comment by free-easy** [comment]
I got the dictionary by running this command `sudo apt install hunspell-it`.
Any word with accented character triggers false negative. Just to list a few ones:
`difficoltà`, `felicità`, `città`, `però`.

As you can see from the screenshot, the word `difficoltà` is marked as wrong and one of the suggestiones (the last one) has as last character a �, which I suppose to be the accented character.

**Comment by carlfranz** [comment]
I'm having the same issue, looks like the hunspell dictionary is in @ISO-8859-1@.

    uchardet it_IT.dic

**Comment by bartosz-antosik** [comment]
Hi! Thank you for the update!

There is a notice in the README that Hunspell (which is the spelling backend on Linux) can only accept UTF-8 dictionaries. Could you please follow advice in README about where to get the dictionaries from and tell me whether it helps?

**Comment by carlfranz** [comment]
Dictionaries are from ubuntu repository. Btw could be solved changing encoding with iconv.

    iconv -f ISO-8859-1 -t UTF-8 it_IT.dic -o it_IT.conv.dic
    mv  it_IT.conv.dic  it_IT.dic

**Comment by free-easy** [comment]
@carlfranz Thank you for the workaround.

I confirm that the problem is related to the dictionary.
