### ISSUE TITLE
Errors are first listed and immediately erased

### ISSUE THREAD

**Issue by chasset** [bartosz-antosik/vscode-spellright#234]
Hello,

The vscode-spellright package seems to work, but the results are immediately erased after the document is checked. So, I haven't enough time to correct them!

Please find below my settings on macOS:
```
{
  "spellright.language": [
    "fr"
  ],
  "spellright.documentTypes": [
    "rmd"
  ],
  "spellright.ignoreFiles": [
    "tools/**/*.Rmd"
  ],
  "spellright.ignoreRegExpsByClass": {
    "rmd": [
      "/{[^}]+}/g",
      "/\\\\.+\b/g",
      "/@.+\b/g",
      "/=\\d+(em)/g"
    ]
  }
}
```
Could you correct it?
Best regards,

Pierre-Olivier

**Comment by bartosz-antosik** [comment]
Could you please try to disable other extensions and reproduce the problem?

**Comment by chasset** [comment]
The package now works fine.

Only three packages are activated:
- French language pack for viscose
- R
- Spell Right

Many thanks.
