### ISSUE TITLE
Windows 10 / Insiders 1.31: This extension stopped working with an error

### ISSUE THREAD

**Issue by nickjj** [bartosz-antosik/vscode-spellright#236]
Hi,

I've been using your extension for a long time without issues using various versions of `code-insiders`.

I'm not sure what happened, but it stopped working recently. I no longer see suggestions for any words that are misspelled.

Maybe it was due to upgrading to insiders 1.31, but I can't say for sure.

In the dev tools it says:

```
/E:/apps/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5720 Activating extension 'ban.spellright' failed: Cannot read property 'Spellchecker' of null.
t._logMessageInConsole @ /E:/apps/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5720
```

I tried removing all custom Spell Right settings (using the defaults at the moment). It always throws that error.

What else can I do to provide more info to resolve this?

**Comment by bartosz-antosik** [comment]
It is because of the Electron version bump.

Should be fine with just released version 3.0.18. Let me please know here!

**Comment by nickjj** [comment]
Awesome, it's fixed. Yay for red squigglies.

**Comment by bartosz-antosik** [comment]
:-)
