### ISSUE TITLE
Dictionary Installation instructions on linux with code-insiders seems incorrect

### ISSUE THREAD

**Issue by bkc** [bartosz-antosik/vscode-spellright#238]
I am running code-insiders 1.31.0-insider on Linux.

I installed hunspell dictionaries in ~/.config/Code/Dictionaries per the installation instructions.

Unfortunately 'select dictionary' command shows no dictionaries in the list. I followed the debug instructions in #53 and reviewed the console output.

I discovered that this extension is actually looking in `~/.config/Code - Insiders/Dictionaries`

I am running extension version 3.0.18

After installing dictionaries in this alternate directory, the select dictionary command now works.

**Comment by bartosz-antosik** [comment]
Hi! Thank you for noticing. I think this requires a notice in documentation.
