### ISSUE TITLE
"Show fixes" button follow column

### ISSUE THREAD

**Issue by Ilias48rus** [bartosz-antosik/vscode-spellright#244]
The button seems always show-up at start of paragraph, it's very uncomfortable to use, and would be very pleasant to make it shown at selected {word/ line + column} (make sure to work with world-wrap).

Thanks for making the extension ,in first place.

**Comment by bartosz-antosik** [comment]
Hi! It is not the extension that is responsible for drawing "the bulb". Extension just provides a list of ossible fixes and all of the rest is how Visual Studio renders/serves the suggestions.

**Comment by Ilias48rus** [comment]
@bartosz-antosik, in this case solution maybe could be using some other GUI elements for the correction suggestions (like listed options in {on-hover element ,and click event handlers} or RMB list), which-ever is possible, maybe i didn't described correctly, but this "issue" is about the issue, not solution. And thanks for info.

**Comment by bartosz-antosik** [comment]
AFAIK there is really no other way to do this. There is no access to general GUI elements, just these provided by VSCode.

**Comment by Ilias48rus** [comment]
@bartosz-antosik i just mentioned the issue, it won't add new way to fix it to the VSC :), but the issue don't disappear either.
