### ISSUE TITLE
Spell right is always disabled and can not be enabled

### ISSUE THREAD

**Issue by sztal** [bartosz-antosik/vscode-spellright#249]
Hi,

I just installed the Spell Right and after reloading the VS Code Spell Right becomes disabled and can not be enabled. What can be reason for that and what kind of info should I provide you, so you can figure this out?

I am working on Ubuntu 18.04.

Also, just right after an installation Spell RIght is enabled until the first reloading of VS Code. However, even then invokation of any Spell Right command fails. For instance when trying to set a language I get:

```
Error: Running the contributed command:'spellright.selectDictionary' failed.
	at e._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:486)
	at e.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:486)
	at t._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:644)
	at t._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:643)
	at t._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642)
	at t._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:641)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:638
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:38
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at a (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170)
	at Socket.f._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170)
	at Socket.emit (events.js:182)
	at addChunk (_stream_readable.js:279)
	at readableAddChunk (_stream_readable.js:264)
	at Socket.Readable.push (_stream_readable.js:219)
	at Pipe.onread (net.js:636)
```

**Comment by bartosz-antosik** [comment]
Could you please elaborate a bit on what do you mean by disabled?

Disabled as disabled component or that you cannot enable the language to spell in status bar?

Also, you did have downloaded the dictionaries, right?

**Comment by sztal** [comment]
Yes, I downloaded the dictionaries and setup the `$HOME/.config/Code/Dictionaries` directory.

As for what I mean by disabled, I mean that Spell Right is disabled entirely as a VS Code extension and there is no way to enable it in VS Code.

**Comment by bartosz-antosik** [comment]
Hm, then I have absolutely no idea!

**Comment by bartosz-antosik** [comment]
There is something, I recall, that changed just recently in VSCode - the extensions are supposed to be enabled without reloading. It has changed in very last version of regular release (1.31). Maybe something there interferes?!

**Comment by sztal** [comment]
That sounds like a clue. However, my knowledge of internal workings of VS Code equals zero, so I am afraid I can not help you with that :P

**Comment by LonMcGregor** [comment]
I get the same issue in windows 10. Every time I restart code I need to re-install this extension for it to work. The menu looks like this:

![image](https://user-images.githubusercontent.com/3817332/53506358-bad84680-3aad-11e9-806c-087a0298a0dd.png)

It works perfectly after installing it until I next re-open code.

**Comment by bartosz-antosik** [comment]
@LonMcGregor And the issue happens only with Spell Right?

**Comment by LonMcGregor** [comment]
@bartosz-antosik Yes.

I have many other extensions that I am able to Enable always, enable for specific workspaces, or disable always and they remember their settings. It's just spell right so far that seems to have issues.

All my other extensions also have their right click menus showing properly, in that one of either the enable or disable options are clickable.

I had a look through my vscode config files, but I can't see anything that indicates an obvious problem.

**Comment by LonMcGregor** [comment]
Something which might be helpful that I've just thought of: I have the following languages installed at a system level: 

English UK, French FR, Japanese JP

Seeing as it uses the system spell checking, maybe this issue only happens with a certain combination of installed languages? I haven't been able to test it yet without those languages installed.

**Comment by bartosz-antosik** [comment]
@LonMcGregor Thanks. I will try to install these and see if it is related.

**Comment by bartosz-antosik** [comment]
@LonMcGregor Could you tell me please where have you downloaded these dictionaries from? From the link provided in README (UK, FR)? This link does not point to Japanese dictionary so you must have taken it from somewhere?

**Comment by LonMcGregor** [comment]
> @LonMcGregor Could you tell me please where have you downloaded these dictionaries from? From the link provided in README (UK, FR)? This link does not point to Japanese dictionary so you must have taken it from somewhere?

In the windows 10 settings app I installed English UK and French FR as "Language Packs". I just checked, and even though I've installed the japanese language pack it doesn't include a spell checker dictionary, so I might have been mistaken on that front.

**Comment by sztal** [comment]
Hi, I am happy to inform that for some magical reason I do not understand `SpellRight` started to work like charm again (I am running VS Code on Ubuntu 18.04). There were a few VS Code updates over the last few months, so I guess the problem must have been accidentally solved during one of these updates, but I know no details.

Anyway, I am glad `SpellRight` works again for me, since it is clearly a best spell check for VS Code out there.

**Comment by LonMcGregor** [comment]
Oh yes, after the update to 1.34.0 spell right is now enabled when I restart VS Code. Tentatively I would say the issue I had is resolved.

I guess it was VS Code's fault, somehow. I'm not sure what changed though.

**Comment by bartosz-antosik** [comment]
Many thabks guys for reporting this!

I was unable to reproduce the issue and little sad about the whole thing.
