### ISSUE TITLE
JSON strings are checked when they shouldn't

### ISSUE THREAD

**Issue by borekb** [bartosz-antosik/vscode-spellright#253]
This is my Spell Right config:

```json
{
    "spellright.language": ["en"],
    "spellright.addToSystemDictionary": true,
    "spellright.notificationClass": "information",
    "spellright.documentTypes": [
        "markdown",
        "typescript",
        "json",
        "html",
        "typescriptreact",
    ],
    "spellright.spellContext": "body comments strings",
    "spellright.spellContextByClass": {
        "markdown": "body",
        "typescript": "comments",
        "json": "comments",
        "html": "body",
        "typescriptreact": "body comments",
    }
}
```

In JSON, it should only check comments (well, VSCode calls this format "JSON with comments"; I hope it's still "json" in SpellRight's `documentTypes`) but it also checks inside strings for me:

<img width="1035" alt="screenshot 2019-03-01 at 11 01 31" src="https://user-images.githubusercontent.com/101152/53631030-cf355400-3c11-11e9-914d-8a6b494c5592.png">

Is that a bug or misconfiguration on my part? Thanks.

**Comment by borekb** [comment]
Misconfiguration. The document type needs to be "jsonc":

```json
{
    "spellright.documentTypes": [
        "jsonc"
    ],
    "spellright.spellContextByClass": {
        "jsonc": "comments"
    }
}
```

Sorry about that.

**Comment by bartosz-antosik** [comment]
Have less time recently. Haven't even noticed the thread and you already closed it. Cheers!

;-)
