### ISSUE TITLE
How to ignore blocks of comments and string in python?

### ISSUE THREAD

**Issue by haochange** [bartosz-antosik/vscode-spellright#254]
"""
supercategory

"""
print("supercategory")

str_t = './supercategory'

\# make install i

**Comment by haochange** [comment]
![20190305145125](https://user-images.githubusercontent.com/17872653/53786530-f44dfd80-3f56-11e9-8ed4-3f097c92ff79.png)

**Comment by bartosz-antosik** [comment]
Hello! Is not `spellContextByClass` configuration setting what you need?

**Comment by haochange** [comment]
THX，solved
