### ISSUE TITLE
Suppress checking in latex syntax

### ISSUE THREAD

**Issue by lonelykid** [bartosz-antosik/vscode-spellright#258]
Can I somehow only let it check for the plain text part of the latex file?
![image](https://user-images.githubusercontent.com/2936633/54501625-b8267f80-48fc-11e9-88e6-629912dec514.png)

**Comment by bartosz-antosik** [comment]
I will look into this.

**Comment by bartosz-antosik** [comment]
It should be fixed in the just release version 3.0.30. Please let me know if it is indeed.

It was introduced in the recent attempt to make LaTeX parser speedier.

**Comment by lonelykid** [comment]
Thank you! It's working as expected. The only problem now is that it's still complaining about part of the equations. e.g. the mgy in W=mgy. This is acceptable. I just add them to workspace dict. 

Maybe only check for spelling in \text{} or similar environments in equation mode. I'm not sure whether this is a good idea.

**Comment by bartosz-antosik** [comment]
Math should not be spelled. Could you please show me an example (copy-able, not screenshot, preferably)?

**Comment by lonelykid** [comment]
See this demo.tex 
\documentclass[12pt]{extarticle}
\begin{document}
\begin{equation}
    V=mgy
\end{equation}
\end{document}

"mgy": suggestions: my, mg, may, mgs, muggy

**Comment by bartosz-antosik** [comment]
Then no! What it does skip is:

$ math $
\( math \)
\[ math \]

I will have to think about the syntax you mention. It's probably worth adding to Spell Right. Anyway it can probably be added using regular expressions (see README.md).

**Comment by lonelykid** [comment]
Thank you. something like \\\\begin{equation}[^]*?\\\\end{equation} will do.
it would be even better to be able to check within \text{} in equations though.

**Comment by bartosz-antosik** [comment]
Also `\begin|\end{align*}` maybe. To check within `\text{}` I have to recognize equation block first anyway...

**Comment by Bakerbakura** [comment]
Please do add detection of equation blocks! Some equation-type environments which should not be spelled when inside a begin/end block are:

- equation
- equation*
- align
- align*
- gather
- gather*
- flalign
- flalign*
- multline
- multline*
- alignat
- alignat*

Some text inside these environments which should be spelled include stuff inside `\text{}`, `\intertext{}`, and `\shortintertext{}`.
