### ISSUE TITLE
`ignoreWord` don't work with PascalCased words

### ISSUE THREAD

**Issue by borekb** [bartosz-antosik/vscode-spellright#26]
This might be a bug:

![image](https://user-images.githubusercontent.com/101152/27913852-b313f596-6261-11e7-9d8c-fac468a4abb5.png)

![image](https://user-images.githubusercontent.com/101152/27913860-b8ba09f4-6261-11e7-95d2-1a4182b9223e.png)

**Comment by bartosz-antosik** [comment]
It may be a sign of bug but maybe in some indirect way. Here is what I get trying to reproduce the behavior:

![phpstorm-2](https://user-images.githubusercontent.com/20492548/27932008-6164115a-629c-11e7-89ce-1b6c55414a55.png)

![phpstorm-1](https://user-images.githubusercontent.com/20492548/27932012-66c69532-629c-11e7-8008-fb954203e758.png)

Could you maybe pass me whole content of spellright.json & the test document?

**Comment by bartosz-antosik** [comment]
Oh, wait - this comes from User (that is global) settings! Let me check.

**Comment by bartosz-antosik** [comment]
So when setting ignoreWords in User Settings it works fine as well.

**Comment by borekb** [comment]
Yes it's in my `settings.json` (user settings). I'm on 1.0.24.

**Comment by bartosz-antosik** [comment]
And you are sure that there is no Workspace settings that override User settings?

**Comment by borekb** [comment]
Positive; there is no `.vscode` folder in my project.

UPDATE: I've reloaded the window and all seems OK now.

**Comment by bartosz-antosik** [comment]
Extension SHOULD watch for changes in workspace settings, but it DOES NOT watch for changes in User settings. This means after User settings changes VSCode has to be restarted. Also, kind of, "by design". Maybe worth rethinking. Was it possibly this?

**Comment by borekb** [comment]
Probably.. If you're going to implement the full "misspelled word -> add to dictionary -> spelling error goes away" workflow, it would be good to be able to do that without full VSCode reload :)

I'm thinking about where to store the custom words. On Windows, I already maintain like 6 custom dictionaries (Chrome profile 1, Chrome profile 2, Office, Markdown editor I use, PhpStorm, ...), it's pretty crazy but it's probably a platform limitation. If there would be any way to save me from maintaining 7th custom dictionary it would be awesome :) At least it should be in user settings or some file I can synchronize using https://github.com/shanalikhan/code-settings-sync.

**Comment by bartosz-antosik** [comment]
It works like this with workspace settings!

Quite some custom dictionaries! I will think about this but I am a fan of pushing such a things to Workspace settings - these are pretty easy to maintain, copy, duplicate etc. But maybe it is just me.

I am also not sure if extension can change User settings. I think it can not but I am not sure about it.

**Comment by borekb** [comment]
Workspace settings are a no-go: they are committed to Git and shared with a team. Custom dictionaries need to be user settings, or a file like `spellright.json` stored in the user directory. I _think_ VSCode Settings Sync would then pick it up (which is desirable for me).
