### ISSUE TITLE
Custom system dictionary doesn't work on MacOS

### ISSUE THREAD

**Issue by alexandru** [bartosz-antosik/vscode-spellright#260]
I've added a custom dictionary to my MacOS system dictionaries (copying them from [titoBouzout/Dictionaries](https://github.com/titoBouzout/Dictionaries) into `~/Library/Spelling/`).

I see that Spellright is supposed to use the system's spellchecker, however the custom dictionary isn't visible. I need it to spellcheck Romanian, which isn't a language installed by default.

Any help is appreciated.

**Comment by bartosz-antosik** [comment]
Hi! It is mentioned in Known Issues at the bottom of README.md. It seems to be outside of the scope of my extension and I can not do anything about it.

**Comment by alexandru** [comment]
Damn, OK, so I guess I'm going to close this.

**Comment by bartosz-antosik** [comment]
I do not understand why it is so. It seems very strange. The truth is I have not searched for any updates on this, maybe never versions of macOS have done something about it.
