### ISSUE TITLE
Add support for Italian language

### ISSUE THREAD

**Issue by lolgab** [bartosz-antosik/vscode-spellright#262]
It would be great to have italian language support for vscode-spellright.

**Comment by bartosz-antosik** [comment]
Hi! What OS? Have you checked what README says about adding dictionaries in various OSes?

**Comment by lolgab** [comment]
I'm on Linux, I'm sorry but had not read that section of the README.

**Comment by bartosz-antosik** [comment]
If you see something that is unclear or does not work - plese let me know! Cheers!
