### ISSUE TITLE
LaTeX checking broken in all commmands

### ISSUE THREAD

**Issue by jackweinbender** [bartosz-antosik/vscode-spellright#263]
A recent update seems to be ignoring all spelling errors contained within commands with curly-braces. I'm using MacOS with SpellRight 3.0.30.

So, I noticed this when several of my `footnote{text}` wasn't being checked, but now I see that even `\emph{}` doesn't check. If I delete the `\command` part, it spell checks perfectly.

**Comment by bartosz-antosik** [comment]
Should be fixed in version 3.0.32. If you could please confirm would be helpful.

**Comment by jackweinbender** [comment]
Updated to 3.0.36.

It is checking the spelling now (so I can confirm that), but it is also marking LaTeX commands as misspelled. I'm guessing it's getting pushed to the checker wholesale, rather than being parsed again as a document that can have more commands. See here:
![image](https://user-images.githubusercontent.com/1544859/55299222-97c7ec00-53f7-11e9-9e11-aaaf17ae0551.png)

**Comment by bartosz-antosik** [comment]
Thanks, I saw there is something off yesterday, just had not enough timne to correct. Whenever you point out something it is great help to have a copyable example. Thanks.

**Comment by jackweinbender** [comment]
Will-do. Also, just because I wasn't explicit in the above comment, LaTeX commands are being spellchecked *in footnotes*, they seem to be behaving normally in body text.

**Comment by bartosz-antosik** [comment]
It's actually that anything (any LaTeX command) embedded inside the `latexSpellParameters` commands will get spelled. But it's an error. Will pursuit.
