### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dpizetta** [bartosz-antosik/vscode-spellright#265]
- Issue Type: `Performance`
- Extension Name: `spellright`
- Extension Version: `3.0.38`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/pizetta/ban.spellright-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by bartosz-antosik** [comment]
#229
