### ISSUE TITLE
Do not spell check links in Markdown

### ISSUE THREAD

**Issue by borekb** [bartosz-antosik/vscode-spellright#27]
Originally reported in https://github.com/bartosz-antosik/vscode-spellright/issues/24#issuecomment-313523481 but it's worth a separate issue, IMO. Link part of MD link syntax shouldn't be spell checked:

`[Spell check this](DO NOT spell check this)`

Repro in 1.0.25:

![image](https://user-images.githubusercontent.com/101152/28068401-a564816c-6645-11e7-9f48-2921369e01a2.png)

**Comment by bartosz-antosik** [comment]
Done in 1.0.26.

**Comment by bartosz-antosik** [comment]
Sorry, 1.0.27.
