### ISSUE TITLE
All words with æ, ø, and å are marked as invalid in Norwegian Bokmål

### ISSUE THREAD

**Issue by jeblad** [bartosz-antosik/vscode-spellright#270]
Loaded Norwegian Bokmål dictionary and still got invalid words.

å: så på å gå
ø: ønske økt løse
æ: bevæpning færre

**Comment by bartosz-antosik** [comment]
Couyld you tell a bit more about OS, whare have you downloaded the dictionary from, whether you have checked if the dictionary IS UTF-8 (as described in README.md)?

**Comment by jeblad** [comment]
That was fast! :)

This is on Ubuntu 18.04.02 LTS, with VScode 1.33.0, and Spell Right 3.0.38.

For the moment I'm using both US Enlish (en-US) and Norwegian Bokmål (nb).

When I click on the lamp-icon to add terms to the dictionary, some of the terms show up with the typical diamond shaped code point. This is often a sign that there are a mixup of encoding format. This happen with "å", but not with "ø", which is also common. This could be another bug though… 

I'll check back if you have more questions.

**Comment by jeblad** [comment]
The downloaded file .code/Dictionaries/nb_NO.aff has a line `SET ISO8859-1`. Bugger!

Where does this file come from? Nearly everyone in Norway use UTF-8 these days.

**Comment by jeblad** [comment]
Seems like I had some very old files in my /usr/share/hunspell, and I did not even had hunspell set up. Installed hunspell, replaced the files, and it seems to work as expected.

The files were leftovers from a project a long time ago. ;)
