### ISSUE TITLE
Add to dictionary not showing up in context menu

### ISSUE THREAD

**Issue by mramato** [bartosz-antosik/vscode-spellright#271]
* I'm running on Kubuntu 18.04 and VS Code 1.33.1.
* Spell checking is working via `~/.config/Code/Dictionaries` with `en_US`.
* In the quick fix menu, a list of word suggestions appear but there is no way to add a work to a custom dictionary.
* I assumed right-click context menu would also have suggestions/add ability, but nothing shows up there, only the quick fix menu

I'm hoping it's something stupid I'm doing wrong but I can't for the life of me figure it out.

Thanks!

**Comment by bartosz-antosik** [comment]
Hi! How is the file opened (is it part of workspace, just a single file opened from somewhere etc.)? How is the VSCode installed (regular installation, portable etc.)?

**Comment by mramato** [comment]
* The file is part of the workspace.
* VS Code is installed from the official deb.

**Comment by bartosz-antosik** [comment]
Oh, just to be clear: When you say "right click menu" you refer to suggestions menu which is called by `Ctrl + .` not the right click? Like this:

![image](https://user-images.githubusercontent.com/20492548/56227884-c3dda100-6076-11e9-845e-3409f674ae0b.png)

Extensions cannot add things to right click menu. Just to this "diagnostics" menu.

**Comment by mramato** [comment]
Thank you, I was unaware of the "Ctrl + ." menu and somehow missed it in the documentation.  However, I was actually talking about the `Quick fix` menu as well:

![image](https://user-images.githubusercontent.com/1495196/56229228-6847ef00-6047-11e9-8629-e913534a8b7c.png)
