### ISSUE TITLE
Text uploads to cloud ?

### ISSUE THREAD

**Issue by chatelao** [bartosz-antosik/vscode-spellright#278]
Hi everybdoy,

I would like to use it, but have a question:

* Are any of my texts uploaded to the internet for spell-check?

Regards
Olivier

**Comment by bartosz-antosik** [comment]
Hi! No, as the name says, it's all offline. Everything is checked on the local system, nothing gets uploaded anywhere.

**Comment by chatelao** [comment]
Then write this on the first line, it is the best argument to use it.

**Comment by bartosz-antosik** [comment]
Welll, I thought I knida did! The title says "offline". Maybe it is not intuitive enough though...

**Comment by chatelao** [comment]
Sometimes "Offline" Stuff ist "Offline too", "Providing Anonymous Learning
Data", etc.

Maybe just write, that the server never senden data back.

Bartosz Antosik <notifications@github.com> schrieb am Di., 30. Apr. 2019,
18:22:
