### ISSUE TITLE
Crashes extension host when parsing emoji, for example 🇮🇳 

### ISSUE THREAD

**Issue by rhnvrm** [bartosz-antosik/vscode-spellright#284]
**Version information**:
VSCode: 1.34
SpellRight: 3.0.38

To reproduce, copy and paste this emoji (🇮🇳) in a markdown file with spellright enabled.

Probably related to (#223)

**Comment by danmackinlay** [comment]
@rhnvrm What platform are you on?
I'm seeing a spellRight crash on emoji, but not on VS Code macOS, only VS Code Ubuntu.

This markdown fragment causes spellright to crash:

```markdown

### Android

🤷‍♂️
```

It also renders badly in VS Code, although that is not the fault of spellright.
![Screenshot from 2019-07-18 21-19-27](https://user-images.githubusercontent.com/21740/61453591-db903280-a9a1-11e9-8b45-e20e68cb1d34.png)

```shell

dan@splayd /m/d/S/S/livingthing> code --status --show-versions                                                                          
Version:          Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS Version:       Linux x64 4.15.0-54-generic
```

I get an actual crashlog sometimes from the crashing extension host. I will attach it here next time it occurs,

**Comment by rhnvrm** [comment]
My current machine is using:
```OS Version:       Linux x64 4.15.0-51-generic```

I had tested this on Arch Linux (VS Codium) and Ubuntu (VS Code) both.

**Comment by danmackinlay** [comment]
Now that I know it's Linux VS code with emoji,  at least I'll be able to test some alternative distros tomorrow in the office.

Anyway, I'm having trouble getting the crash report working. For now, I'll confirm  I'm getting the `SIGSEGV` reported in a function `leftcommonsubstring` somewhere in the hunspell adapter.

I also get a spellright hanging a few times; the CPU profiles from that I DO have, in `/tmp/exthost-*.cpuprofile`, but that's presumably a different issue.

**Comment by howthebodyworks** [comment]
This is @danmackinlay on my work github account.

The problem also arises on Kubuntu 16.04. Here are some screenshot error logs from apport (which I should work out how to export).

![image](https://user-images.githubusercontent.com/18180368/61501553-26965e00-aa13-11e9-80e9-c58cde12052d.png)
![image](https://user-images.githubusercontent.com/18180368/61501577-2d24d580-aa13-11e9-8ee5-6f6d2fc734d2.png)

Once again, triggered only by documents with emoji. (On Kubuntu, support for these is even worse)

![image](https://user-images.githubusercontent.com/18180368/61501626-63faeb80-aa13-11e9-9375-75163916e5bf.png)

**Comment by jacksteamdev** [comment]
For me, these emojis: 🧐, 🤩

About:
```
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-20-generic
```

**Comment by jgehrcke** [comment]
@bartosz-antosik do you plan to debug and address this?

**Comment by laymonage** [comment]
For me, the :eu: emoji causes this (as well as the emojis mentioned above). It would be really nice if this is solved.

**Comment by thetooth** [comment]
I am in the middle of writing an extremely important whitepaper in restructuredtext and need to use the 🤔 emoji but am encountering this issue. Has there been any progress with this? It also happens that the rst extension hooks the backspace key, and since everything crashes together, I am unable to remove the offending glyph without using another editor. The professor will be furious if I turn this in late again.

**Comment by brunetton** [comment]
Same here. It took me some time to understand that 🤔 emoji caused a crash of the extension
