### ISSUE TITLE
Wrong suggestions not consulting a whole word

### ISSUE THREAD

**Issue by curiome** [bartosz-antosik/vscode-spellright#285]
Some correct words are reported wrong by highlighting partially.
![Capture](https://user-images.githubusercontent.com/50870507/58092022-15f37400-7b99-11e9-8342-bdf3af540761.PNG)

**Comment by bartosz-antosik** [comment]
Hi! Could you please tell me the OS & maybe what dictionary you use?

**Comment by curiome** [comment]
I am using windows 10 with default API. It used to work just fine, but it started doing this recently.

**Comment by curiome** [comment]
![Annotation 2019-05-22 044224](https://user-images.githubusercontent.com/50870507/58160292-287ab580-7c4c-11e9-8f8f-033aab3d02d5.png)
It seems most words with 'in' in it has similar issues.

**Comment by curiome** [comment]
Oops, my bad. I had ignoreRegExps in my settings.json.

**Comment by bartosz-antosik** [comment]
Hi! Thanks for the update. I was going to ask about the regexps once I get on solid ground from the traffic but you were quicker!
