### ISSUE TITLE
Spell Right v3.0.38 not working with OSS Code v1.34.0 on Manjaro

### ISSUE THREAD

**Issue by andreibica** [bartosz-antosik/vscode-spellright#286]
I've installed Spell Right extension v3.0.38 with the following OSS Code:

```
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-21T12:30:20.933Z
Electron: 4.1.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.30-electron.0
OS: Linux x64 4.20.17-1-MANJARO

```
and it doesn't work:
* no eye icon is displayed in the status bar
* trying to run any spellright.* commands displays an error: "command `spellright.*` not found"

It used to work on my system a few months ago, but with different versions.

**Comment by stakaz** [comment]
I think the problem is the same as in #269 and has to do with the electron version. I have recently updated my arch linux after a while and the extension stopped working.

As far as I understand the master branch has the fix but you cannot install it through code extensions for now. Would be great if it the update would come soon.

**Comment by andreibica** [comment]
Ok, thanks, then I will wait for the fix to be available.

**Comment by sbuschjaeger** [comment]
I struggle with the same problem (similar setup with Arch-Linux). According to #269 the Linux version should be available for roughly 6 weeks now (...?). Is there any update on this? I tried `npm install` inside the after `git clone`  (as suggest in the last comment of #269), but it failed with some error. Is there an official guider/readme on how to built the extension?

**Comment by bartosz-antosik** [comment]
Hello thread! The recently uploaded version 3.0.46 should work with Electron 4.x. Please let me know in this thread if it does not or there are any issues. Thank you for your patience and sorry it has to wait - I am somehow busy recently.

**Comment by phwuil** [comment]
Thanks !! It works !

**Comment by andreibica** [comment]
Works for me as well. Thanks.
