### ISSUE TITLE
X64 VSCode is not supported?

### ISSUE THREAD

**Issue by istvans** [bartosz-antosik/vscode-spellright#29]
It did not work at all for C++ code. It did not even show up on the status bar. VSCode X64 version: 1.14.2. I'm using Windows 10 Enterprise Version 1703 OS Build 15063.483

**Comment by bartosz-antosik** [comment]
(Thank you for posting the issue here)

Spell Right uses node.js module which has binary dependencies (you can see more description [here](https://github.com/Microsoft/vscode/issues/20266)). It has been provided with dependencies for ia32 architecture, that is 32 bit Visual Studio Code. Would be far more simpler if VSCode team would agree to build the module along with the VSCode builds. Then the extension would work for all three platforms.

**Comment by bartosz-antosik** [comment]
Spell Right has been updated to version 1.0.28 which should work with x64 (and ia32) version of Visual Studio Code. Please give it a try!

**Comment by borekb** [comment]
I've got VSCode 1.14.2 32bit + Spell Right 1.0.28 but the status bar icons are not showing up and the spell checking is not available. I didn't change any configuration in the last few days and checking it manually, everything seems alright. 🤔

**Comment by istvans** [comment]
Same here. I use the same VSCode version but the 64bit one.

**Comment by benwolman** [comment]
Same problem, same version. 1.14.2 32bit, and Spell Right stopped working today.

**Comment by bartosz-antosik** [comment]
Terribly sorry guys. Was tested by me before release, must have missed something. As usually 'here it works fine in both 64 and 32 bit installations'. Investigating.

Do you observe maybe anything in the DEBUG CONSOLE/OUTPUT pane?

**Comment by borekb** [comment]
Output > Extensions is empty in my case.

Trying on another computer where 1.0.28 was already installed, I saw this:

![image](https://user-images.githubusercontent.com/101152/28559593-6811fcc2-7117-11e7-8e4d-22ba3c5a1d21.png)

I reloaded, the version is still 1.0.28 but now the status bar icon and spell checking is gone. Looks like the same version of extension was re-uploaded?

**Comment by bartosz-antosik** [comment]
No it was not. Not consciously at least. Could I please see your configuration (User)

**Comment by borekb** [comment]
There you go:

```json
{
    "spellright.language": "en",
    "spellright.documentTypes": [
        "markdown"
    ],
    "spellright.ignoreWords": [
        "my",
        "words"
    ]
}
```

**Comment by bartosz-antosik** [comment]
Gentlemen! I need some support here! I have done tests on two machines of mine, one has VSCode 64 other 32-bit build. Both have Spell Right updated automatically from the Market. I did tests on two virtual machines (W10, W7) with VSCode & Spell Right installed from scratch - both work. The change in recent version is radical, I agree, still rational & I see no straight reason for what you report.

**Comment by Eldaw** [comment]
Spell Right stopped working for me today as well. I'm using 32-bit VS Code.

**Comment by Eldaw** [comment]
1. I have a bin folder in both of the subfolders, win-ia32 and win-x64. In fact, after this extension stopped working on my laptop, I copied the entire ban.spellright-1.0.28 folder over from my desktop PC where the extension still works. But it still doesn't work on my laptop.

2. The only file called extension.js is in the 'src' folder. Is that the one that needs to be edited?

**Comment by bartosz-antosik** [comment]
Thank you!

Ad. 1. It's somehow good info, that there are situations where it does and where it does not work. Maybe we could pinpoint the difference. What are windows versions/builds on these two machines?

Ad. 2. Yes, exactly. Please.

**Comment by borekb** [comment]
@bartosz-antosik 

1. Yes, the bin directory exists and contains both win-ia32 and win-x64 folders. What was strange is that I also had `ban-spellright-1.0.27` in the `extensions` folder: other extensions only have a single folder there. So I deleted it manually but it had no effect.

2. I turned the flag on but the output console is empty after reloading the VSCode window.

**Comment by bartosz-antosik** [comment]
Thank you!

Ad. 1. Folder `ban.spellright-1.0.27` is deleted by VSCode on restart (but I think not necessarily on reload). It is the way it rotates extensions.

Ad. 2. Strange again but also some information.

**Comment by Eldaw** [comment]
1. Both my laptop and desktop are running Windows 10 Pro x64.
2. I've enabled the debug output but I also see nothing in the debug console after starting VS Code.

**Comment by bartosz-antosik** [comment]
Could any of you gentlemen please download this VSIX version of the extension and install it on machine that is not working (Extensions view ->? three dots menu -> `Install from VSIX`)?

https://drive.google.com/open?id=0B9u6OGMG7xHcRm5KamFiYkhlWUk

**Comment by Eldaw** [comment]
OK, I've installed it. But Spell Right still does not load.

**Comment by bartosz-antosik** [comment]
Thank you. I am again clueless.

**Comment by borekb** [comment]
Is there some cache that could be cleared?

**Comment by bartosz-antosik** [comment]
None that I can think of.

**Comment by Eldaw** [comment]
@bartosz-antosik Well I guess step 1 will be getting your debug logging working. Is that working for you?

**Comment by borekb** [comment]
Is there a way to tell if this extension is loaded at all? Like a quick console.log() in extension.js? (I've never done VSCode extension development.)

**Comment by bartosz-antosik** [comment]
Many thanks for cooperation!

Trouble is  that even if something gets pushed out to console before this `(...) = require(...)` block it gets printed after these blocks get initialized and it looks like the problem is with choosing the right bindings (lib/spellchecker.js) in some situations. So please just few more moments for my investigation.

**Comment by bartosz-antosik** [comment]
Once again, kind request to download VSIX & install it manually (as explained few posts above):

https://drive.google.com/open?id=0B9u6OGMG7xHcUldPcnp1S2dIdjQ

**Comment by borekb** [comment]
No change. I also tried removing all my custom spellright settings from user settings.json, no difference.

**Comment by Moberstein** [comment]
Had the same problem, I cloned this repository and debugged the extension and got an error "Unexpected token in JSON" by parsing the user settings. Removing the comment that was on top of that file (=> that's not valid JSON) worked for me, the extension is running again!

**Comment by bartosz-antosik** [comment]
Dear Lord! Thank you! Now it seems very clear what's wrong.

**Comment by istvans** [comment]
Oh my!  :D I will check it this afternoon. Thank you guys for your efforts!

**Comment by bartosz-antosik** [comment]
Again, hope this is last iteration, if anyone who had the problems could please download and install:

https://drive.google.com/open?id=0B9u6OGMG7xHcUHRUTVBYN1NrV28

**Comment by borekb** [comment]
🎉 

![image](https://user-images.githubusercontent.com/101152/28573945-a6912862-714c-11e7-912f-648687376514.png)

**Comment by bartosz-antosik** [comment]
Lovely. Excuse me please everyone as it is me who has introduced this regression!

It has been reverted & corrected so that you COULD have comments in JSONs again. 64 bit version SHOULD be working as was the intention of the whole update.

Enormous thanks everyone for cooperation!

**Comment by borekb** [comment]
If I installed the VSIX version of the extension, will auto-update bring be back to the main release channel or do I need to uninstall it manually? Thanks.

**Comment by bartosz-antosik** [comment]
Yes, It will. In seconds actually. That's exactly what I did.

**Comment by istvans** [comment]
Fantastic job guys! I can barely wait to try it out tonight!

**Comment by Eldaw** [comment]
Fix confirmed. Out of interest, why did the problem only affect some computers while others worked fine?

**Comment by bartosz-antosik** [comment]
That's simple: Not everyone has comments in User Settings! 

I have no idea whether these comments were added by users or extensions but they were there preventing settings to be loaded.

**Comment by Eldaw** [comment]
Hmm. Comments in settings.json ?  That file is identical on both of my computers. Yet only my laptop had the problem.

Here is the full contents of my settings.json file from my laptop:

```
{
    "C_Cpp.intelliSenseEngine": "Default",
    "editor.renderControlCharacters": true,
    "editor.renderWhitespace": "boundary",
    "editor.wordWrap": "on",
    "extensions.ignoreRecommendations": true,
    "files.autoGuessEncoding": true,
    "files.trimTrailingWhitespace": true,
    "spellright.documentTypes": [],
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
    "window.menuBarVisibility": "default",
    "window.newWindowDimensions": "inherit",
    "window.zoomLevel": 0,
    "workbench.activityBar.visible": false,
    "workbench.sideBar.location": "left",
    "workbench.startupEditor": "none"
}
```

**Comment by borekb** [comment]
JSON for configuration is the curse of our industry :)

**Comment by bartosz-antosik** [comment]
Ok, You are right I was taking shortcut: One of the JSONs you have is not a valid JSON. There are more than comments that can make them invalid for `JSON.parse(...)` method. It was considered invalid because I have not `minified` them before parsing which is common way to make a JSON valid.

**Comment by Eldaw** [comment]
Weird. Well I guess it will remain a mystery why one computer worked and one did not, even though they both have identical settings.json files.

**Comment by bartosz-antosik** [comment]
And that's probably it.

What I was thinking about, starting from mentioning comments is:

https://www.npmjs.com/package/jsonminify

Before the fix `jsonMinify` operation was not done on the file (apart comments it corrects white spaces which CRLF/LF difference may be considered to be) after it is done back. `jsonMinify` has thrown an exception in the case of an empty file which I have not spotted until I have done some tests on a fresh installation which was a motivation for the "side" fix.

Once again: Thanks everyone!

**Comment by benwolman** [comment]
Thanks for your work in resolving the issue! Best spell checker for VSCode!

**Comment by bartosz-antosik** [comment]
At your service & thank you!
