### ISSUE TITLE
Command "spellright.* not found

### ISSUE THREAD

**Issue by openscript** [bartosz-antosik/vscode-spellright#290]
I'm trying to run this plugin on the following environment:

Version: 1.35.0
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-05T22:12:50.056Z
Electron: 4.1.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.30-electron.0
OS: Linux x64 5.1.7-arch1-1-ARCH

None of the plugin specific commands work:
![image](https://user-images.githubusercontent.com/1105080/59152005-a6a4cd80-8a3c-11e9-99da-ed1427dd7473.png)

Any ideas to go forward from here? Thank you in advance! :)

**Comment by bartosz-antosik** [comment]
Hello! The problem is that you are using version (what version) of VSCode with Electron 4.1.4. Currently the extension does not have binaries for version 4. I will try to update this soon.
