### ISSUE TITLE
Switch to Hunspell on Windows10

### ISSUE THREAD

**Issue by webmaster442** [bartosz-antosik/vscode-spellright#293]
Hello.

I have a question. Is there an option to use Hunspell dictionaries instead of windows dictionaries?

I'm writing a lot of documentation in md format using vs, and the Hungarian Windows dictionaries suck, to say the least.

**Comment by bartosz-antosik** [comment]
Yes, of course there is. Set environmental variable: SPELLCHECKER_PREFER_HUNSPELL to e.g. 1. Then you haev to provide dictionaries the way that it is described for Windows 7 in README document.

**Comment by RagibHasin** [comment]
Sorry for bringing up this long-resolved issue, but could this option be made into an extension setting? Then it would be easier to configure and discover.
