### ISSUE TITLE
After upgrading VSC every command fails

### ISSUE THREAD

**Issue by crystalfp** [bartosz-antosik/vscode-spellright#295]
I'm not sure this problem is related to the recent VSC update to 1.36 (Window), but Spell right does not work anymore (on markdown files) and any command gives an error. For example, selecting "SpellRight: Select Dictionary" results in a popup saying: "command 'spellright.selectDictionary' not found". Apparently there is no error in the various log. Any idea?
Thanks!
mario

**Comment by crystalfp** [comment]
The problem seems related to #279

**Comment by bartosz-antosik** [comment]
Yes, I am sorry from yesterday when I have noticed Electron change I am trying to upgrade the extension but MS tool for upgrading fails utterly. I have no idea why till now. I will keep on trying.

**Comment by bartosz-antosik** [comment]
It should be ok in version 3.0.44. Please confirm.

**Comment by crystalfp** [comment]
Yes! It works. Thanks for your efforts! mario
