### ISSUE TITLE
I can't get it to work with Code Remote WSL (ubuntu)

### ISSUE THREAD

**Issue by SteveALee** [bartosz-antosik/vscode-spellright#297]
Issue Type: <b>Bug</b>

I've installed the extensions and required hunspell dictionaries on WSL side but there seems to be no way to get it to work and allow me to select the . Also the links in the extension settings open local sttings not WSL. I'm not sure what should be happening - might ned some work to get it to work in the client / server setup?

Extension version: 3.0.46
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18950
Remote OS version: Linux x64 4.19.57-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.57-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2207)|
|Memory (System)|14.58GB (13.75GB free)|
|VM|0%|
</details>

**Comment by bartosz-antosik** [comment]
Hi! It's known problem. It is because spell right uses binary dependencies. There is a hope and an idea on how to resolve this, but I am very short on time recently. I will try to make the transition.

**Comment by SteveALee** [comment]
Ok, thank you for responding so quickly! I find it to be a very useful extension otherwise.

**Comment by gaurav-nelson** [comment]
PS: https://github.com/bartosz-antosik/vscode-spellright/issues/279
Looks like a duplicate. Please feel free to close this issue.
