### ISSUE TITLE
Manual install

### ISSUE THREAD

**Issue by netheril96** [bartosz-antosik/vscode-spellright#3]
I want to try out this extension, but it current says

> This extension is currently limited to 64-bit Windows platform. It is due to problems with distribution of native modules in current VSCode's distribution model. For details see (and up-vote maybe) discussion about VSCode's feature request #20266.

I briefly read the issue and understand that you cannot provide an easy way to install on macOS for now. But is there any manual way? Can I build node-spellchecker myself and install it somehow? Any instructions?

**Comment by bartosz-antosik** [comment]
Sorry, I do not have a clean guide on how to do this. It is deeply related to the way node.js & electron work (of which I do not know much). Below are the links to instructions I have followed:

https://github.com/Microsoft/vscode/issues/658

and, which is linked in the above:

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

My particular environment variables settings for the final build step were (it is for 64 bit Windows but VSCode's architecture is 32 bit):

```
set npm_config_disturl="https://atom.io/download/atom-shell"
set npm_config_target=1.4.6
set npm_config_arch="ia32"
set npm_config_runtime="electron"
set HOME=~\.electron-gyp

npm install spellchecker
```

Most important is the version of electron shipped with VSCode. I do not remember how did I get it but it works for VSCode's version 1.11.1 so it seems still valid.

Besides these instructions installation requires a valid C/C++ compiler tool-chain to be present in the path.

What the install step produces are `spellchecker.node` (which is in fact a platform specific Shared Object/Dynamically Linked Library) and `hunspell.lib` binaries. It should reside in module's build\Release folder.

Of course you should either install the module in node_modules sub-folder of the ban.spellright-$(VERSION) folder or the binary should be copied there.
