### ISSUE TITLE
Add support for Asciidoc files

### ISSUE THREAD

**Issue by insanetesterftw** [bartosz-antosik/vscode-spellright#30]
Currently SpellRight doesn't work on files with the extension *.asc, *.adoc, and *.asciidoc.

Asciidoc files are just text files. Asciidoc is a lightweight markup language similar to **markdown** but targeting longer documents like books.

http://asciidoctor.org/docs/asciidoc-recommended-practices/#document-extension

> AsciiDoc doesn’t care which extension you use. GitHub supports the extensions .asciidoc, .adoc and .asc.
>.adoc seems to be the most often used extension and the one we prefer. It does not conflict with other well known applications, is distinct, and not excessively long (like .asciidoc). It also reads as “a doc”. Our recommendation, therefore, is to use .adoc.

Thank you.

**Comment by bartosz-antosik** [comment]
Added in version 1.0.36. Please have a look, as I know not much about AsciiDoc, so fine-tuning may be required.
