### ISSUE TITLE
Strange spelling of <input> html element

### ISSUE THREAD

**Issue by crystalfp** [bartosz-antosik/vscode-spellright#309]
Spelling a html file, `spellright` correctly ignores tags, except the initial `i` of an `<input />` element and only in the attached file. Here is the warning:
![image](https://user-images.githubusercontent.com/865866/65141225-7b088a80-da10-11e9-8f8a-e971fecf45c5.png)
You can remove the `data-bind` attribute and the error remains. Also, there is no hidden character after the i.

[kb.html (change extension from txt)](https://github.com/bartosz-antosik/vscode-spellright/files/3625893/kb.txt)

Thanks for looking!
mario

**Comment by crystalfp** [comment]
Forgot: I'm on windows 10 64 bits using latest version of spellright.

**Comment by bartosz-antosik** [comment]
Hi! Thanks for reporting the issue. Should be fixed in just released 3.0.48.
