### ISSUE TITLE
only comment need a spell check

### ISSUE THREAD

**Issue by zzzgit** [bartosz-antosik/vscode-spellright#31]
hello, is there a way to config this plugin to perform only in comment, but not in code?

**Comment by bartosz-antosik** [comment]
Could you please be more specific? The extension is not supposed to spell check code ever. In case of most programming languages it should spell comments & strings, nothing more. Could you tell me what behavior you experience and what would you expect?

**Comment by bartosz-antosik** [comment]
If you could describe the problem in more details the issue will be reopened.
