### ISSUE TITLE
Every word marked as misspelled

### ISSUE THREAD

**Issue by chisomiloks** [bartosz-antosik/vscode-spellright#312]
Followed every instruction for linux and selected the right dictionary. Still shows every word as misspelled.

**Comment by bartosz-antosik** [comment]
Hi! Could you cross-reference your issue with thread #264 & #162?

**Comment by chisomiloks** [comment]
Thanks for the quick response. My problem was similar and the solution was a combination of both. Thanks for creating this useful extension.
