### ISSUE TITLE
elseif in comments is marked incorrect in PowerShell

### ISSUE THREAD

**Issue by DarkLite1** [bartosz-antosik/vscode-spellright#315]
This `PowerShell` code is correct and accepted by `Spell Right`:
```powershell
if ($Fruit) {
    'Frutis it is'
}
elseif ($Vegetables) {
    'Veggies for all'
}
```
This `PowerShell` code is marked as incorrect by `Spell Right` although it is correct:
```powershell
if ($Fruit) {
    'Frutis it is'
}
# elseif ($Vegetables) {
#     'Veggies for all'
# }
```
Suggestion by `Spell Right`:

> "elseif": suggestions: else if

Would it be possible to have `Spell Right` apply the same logic as when the code is not commented out? In any case, this should not be marked as incorrect because the `PowerShell` syntax is correct.

**Comment by bartosz-antosik** [comment]
Hi! Sadly, this is actually expected behavior! This is spell checker, not a syntax checker and it is supposed to spell comments and quoted strings within scripts. So from its point of view something like "elseif" is spelled incorrectly. You can use various means to stop Spell Right from reporting this as misspelled word, but I am unable to supply it with keywords from various languages.

**Comment by DarkLite1** [comment]
Then I'm wondering why it's not reporting the sting `#region` as incorrect? The concatenation of the character with the word is also an non existing word. That's why I thought there was syntax support in `Spell right`.

PowerShell also uses the word `DynamicParam` which is also not a normal word. This does not seem to trigger the incorrect message from `Spell Right` either. The same goes for CmdLets like `Write-Verbose`, so there is somewhere knowledge within `Spell Right` that it is analyzing `PowerShell` code.

Or am I totally mistaken?

**Comment by DarkLite1** [comment]
Thank you for the clarification. IMHO there should be knowledge in the spell checked about the language it is checking. But indeed, maybe that's something that might be supported in another spell checker. I'll have a look, thanks for the help anyhow.
