### ISSUE TITLE
spellchecker.json vs. user settings.json

### ISSUE THREAD

**Issue by borekb** [bartosz-antosik/vscode-spellright#32]
I've got a question. On my PC, I seem to have custom ignore words in two files:

- `spellchecker.json`
- `settings.json` (also in the `../Code/User` directory)

When I do *Add "customword" to global ignore list*, it seems to be added to my user `settings.json`. How does the `spellchecker.json` file work? Is there a way to add my custom words there? I would prefer that as I synchronize my user `settings.json` between two computers and custom words create a lot of noise and possible merge conflicts there. Thanks.

**Comment by bartosz-antosik** [comment]
The idea was simple: There are two storages for ignored (or spelled correctly) words: global (user) and project local (workspace). Workspace setting, if exists, overrides the global (user) dictionary. So if you push everything to Workspace dictionary it will not be global but it will not reside in settings.json.

This is going to change in relation to #28 very soon.

**Comment by borekb** [comment]
I generally don't want to keep custom words in the workspace settings so I never used the *Add word to workspace ignore list* but that is actually a third location. So on my PC, custom words are actually in these three places:

- `..Code/User/settings.json`
- `..Code/User/spellchecker.json`
- `.vscode/spellright.json`

Looking forward to what you come up with in #28 :)

**Comment by bartosz-antosik** [comment]
The file `spellchecker.json` is not mine! Or not intentionally mine! Can you show me it's contents?

**Comment by borekb** [comment]
Ah I didn't realize it's not yours :) Sorry.

**Comment by bartosz-antosik** [comment]
As you can see me too for quite some days! ;-)

My words above were correct just I store in `settings.json` and `spellright.json` in user/workspace areas accordingly.
