### ISSUE TITLE
With Hunspell no errors are found

### ISSUE THREAD

**Issue by gabbersepp** [bartosz-antosik/vscode-spellright#330]
Hi,
I installed the extension on my Surface and it works for EN-US. Then I installed it on my laptop (Win10 Home, 64Bit) and there it did not work.
I activated debug output as mentioned here: https://github.com/bartosz-antosik/vscode-spellright/issues/53#issuecomment-323970244

It tells me,that only german dictionaries are added. Thus I set "this.hunspell" hard to "true" in the `spellright.js` file. After a restart of VScode I am able to select EN-US (downloaded and put the dictionary into `C:\Users\Benutzer1\AppData\Roaming\Code\Dictionaries` folder)

Now the console displays the EN-US dictionary. But now the console shows this message:

```
[Extension Host] [spellright] Spelling of "c:\Users\Benutzer1\git\dev.to-posts\blog-posts\eleventy-static-page\eleventy-static-page.md" [markdown] COMPLETED in 0.059s, 0 errors.
```

Would be nice if you can point me into the right direction.

**Comment by gabbersepp** [comment]
> Hi! Could you please ensure that the dictionary is UTF-8? The details are described more or less in README.md.
Hi yes I have read it. :) I tried one from the page you mentioned in the Readme and one from another page. It also stated that the files are in utf8. But I can check it for myself to be sure.

**Comment by gabbersepp** [comment]
I have following files:
![image](https://user-images.githubusercontent.com/3234900/72026791-11d9ab00-327d-11ea-9c1c-8f3d085c9986.png)

Both, the `.div` and the `.aff` file are in UTF8 if we can trust Notepad++

I don't know if this is intended, but for every key I press i get following console output:
![image](https://user-images.githubusercontent.com/3234900/72026887-60874500-327d-11ea-9538-c22892dd3de9.png)

**Comment by gabbersepp** [comment]
It seems that my laptop at work shows the same behaviour. 
What requirements must be fullfilled by my windows installation to ensure that your extension provides spell correction out of the box? Do I have to install some dictionaries in windows directly? Maybe my surface has something internal activated that my laptops do not have

**Comment by bartosz-antosik** [comment]
There are two separated issues, if I understand things correctly:

1) HUNSPELL dictionaries

This is not only important whether the file IS UTF-8. It also has to have the `SET UTF-8` in `.aff` file:

![utf-8](https://user-images.githubusercontent.com/20492548/72055278-d8c82780-32ca-11ea-8de8-0f521e95b5f0.png)

![iso8859-1](https://user-images.githubusercontent.com/20492548/72055286-db2a8180-32ca-11ea-84a7-9eb69b576b96.png)

Please maybe check these!

2) Windows dictionaries

There is a mysterious problem with Windows. Please first have a look at "Known Issues", last paragraph, especially pointed out comments.

**Comment by gabbersepp** [comment]
Thanks! A comment in the linked issues pointed me into the right direction. My english language pack was corrupt. I reinstalled it and now it works! Thanks for your great work!

**Comment by bartosz-antosik** [comment]
That is a great news!
