### ISSUE TITLE
No spell check happening

### ISSUE THREAD

**Issue by Timothep** [bartosz-antosik/vscode-spellright#331]
Hi, I just installed the extension. After installing, it highlighted my whole file once but was apparently using German language when I wanted English. I hit F1 to change the language and accidentally clicked on "SpellRight: Configuration Update" which turned the checking apparently OFF.

In the taskbar I can see the "eye" and select English and/or German. The tooltip says "- ON". But whatever I type, I cannot get a spelling error to be displayed.

Any idea what I am missing? Thanks a lot!

**Comment by bartosz-antosik** [comment]
Hi! Could you please start from having a look at this thread: #330?

**Comment by Timothep** [comment]
Oh boy, my bad, the English language package wasn't installed on my Win10 Machine yet. Sorry about that!
