### ISSUE TITLE
spellright stopped working

### ISSUE THREAD

**Issue by ergl** [bartosz-antosik/vscode-spellright#334]
Hi! It seems the extension stopped working with the new vscode update, every command I try results in an error message like `command 'spellright.<command>' not found`

macOS Mojave 10.14.6
Visual Studio Code:
Version: 1.42.0-insider
Commit: 68615717819b3731705d92ec06b52edd47665291
Date: 2020-01-22T05:26:38.760Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by bartosz-antosik** [comment]
Hi! It is because binary dependencies required updating. Should be fine with just released version 3.0.50.

**Comment by ergl** [comment]
Thanks! It works perfectly now
