### ISSUE TITLE
Spell check of ordinal numbers

### ISSUE THREAD

**Issue by timfelle** [bartosz-antosik/vscode-spellright#341]
Hello, it would seem the extension flags out ordinal numbers as being an error in the English (British) system.
Ordinals: 1st, 2nd, 3rd, 4th and so on.

**Comment by olivercrask** [comment]
Anyone know of a settings entry to account for this rather than adding st, nd, rd, th as words?

**Comment by martincook3** [comment]
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.17763

---

`"spellright.groupDictionaries": false`,
`"spellright.language": [ "en-GB" ]`,

---

My experience is slightly different:

>1st 2nd 3rd 

are OK but
> (1st (2nd (3rd

are each flagged as an error.
