### ISSUE TITLE
Some math expressions are spelled in LaTeX whereas they should not be

### ISSUE THREAD

**Issue by bartosz-antosik** [bartosz-antosik/vscode-spellright#35]
James Yu suggested in one of comments to issue [#225](https://github.com/James-Yu/LaTeX-Workshop/issues/225#issuecomment-320389342) that Spell Right spells math expressions like:

```
\forall(i,j)\notin\mathcal{E}
```

where i gets underlined as spelled incorrectly (suggesting capital). 

They should not be spelled.

**Comment by bartosz-antosik** [comment]
Correct me if I am wrong, but it seems to me that this expression would get spelled only outside of math braces (`$` and `$` etc.), where it should not exist in this form. I assumed that only `\command{...}...` and `\command[..]...` should not be spelled in normal document context and nothing inside math braces.

**Comment by James-Yu** [comment]
In fact, in LaTeX it is very common to have math equations in the following form:
```
\begin{align}
\some_{equations}^{here}
\end{align}
```
The snippet I provided was also surrounded by the environment. The way cSpell handles this problem is simply ignore any words with three or less letters, which I found to be surprisingly effective and not causing many false negatives. Just for your reference.

**Comment by bartosz-antosik** [comment]
You are right. The expression will be eliminated by modified regexp. Next release will have it.

About spelling starting from some length of the word, e.g. 4 characters. I am very strong against about spelling starting from some length! This was in fact my objection against most of the spell checkers I have examined before starting mine on the beginning of this year. It makes impossible to spell a lot of short words, shortcuts and abbreviations (I'm, etc., i.e. etc., etc.) As I was stressing my intention was to produce a precise speller thus a lot of tweaking in the parsers. Like the thread above...
