### ISSUE TITLE
Linking Hunspell directories from system installed directory won't populate language files

### ISSUE THREAD

**Issue by jonnisell** [bartosz-antosik/vscode-spellright#357]
Documentation suggestion:
In the **Dictionaries** section of the README there's an instruction for linking the system installed Hunspell directories to the user's config folder. This won't populate the _~/.config/Code/Directories_ with the files, but please add the following change and it will:
`ln -s /usr/share/hunspell/* ~/.config/Code/Dictionaries`
Then restart VS Code

This worked for:
VS code version  1.44.0
Fedora 31 ( with Hunspell installed in _/usr/share/myspell_ )

p.s. Just started using this extension, but seems great. Thanks

**Comment by bartosz-antosik** [comment]
Hi! Thanks for the update. I will include it in the README. It was hard to notice the difference at first! ;-)
