### ISSUE TITLE
Feature Request: Command to add word to dictionary

### ISSUE THREAD

**Issue by ZaymonFC** [bartosz-antosik/vscode-spellright#36]
This is a great plugin but one thing that is bugging me is not having the ability to add a selected word to the dictionary with a command.

**Comment by ZaymonFC** [comment]
Alas I should have researched further and discovered the context menu with ctrl+. Thanks for your work!

**Comment by bartosz-antosik** [comment]
Thanks for auto closing issue! ;-)
