### ISSUE TITLE
Turn Spell Checking Back On For Current Document

### ISSUE THREAD

**Issue by jhomme** [bartosz-antosik/vscode-spellright#360]
Hi. This could be user error on my part. I have a Markdown document that I only wanted to check Markdown for, so I turned off spell check.  I cannot figure out how to turn spell check back on for this document.

Thanks.

**Comment by IntiGabriel** [comment]
Did you figure it out?
In the lower right there is a small eye (captioned with`[off]`)where you can click on. You can then select the language and enable spell checking again.
![image](https://user-images.githubusercontent.com/7985324/91957224-094f4c80-ed06-11ea-90d7-297e19a06244.png)
