### ISSUE TITLE
Where is the system dictionary?

### ISSUE THREAD

**Issue by K4rl-M4rx** [bartosz-antosik/vscode-spellright#369]
I accidentally set "spellright.addToSystemDictionary": true. 
And I added wrong words in it.

**Comment by K4rl-M4rx** [comment]
It's okay to just leave it. But it keeps bugging me.

**Comment by bartosz-antosik** [comment]
Hello Karl Marx! Do I understand correctly that you ask, where lands word added to system dictionary?

**Comment by K4rl-M4rx** [comment]
> Hello Karl Marx! Do I understand correctly that you ask, where lands word added to system dictionary?

Yes. I’m a Win10 user. It would be great helpful to me if you know where the dictionary is, thanks in advance!

**Comment by bartosz-antosik** [comment]
%APPDATA%\Microsoft\Spelling

**Comment by K4rl-M4rx** [comment]
> %APPDATA%\Microsoft\Spelling

I found it. Thanks again!
