### ISSUE TITLE
Turning off SpellRight leaves it stuck in enabled mode in other Editors

### ISSUE THREAD

**Issue by Eldaw** [bartosz-antosik/vscode-spellright#37]
With SpellRight configured to not check any document types by default, try the following:

1. Open a new instance of VS Code with no documents open.
2. Hit Ctrl + N to start a new text file.
3. Type some random/nonsense words.
4. Hit Ctrl + N to open a second editor/tab.
5. In the second file, type some random/nonsense words.
6. While still in the second file, enable SpellRight from the status bar and notice that the words get underlined in red.
7. Switch to the first file in the first tab. Notice that the words there get underlined in red too. So far so good.
8. Switch back to the second file.
9. Turn off SpellRight from the status bar (i.e. turn off for document type [plaintext])
10. Go back to the first file, where the words are still underlined in red. Notice that according to the status bar, SpellRight is supposedly disabled.

**Comment by bartosz-antosik** [comment]
Should be fixed in 1.1.4.
