### ISSUE TITLE
I've installed the extension and can't figure out how to turn it on

### ISSUE THREAD

**Issue by gigihanna10x** [bartosz-antosik/vscode-spellright#383]
Is there some way to turn it on/off using the UI?

**Comment by gigihanna10x** [comment]
It seems like it's installed and enabled, but it's not highlighting any spelling errors in text/markdown. Feel like I'm missing a step to get it to work.

**Comment by bartosz-antosik** [comment]
Hello! Basically there should be an "eye" symbol towards the right end of the status bar, sth. like this:

![image](https://user-images.githubusercontent.com/20492548/93778360-189b2900-fc26-11ea-90ba-61d7e80bc6ed.png)

When you click it you should see list of available dictionaries.

**Comment by gigihanna10x** [comment]
Thanks! I'd given up and uninstalled this extension, and installed Sublime instead, which has a built-in spell checker. If I go back to VS Code, I'll try reinstalling this extension again. :-)
