### ISSUE TITLE
Extensions fails to load when there's a trailing comma in settings.json

### ISSUE THREAD

**Issue by DamianPereira** [bartosz-antosik/vscode-spellright#39]
Trying to execute select dictionary with a trailing comma in settings.json leads to a popup error that says:

    command 'spellright.selectDictionary' not found

Developer tools's console outputs this error:

    Activating extension `ban.spellright` failed: Cannot read property 'spellright.ignoreWords' of null.

I only realized I had a trailing comma when adding some console.logs in the extension src files. The problem is the JSON.parse in line 1384 of spellright.js. It fails when parsing settings.json, returns null as the value and leads to the reading ignoreWords of null error above.

I see 2 solutions:

1. Add better error on getUserSettings(), so that the user is notified the settings.json file has bad syntax, and can realize why the extension is not loading.
2. Ignore the trailing comma. Other extensions seem to use vscode.workspace.getConfiguration('extension'), instead of reading the file manually and parsing it (internally VScode parser seems to ignore trailing commas). Maybe the code can be modified for this?

Which would be the better option? I could make a PR if it would help.

**Comment by bartosz-antosik** [comment]
Thanks for in-depth analysis. This is really helpful. It should be resolved soon, I think going along second option. I am not the master of VSCode and parts of the code are bit of legacy. This part in particular is.

**Comment by bartosz-antosik** [comment]
Should be fixed in version 1.1.10
