### ISSUE TITLE
Specify what to spell-check

### ISSUE THREAD

**Issue by borekb** [bartosz-antosik/vscode-spellright#40]
If I enable Spell Right for TypeScript and other code files, it seems to spell-check comments and strings. Strings are usually technical stuff I don't want to spell check, for example, ES6 imports like `import { env } from '../Dotenv'`. I'd like only comments spell-checked in the code files.

I wonder if if the `documentTypes` could be enhanced like this:

```
"spellright.documentTypes": {
    "plaintext": true,
    "markdown": true,
    "typescript": "comments-only",
    "javascript": "comments-only"
}
```

**Comment by bartosz-antosik** [comment]
The configuration syntax you propose is hard to deploy. Let me think about it for a moment.

**Comment by bartosz-antosik** [comment]
Just to let you know, I have ready the back end for this functionality. Still thinking about configuration.

**Comment by borekb** [comment]
Awesome. If you have multiple ideas, maybe you could post them here for early feedback? Looking forward to this!

**Comment by bartosz-antosik** [comment]
If I would have something solid I would love to bounce it off. I don't however.

**Comment by bartosz-antosik** [comment]
So finally I think of something like this:

Two settings in User/Workspace settings:

spellSectionsGlobal: "all", // "", "comments", "strings", "body", "all"
spellSectionsPerType: {}, // { "latex": "all", "cpp": "comments", [...] }

This would allow to set preference globally and point exceptions. It allows you to have some settings and modify it locally rather than have to point it for every document type.

**Comment by borekb** [comment]
Very nice, you've chosen a great approach IMO.

**Comment by bartosz-antosik** [comment]
This change has been published in 1.1.24. Please have a look and let me know if it is OK for you.

**Comment by borekb** [comment]
Great. I'm just trying it out and seems to work well e.g. for Markdown and HTML (in HTML, I've successfully disabled spell check in HTML comments, yay!) but I'm not sure if it's working in TypeScript:

My settings:

```
"spellright.spellSyntax": "body comment string",
"spellright.spellSyntaxByClass": {
    "markdown": "body",
    "typescript": "comment",
    "html": "body"
}
```

Spell check in `.ts` file seems to process string literals as well:

![image](https://user-images.githubusercontent.com/101152/29663319-b702fbf4-88ca-11e7-937d-507845b852d5.png)

BTW I probably preferred your previous settings names `spellSections..`, for example, I would find `spellSectionsPerDocumentType` more intuitive than `spellSyntaxByClass`.

**Comment by bartosz-antosik** [comment]
That's funny - when I get TypeScript text from the editor, internally from the extension's point of view, I get it embraced in quotes ("). This is what fools the lexical analyzer. So far cannot find why...

**Comment by bartosz-antosik** [comment]
I was wrong. It's mine. The problem is in other languages too.

**Comment by bartosz-antosik** [comment]
It's corrected. Will be included in next release.

Another matter: I did not finally liked "Section" because it is more like logical division of the document than syntactical. Also documents are grouped by class rather than types (many types can actually fall into single document type e.g. cpp is "*.cpp" & "*.hpp" etc. I will think of something.

Maybe `spellContext`? But it's also counterintuitive...

I also do not like "string comment" instead of "strings comments" which also is logical over intuitive. 

Devils wheel.

**Comment by borekb** [comment]
"There are only two hard things in computer science: cache invalidation and naming things" :) 

I actually like "context" or maybe "scope" ("context" is probably better). To be entirely honest, it still feels to me that this:

```json
"spellright.documentTypes": [
    "markdown",
    "typescript",
    "html"
],
"spellright.spellContexts": {
    "markdown": "body",
    "typescript": "comment",
    "html": "body"
},
```

could be merged into a single option like

```json
"spellright.documentTypes": {
    "markdown": "body",
    "typescript": "comment",
    "html": "body"
},
```

For document types that don't need customization, some special value like `default` or `on` could be used:

```json
"spellright.documentTypes": {
    "plaintext": "on",
    "markdown": "body",
    "typescript": "comment",
    "html": "body"
},
```

If someone doesn't customize at all, it would look like this:

```json
"spellright.documentTypes": {
    "plaintext": "on",
    "markdown": "on",
    "typescript": "on",
    "html": "on"
},
```

Not that bad, IMO. But I understand that this is always challenging, just posting some ideas here.

**Comment by bartosz-antosik** [comment]
I entirely agree that it would be better to have one setting, but it would crash with the semantics of the dropdown/list (list only switches ON/OFF but there would be more states). 

I decided this should be a side setting as 1) it would not be probably a mainstream setting 2) It seems more straightforward to only add classes and subtle things do elsewhere. But it's just my thinking.

I will go with `spellContext` etc. And with "comments", "strings". Next update. Thanks.

**Comment by bartosz-antosik** [comment]
In 1.1.25: changed to `Context`, changed to `strings`/`comments`. Strings you reported in TypeScript should switch correctly.
