### ISSUE TITLE
Comments are not spell-checked in .http files

### ISSUE THREAD

**Issue by borekb** [bartosz-antosik/vscode-spellright#41]
I use the [REST Client](https://github.com/Huachao/vscode-restclient) extension and their `.http` files. I have enabled Spell Right for it but the comments are not spell-checked:

![image](https://user-images.githubusercontent.com/101152/29249514-27c692d0-8031-11e7-9d2f-0a53677fb083.png)

Does this have something to do with the way they define their language? Is this a problem or their end or an issue in Spell Right? Thanks.

**Comment by bartosz-antosik** [comment]
Could you please post a sample .http/.rest file here? Would be helpful to test without need to discover everything.

**Comment by borekb** [comment]
Sure, sorry, for example this isn't spell-checked:

```
# Some comments here
# asdas asdasd ngvlkjfhgkjhg

GET https://google.com/
```

**Comment by bartosz-antosik** [comment]
Turns out HTTP document type is nothing native to VSCode but is brought by the extension you mention. Nevertheless support has been added. Please check it out in version 1.1.14.

**Comment by borekb** [comment]
Thank you!

I now also realize that languages are supported one by one: https://github.com/bartosz-antosik/vscode-spellright/commit/e1c59c817fc2e883861bb4d19bc04dc2c1ad43c2#diff-dc0cf9146a53528c69be70ee4bd946b7R83. I thought that the language itself provides some sort of information what is comments or strings in that language and that can be consumed automatically. But probably not.

**Comment by bartosz-antosik** [comment]
No, absolutely not!, it is not automatic! 

It is complained about in various places by various extension creators that there is no access to syntactic information of the languages supported. In my extension it is relatively easy to add language & e.g. create PR, see here:

https://github.com/bartosz-antosik/vscode-spellright/blob/master/lib/doctype.js

**Comment by borekb** [comment]
Very good to know, thanks!
