### ISSUE TITLE
Can't properly double click and copy suggestion.

### ISSUE THREAD

**Issue by mauhcs** [bartosz-antosik/vscode-spellright#413]
Issue:
When I have a word misspelled and I want to copy the correct for from the suggestions, double clicking in the correct word will select the correct word AND the word 'spelling.' See image:

<img width="470" alt="Screenshot 2021-02-27 at 19 21 36" src="https://user-images.githubusercontent.com/17294645/109384606-603e8300-7931-11eb-9c5b-547c2809c414.png">

The expected behaviour would be selecting only the suggested word, hence the flow to correct a misspelled word can be: 'hover over misspell -> double click on correct word -> copy/past'

I am using MacOs, editing a Latex file and have the version 3.0.56 of spellright.

**Comment by bartosz-antosik** [comment]
Hi! This is not a mechanism provided by the extension but by the VSCode itself. Extension only supplies the hint window with content. I suppose it acts identical in suggestions provided by other language tools? If so then I am pretty sure this should be reported as VSCode issue.
