### ISSUE TITLE
Allow add to user dict whole CamelCase word not only its parts

### ISSUE THREAD

**Issue by slodki** [bartosz-antosik/vscode-spellright#43]
When put cursor in CamelCase word and then add it to user dictionary only one part can be added even if this word is brand or trademark and should be added as a whole.

The same problem with snake_case and digit2inside words.

**Comment by bartosz-antosik** [comment]
Formally speaking there is a way! You can open the dictionary file and put the compound phrase there. It should be spelled as a whole correctly then.

I will think on adding some functionality to do this from within Spell Right.

**Comment by slodki** [comment]
I discovered your method when i checked what exactly is added to dictionary...

You generate 2 options in suggestion
- add word to user dict
- add word to workspace dict
Then you should add next two
- add whole CamelCase word to user dict
- add whole CamelCase word to workspace dict

**Comment by bartosz-antosik** [comment]
There are two new commands registered in recently released version 1.1.16: `SpellRight: Add Selection to Workspace Dictionary` and `SpellRight: Add Selection to User Dictionary` to do this kind of things. I would love to not to clutter the drop-down menu with additional options hence the solution proposed.
