### ISSUE TITLE
Parser fails when 1st letter is uppercase & 2nd letter has an accent

### ISSUE THREAD

**Issue by qchenevier** [bartosz-antosik/vscode-spellright#436]
Hello,

It seems that the plaintext & markdown parsers are having trouble when:

- first letter is uppercase
- second letter has an accent

In this case, the parser will remove the 1st letter of the word.

Examples:
```
Réflexion <-- parser misses the first letter: it gets only "éflexion"
réflexion <-- this is OK (first letter is not uppercase)
Préparation <-- this is OK (it's the third letter which has an accent)
Reflection <-- this is OK (obviously)
```

**Comment by qchenevier** [comment]
Actually, it wasn't due to the parser.

It's because I had misconfigured it with that option:
```
"spellright.ignoreRegExps": [ "/\\b[-_A-Z0-9]+\\b/g" ]
```

**Comment by bartosz-antosik** [comment]
Thank you for the explanations & sorry I have not had a moment to look into it.
