### ISSUE TITLE
Right suggestion for wrong CamelCase word part displayed

### ISSUE THREAD

**Issue by slodki** [bartosz-antosik/vscode-spellright#44]
The correct suggestion is displayed but for the wrong part.

#### Example 1:
all parts wrong, word with English dictionary: `MyyOvnCemalCiseWerd` (should be `MyOwnCamelCaseWord`):

*cursor position marked with _ char*

| cursor position | suggestion |
|---|---|
| _MyyOvnCemalCiseWerd | Own |
| My_yOvnCemalCiseWerd | Own |
| Myy_OvnCemalCiseWerd | Camel |
| MyyO_vnCemalCiseWerd | Camel |
| MyyOvn_CemalCiseWerd | Case |
| MyyOvnCem_alCiseWerd | Case |
| MyyOvnCemal_CiseWerd | Word |
| MyyOvnCemalCise_Werd | Word |
| MyyOvnCemalCiseWe_rd | Word |
| MyyOvnCemalCiseWerd_ | Word |

#### Example 2:
one part correct, word with English dictionary: `MyyOvnCamelCiseWerd` (should be `MyOwnCamelCaseWord`):

| cursor position | suggestion |
|---|---|
| _MyyOvnCamelCiseWerd | Own |
| My_yOvnCamelCiseWerd | Own |
| Myy_OvnCamelCiseWerd | **Own** |
| MyyO_vnCamelCiseWerd | **Own** |
| MyyOvn_CamelCiseWerd | **Own** |
| MyyOvnCam_elCiseWerd | **Own** |
| MyyOvnCamel_CiseWerd | Word |
| MyyOvnCamelCise_Werd | Word |
| MyyOvnCamelCiseWe_rd | Word |
| MyyOvnCamelCiseWerd_ | Word |

There is no way to display suggestion for the first part of CamelCase word.

Selected suggestion corrects right word `Cemal` -> `Camel` etc.

**Comment by bartosz-antosik** [comment]
Indeed. But the diagnostics are listed and highlighted properly.

**Comment by bartosz-antosik** [comment]
Should be corrected in version 1.1.12.
