### ISSUE TITLE
SpellRight suddenly stopped working

### ISSUE THREAD

**Issue by mashupmark** [bartosz-antosik/vscode-spellright#443]
The extension suddenly stopped working under Version v3.0.58.
I already tried restarting VS Code, uninstalling and reinstalling SpellRight as well as installing Version v3.0.56.
Running any command associated with SpellRight yields the following error:

![Bildschirmfoto 2021-08-09 um 10 47 26](https://user-images.githubusercontent.com/46753823/128680750-32fcf780-1795-4dbb-8b7b-80f8703968c1.png)

A quick look into devtools shows the following error message:

![Bildschirmfoto 2021-08-09 um 10 43 30](https://user-images.githubusercontent.com/46753823/128680835-79b84123-64ae-4164-b920-2a700393732d.png)

The error occured under VS Code 1.59.0 on macOS 10.14.5

**Comment by doitian** [comment]
Same here

- vscode 1.59.0
- SpellRight 3.0.58
- macOS 11.4 (20F71)

**Comment by klausj1** [comment]
Same here under Windows as well (also with SpellRight 3.0.58):

```
VSCode version:
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.18363
```

I think it is related to the July update of VSCode.

Any help would be greatly appreciated!

**Comment by bartosz-antosik** [comment]
Hello! I am pretty sure it is because Electron version has been updated. I will try to rebuild binary dependencies soon. Sorry for the inconvenience!

**Comment by klausj1** [comment]
Thanks a lot! Probably duplicate with #441.

BTW: Is there an easy way in VSCode to get notified if an extension could not be started? I did not see any notification of the problem (it just dit not work), and had to look into the error log of the extension host or the devtools manually.

**Comment by mashupmark** [comment]
The issue is fixed in version v.3.0.60
Thanks a lot for the quick help 👍

**Comment by Shamp0o** [comment]
I'm still getting this error under v.3.0.60.

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:38:17.605Z (1 mo ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0
```
