### ISSUE TITLE
Reuse system installed hunspell dictionaries

### ISSUE THREAD

**Issue by slodki** [bartosz-antosik/vscode-spellright#45]
>On Linux and Windows 7 Spell Right uses built in Hunspell spell checker library. To use it a pair of Dictionary (*.dic) and Affixes (*.aff) files have to be downloaded from here (please remember to download RAW files) and placed in `Dictionaries` subfolder of VSCode's user global configuration directory, located at:
>
> * Windows: `%APPDATA%\Code\Dictionaries\`
> * Linux: `$HOME/.config/Code/Dictionaries/`
>
> `Dictionaries` subfolder does not exists there by default and has to be created manually.

On Linux it was sufficient for me to symlink system-wide installed dictionaries:
```shell
ln -s /usr/share/hunspell ~/.config/Code/Dictionaries
```
All dictionaries are detected and working.

Please verify if this is correct solution (this dir is readonly for users on Linux) and update SpellRight documentation.

**Comment by bartosz-antosik** [comment]
Has been added in the version 1.1.14.

**Comment by Eido95** [comment]
I tried to use the command above, but still no system dictionaries are found by installed Spell Right extension.

I'm using Fedora 29 (Workstation Edition).

In Fedora 29, the directory `/usr/share/hunspell` is not existed.

@slodki on which Linux distribution did you successfully used system-wide installed directories? what is the structure of your `/usr/share/hunspell` directory?

**Comment by Eido95** [comment]
I figured this out.

On Fedora, the system dictionaries located under `myspell` folder instead of `hunspell`.

The command mentioned by @slodki worked for me when used it with `myspell` directory.

I PR-ed (#252) instructions for Fedora users.
