### ISSUE TITLE
Files with emoji crash the plugin

### ISSUE THREAD

**Issue by Michael-F-Bryan** [bartosz-antosik/vscode-spellright#450]
Issue Type: <b>Bug</b>

Opening a text file containing an emoji (e.g. 🤣) will crash the extension host.

To reproduce, just create a new file and open it in VS Code with this plugin enabled:

```shell
$ echo '🤣' > some_file.txt
$ code some_file.txt
```

Extension version: 3.0.60
VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:06:57.931Z)
OS version: Linux x64 5.14.5-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 3607)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.45GB (1.10GB free)|
|Process Argv|. --crash-reporter-id ae604bc8-e57b-4bda-8394-87b2db34c796|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgsc2:30361791
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by laymonage** [comment]
@Michael-F-Bryan unfortunately I'm just a fellow user and not a maintainer of this extension. I was just checking if the issue has been fixed :sweat_smile:

Maybe I could try debugging the extension and see if I can get anywhere, but I've never worked on VSCode extensions before, so the chances are pretty low. This extension also seems to use a native binding to a C/C++ library, so it's also possible the problem stems from there.
