### ISSUE TITLE
No "spellright.*" commands are found. macOS Big Sur

### ISSUE THREAD

**Issue by jpgoldberg** [bartosz-antosik/vscode-spellright#451]
Versions:
- Visual Studio Code: 1.60.2
    - Electron: 13.1.8
        - Chrome: 91.0.4472.164
        - Node.js: 14.16.0
        - V8: 9.1.269.39-electron.0
   - OS: Darwin arm64 20.6.0
- Spell Right: v3.0.60
- OS: macOS Big Sur 11.6

After installing Spell Right, I see no indication that it is active. There is no eye in the status bar, there is no misspelling detection, and for any Spell Right command I use from the command palette, such as "SpellRight: Select Dictionary (Language) I get

```
Command 'SpellRight: Select Dictionary (Language)' resulted in an error (command 'spellright.selectDictionary' not found)
```

I get similar results with any other SpellRight command.

If there are any log files that I should be looking at to help identify the problem, please let me know what those might be.

**Comment by piegamesde** [comment]
Can reproduce with VSCodium 1.59.1, extension v3.0.56 on Arch Linux.

**Comment by julienlavergne** [comment]
Same,

VSCode 1.61.0-insider
Spellright: 3.0.60
Linux redhat 7

**Comment by EddyLuten** [comment]
I'm confirming that I'm also seeing this issue for any SpellRight commands with the same setup as @jpgoldberg. The entire extension is currently unusable.

VS Code: 1.60.2
SpellRight: 3.0.60
MacOS: 11.6 Big Sur

However, on my Windows machine it works fine.

**Comment by nkuehn** [comment]
Looks somewhat similar or related to #426 , which is related to the bundled binary node-spellright extension not being compatible the node version VSCode is using internally.

**Comment by jpgoldberg** [comment]
In light of https://github.com/bartosz-antosik/vscode-spellright/issues/426 I have updated my description of the issue to include Electron version information along with platform architecture.

**Comment by jpgoldberg** [comment]
That has been fixed (for me) with builds from https://github.com/bartosz-antosik/vscode-spellright/pull/454 

See issue #426 for more discussion.
