### ISSUE TITLE
No spellchecking for files in virtual workspaces?

### ISSUE THREAD

**Issue by r08n** [bartosz-antosik/vscode-spellright#457]
Hello, I am using actual versions of VS Code (v1.61.1) together with Spell Right (v3.0.60). Spellchecking works perfect for files located on "normal" volumes (like local filesystem or mounted server shares)!

I also use [GitHub Repositories 0.16.0](https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub), that enables direct GitHub Access without the need to clone Git repositories locally (and is like Spell Right a little gem :relaxed:). As for my understanding GitHub Repositories leverage the VS Code feature of virtual workspaces (using virtual file system). Unfortunately Spell Right seems not to work for such files as it does not mark any misspelled word. 

If my assumption is correct, then Spell Right currently does not support virtual workspaces? If true, I guess supporting it would make Spell Right even more valuable than it already is!

In the September release notes of VS Code 1.61 I found a chapter about [this topic](https://code.visualstudio.com/updates/v1_61#_virtual-workspaces-extension-guide), that also contains a link to the corresponding [Extension Guide](https://code.visualstudio.com/api/extension-guides/virtual-workspaces). Just in case you intend to implement support for virtual workspaces :wink:

**Comment by Greedquest** [comment]
... If not then you can mark this extension as does not support virtual workspaces (even just for the time being). e.g. https://github.com/streetsidesoftware/vscode-spell-checker/pull/907

**Comment by devgid** [comment]
Any feedback is this will be in the pipeline?

https://code.visualstudio.com/api/extension-guides/virtual-workspaces

Will be useful if this can be used in the browser or with GIthub remote repos.

**Comment by tyler36** [comment]
It looks like there a couple of PRs (#405 , #398) that might address this. Perhaps confirm they resolve the problem and +1 them might get them merged.

**Comment by bartosz-antosik** [comment]
Spell checking in `vscode-vfs` and `vscode-remote` schemes has been added.
