### ISSUE TITLE
CamelCase word is marked as correct when only one part was corrected

### ISSUE THREAD

**Issue by slodki** [bartosz-antosik/vscode-spellright#46]
Example: `MyyOvnCemalCiseWerd` again :smile:

1. Whole word is underlined as wrong spelling
2. One part is corrected (`Ovn` -> `Own`) using suggestion or manually
3. **Whole word is not underlined (marked as OK?)**
4. After changing the line containing this word...
5. ...underline is displayed again for wrong parts only

I think steps 3 and 4 should be eliminated.

**Comment by bartosz-antosik** [comment]
Should be better from just published version 1.1.22 on.
