### ISSUE TITLE
Multiple VS Code app icons in the macOS dock after the November 2021 (version 1.63) update

### ISSUE THREAD

**Issue by dskecse** [bartosz-antosik/vscode-spellright#465]
Issue Type: <b>Bug</b>

https://github.com/microsoft/vscode/issues/138722#issuecomment-990459514

Extension version: 3.0.60
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 6, 4|
|Memory (System)|16.00GB (0.97GB free)|
|Process Argv|--crash-reporter-id 6429d68c-6f3f-4391-8506-01faac27b59c|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by carlosfrodriguez** [comment]
In my case it spawn 4 more bouncing icons :-(

Disabling the extensions workaround the issue, If I enable it then I get back the 4 extra icons in the dock

((enjoy))
cr

**Comment by xiaohk** [comment]
In my case it only spawn 3 bouncing icons on the right of my dock.

Disabling the extension also works for me.

**Comment by dskecse** [comment]
thank you, @carlosfrodriguez @xiaohk, this has already been discussed by the link mentioned above in the issue description. although disabling the extension works, it's merely a workaround and not the solution.

**Comment by carlosfrodriguez** [comment]
@dskecse I agree, in the mean time I switch to another spell checker. hopefully I switch back again soon.

**Comment by vills** [comment]
fyi, the amount of "bouncing icons" depends on amount workspaces/windows of vscode currently opened.

**Comment by om-ha** [comment]
Is there any option related to `spellright` that is causing this issue? If so we can disable said option as a workaround.

**Comment by om-ha** [comment]
I tried downgrading to the previous version, but the extension didn't work at all.

**Comment by om-ha** [comment]
Here is some debug information:

https://github.com/bartosz-antosik/vscode-spellright/issues/463#issuecomment-990626221

**Comment by cristianoccazinsp** [comment]
Same bug, Intel Mac (Monterey)

**Comment by leira** [comment]
Same issue here. System information can be found in microsoft/vscode#140472.

**Comment by Fabien-GELUS** [comment]
Same on MacOS Catalina 10.15.7, vscode 1.63.2, Spell Right v3.0.60

**Comment by Fabien-GELUS** [comment]
Going back to version 3.0.58 fix this 👌

**Comment by DominicGBauer** [comment]
Also mentioned here https://github.com/microsoft/vscode/issues/138712#issuecomment-1002267673

**Comment by mjvandermeulen** [comment]
> Going back to version 3.0.58 fix this 👌

Going back to version 3.0.58 fixed it for me as well.
- MacOS 10.15.7 (Catalina)
- VSCode 1.63.2 (Universal)

**Comment by om-ha** [comment]
I can confirm the same results as @build3r

**Comment by mscottnelson** [comment]
I am also experiencing this problem. Whenever I open vscode from CLI, a new "dummy" icon appears without ever going away. It's especially annoying in my workflow since I handle many repos, and frequently open new vscode windows from my (non-vscode) terminal. Then, whenever I cmd+tab, I discover 10 or more VSCode icons have spawned and I don't know which VSCode icon is the "real" instance.

Reading through the various issues around this, I would call this a bug in VSCode unless they explicitly decide they are intentionally changing their API with extension authors. Maybe there's a workaround for spellright anyway, though? Disabling spellright is my current fix.

**Comment by cdbattags** [comment]
I've also been experiencing the same. Every new workspace has a new extension host specifically for spellright it looks like?

**Comment by shmulvad** [comment]
This issue has been present for quite some time now. It is a dealbreaker for me and something that has made me disable the extension until it has been fixed. It is a shame, since the extension otherwise is really good.

Does anybody know if this is something that is being actively worked on? I would prefer not to have to switch to another spell checker, but if this extension is abandonware, there is no point in waiting anymore.

**Comment by hazarek** [comment]
all extensions are disabled and still the new icon is bouncing when open file with terminal in same workspace.

**Comment by hazarek** [comment]
i can't report to vscode repo because issue is locked

**Comment by otakaran** [comment]
Glad I found this thread. This is a huge problem when I have many workspaces open simultaneously. Not seeing any updates here so it looks like it's not being worked on.

**Comment by carlosfrodriguez** [comment]
Until this is solved, I temporary switch to `Code Spell Checker`.

**Comment by fdeluca-orangeloops** [comment]
Having same issue here. After a few minutes the icon seems to stop bouncing, but it stays there.
`Computer: MacBook Pro`
`OS: Monterey 12.3.1`

**Comment by Mr-Clam** [comment]
Bouncing icons and other plugins unresponsive brought me to this issue.  It's driving me nuts, so thanks for the person who diagnosed this and recommended disabling the spellright plugin.

Looking at the 171 open issues and 27 open pull requests vs. barely any commits in the last year or so, this project looks like it's becoming abandonware.  Time to find another spelling checker.

**Comment by forivall** [comment]
@Mr-Clam let us know which one you settle on as the best!

**Comment by mattdaviscodes** [comment]
Same problem here. I just uninstalled the extension entirely. Not worth the headache.

**Comment by dmitry-kabanov** [comment]
This bug affects me also.

**Comment by AntonioMeireles** [comment]
afaict this got fixed on VSCodes' side in latest insiders' build. 

<img width="260" alt="image" src="https://user-images.githubusercontent.com/743527/171028023-ec886b87-634b-4aa8-9d7a-5c919a5c7d9f.png">

at sight, here, things seem to be back to normal...

**Comment by dskecse** [comment]
Closing the issue as it seems to have been fixed on VS Code 1.70.2 ✅ 

![Screenshot 2022-08-29 at 22 16 13](https://user-images.githubusercontent.com/1451690/187280786-ed653330-e279-4600-a2a0-4a0415921495.png)

Thank you all for participating! 🎉
