### ISSUE TITLE
Undo editor action doesn't trigger word re-check

### ISSUE THREAD

**Issue by slodki** [bartosz-antosik/vscode-spellright#47]
1. Type word with spell error
2. Word is marked as bad
3. Fix word spelling
4. Word is marked ok
5. Pres `Ctrl-Z` to undo last change
6. **Word is marked ok**
7. Do some more editing somewhere
8. Word is re-checked and marked as bad

I thing steps 6 and 7 should be eliminated.

**Comment by bartosz-antosik** [comment]
Should be better from just published version 1.1.22 on.
