### ISSUE TITLE
Since updating to 1.1.10 Spell Right starts off enabled when configured not to

### ISSUE THREAD

**Issue by Eldaw** [bartosz-antosik/vscode-spellright#48]
Whenever I start VS Code, Spell Right is enabled for the text documents I currently have open, set to spell check in English.

This is despite me having this setting configured:

`"spellright.documentTypes": [],`

Even if I then disable Spell Right for the current document type, if I then quit and restart VS Code, Spell Right becomes enabled once again.

I believe this only started happening after the recent update to 1.1.10. Previously Spell Right was always disabled for all file types until I explicitly enabled it.

**Comment by bartosz-antosik** [comment]
Corrected in version 1.1.12.
