### ISSUE TITLE
Duplicate bouncing VSCode icon in the macOS dock

### ISSUE THREAD

**Issue by Drarig29** [bartosz-antosik/vscode-spellright#497]
Issue Type: <b>Bug</b>

With the "Extension Bisect" feature of VSCode, I found that this extension adds a duplicate icon in the macOS dock and it keeps bouncing.

I imagine you have some kind of process in the background, maybe you can hide it... I don't know.

Extension version: 3.0.60
VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

**Comment by Drarig29** [comment]
Duplicate of #493

**Comment by fire1ce** [comment]
+1
