### ISSUE TITLE
Broken Name for the Norwegian Bokmål Dictionary

### ISSUE THREAD

**Issue by SShrike** [bartosz-antosik/vscode-spellright#5]
The name for the Norwegian Bokmål dictionary displays as ![Norwegian (Bokm?l)](https://cloud.githubusercontent.com/assets/4061736/24952913/77666fdc-1fcd-11e7-8340-d556f7b8e7f4.png) in both the status bar *and* the language selection menu. For reference, I'm running the latest version of VS Code (1.11.1) on Windows 10 x86_64.

Perhaps this issue is not specific to this dictionary, and might apply to any dictionary that has a name using characters outside of the ASCII range?

**Comment by bartosz-antosik** [comment]
No, it is not related to ASCII in any way. As I was unable to find a "official" JavaScript call/module that would translates a language/culture identifier, nb-NO in this case, I did an internal lookup. It had broken this particular name. It has already been corrected and will be be corrected in next release.
