### ISSUE TITLE
SpellRight crashes on certain emoji

### ISSUE THREAD

**Issue by paulwellnerbou** [bartosz-antosik/vscode-spellright#511]
I tracked it down to one line (I have an AsciiDoc file, with the extension `.adoc`), with this content:

```
Tidy up 🧹.
```

The 🧹 is causing SpellRight to crash constantly.

Is there anything I can do about it?

I am working on Linux (Ubuntu):
```
Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-15T02:58:26.441Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.13.0-51-generic snap
```

I assume this is the error:
```
  ERR A system error occurred (read ECONNRESET): Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_errnoException (node:internal/errors:594:12)
    at Pipe.onStreamRead (node:internal/stream_base_commons:220:20)
```
![Screenshot from 2022-06-21 08-57-17](https://user-images.githubusercontent.com/1842543/174736237-2e3032a9-3ad8-4687-9a6c-a7f147458317.png)

It works without SpellRight.

**Comment by maxammann** [comment]
I'm also experiencing this issue. I think upgrading hunspell is the best way to go forward.
