### ISSUE TITLE
Extension not working properly on VSCode 1.74.0

### ISSUE THREAD

**Issue by rotemdan** [bartosz-antosik/vscode-spellright#536]
Suggestions either don't appear, don't disappear or don't update correctly after one error is found, even after the error is fixed.

I'm not sure if this is a VSCode issue only, since it worked properly on previous versions, but I've also reproduced the issue on latest Insider build (`1.75.0-insider`) with only the Spell Right extension installed:

![spellright1](https://user-images.githubusercontent.com/8589488/206639953-5b85e82b-ac47-4f47-bd57-111a546c86e1.gif)

The video was captured on:
```
Version: 1.75.0-insider (user setup)
Commit: b92894493e6f971a3c71912d823e699d3a05d643
Date: 2022-12-08T05:20:51.149Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes
```

_Edit_: The extension page logs many uncaught errors:
![Screenshot_9](https://user-images.githubusercontent.com/8589488/206642391-57194fa7-f041-4b03-85bc-70912e0b2b69.png)

Maybe this is this related to some breaking API change that was introduced in `1.74.0`?

**Comment by bartosz-antosik** [comment]
I will have a look at this. Looks strange, indeed.

**Comment by kakoeimon** [comment]
I have the same issue, but it looks like it is a VSCode regression.
I had 1.7.4 (no iinsider)
I installed 1.7.2 and everything works as expected.

**Comment by SR--** [comment]
Same here, not working on 1.7.4

**Comment by hjhilden** [comment]
Same, stopped working with version: 1.74.0. Also getting the `Cannot read properties of undefined (reading '_line')`

**Comment by gdavisSMAX** [comment]
I am getting the same behavior.
Running VSC 1.74.0 / Spell Right 3.0.90 on a Windows 11 laptop.

**Comment by J-Lakeman** [comment]
Confirmed with Version: 1.74.0 running on _Ubuntu 22.10_ as well as _macOS Big Sur_, so this indeed seems to be a VS Code issue.

**Comment by rotemdan** [comment]
I've updated to the new version and the issue seems to be fixed. Thanks! You can close the issue if you wish.

**Comment by bartosz-antosik** [comment]
@SR-- Thanks. I wish I could polish it here and there but hasn't got enough time recently.

**Comment by SR--** [comment]
This one has 339k installs. You are truly lucky if you have another project that is more important than keeping 339k humans happy. ;)

**Comment by bartosz-antosik** [comment]
@SR-- Thank you! I will put your message in frame and hang s/where around to look at in the moments of doubt!
