### ISSUE TITLE
How can one use additional hunspell dictionaries on a Mac? 

### ISSUE THREAD

**Issue by ttasovac** [bartosz-antosik/vscode-spellright#542]
Adding dictionaries to `$USERHOME/Library/Spelling` (which would be the expected place on a Mac) doesn't seem to do anything —  spellright doesn't offer those additional dictionaries  in the language dropdown.

I've also tried `$USERHOME/.vscode/Dictionaries` and  `$USERHOME/.vscode/dictionaries` with no effect.

The README mentions only these:

```
Windows: %APPDATA%\Code\Dictionaries\
Linux: $HOME/.config/Code/Dictionaries/
```

but no option for adding custom hunspell dictionaries on a Mac. 

Many thanks in advance.

**Comment by bartosz-antosik** [comment]
Hi! I suppose it may be the issue described in `Known Issuses` of the README.md.

**Comment by cyoq** [comment]
Hello! Do you know if it is possible to solve this issue, maybe by setting the path to the `.dic` and `.aff` files?
I have set up a custom dictionary to `$USERHOME/Library/Spelling` and it is recognized by the system in the settings, but the extension still cannot see the spelling. It is very frustrating that the 10-year-old issue persists on the Mac 😢
