### ISSUE TITLE
Support for British English (splitting dictionaries by regions) on macOS 

### ISSUE THREAD

**Issue by kaimdx** [bartosz-antosik/vscode-spellright#56]
I am writing my latex document using VScode, and the Spell Right plugin is essential. I am in UK so often needs British English. However, I see only one 'English' option from the language list, and it uses US spelling. Is it possible to have the option of British English? I am using it on Mac with system language set to 'English - U.K.'. Thanks.

**Comment by bartosz-antosik** [comment]
Please try to set `spellright.groupDictionaries` configuration option to `false` and then you should see all the regions of dictionaries!

**Comment by kaimdx** [comment]
Thanks. I changed the setting (last line in the screenshot below) and restarted vscode a few times,

![screen shot 2017-08-24 at 21 12 22](https://user-images.githubusercontent.com/1853740/29686502-162800de-8911-11e7-8f62-ce538a3e6157.png)

However, the list of languages seem to remain the same. Did I miss anything? 

![screen shot 2017-08-24 at 21 14 38](https://user-images.githubusercontent.com/1853740/29686563-516641ce-8911-11e7-83b0-4ab5c5210b28.png)

**Comment by bartosz-antosik** [comment]
You probably have not. This seemed to be working (it does work on Windows, but this is another matter) on macOS when I tested it about three weeks ago. 

Please give me some time to investigate further. I will probably have some time to check this after the weekend.

**Comment by kaimdx** [comment]
OK, thanks.

**Comment by bartosz-antosik** [comment]
Just stroke me - there is another thing you may try - set `spellright.language` to en-GB or en_GB and see the difference in spelling (e.g. color - colour, flavor - flavour, etc.).

**Comment by kaimdx** [comment]
Thanks. Just tried both 'en-GB' and 'en_GB', but neither made any difference.

**Comment by bartosz-antosik** [comment]
Let me investigate then.

**Comment by bartosz-antosik** [comment]
I had eventually contact with Mac and it looks like somehow your settings are not taken applied.

When I have set `spellright.groupDictionaries` to false the list of languages looks like this:

![spellright-mac-1](https://user-images.githubusercontent.com/20492548/29743396-96cefca2-8a91-11e7-9a35-299698fe77d7.png)

From where you can choose `English - United Kingdom`:

![spellright-mac-2](https://user-images.githubusercontent.com/20492548/29743401-a9f86732-8a91-11e7-85fb-fed96dbd7cc4.png)

And voila, the difference:

![spellright-mac-3](https://user-images.githubusercontent.com/20492548/29743403-b0db8566-8a91-11e7-88c4-3a18f02eb08f.png)

![spellright-mac-4](https://user-images.githubusercontent.com/20492548/29743404-b39cff82-8a91-11e7-895c-6205cdc7e2f6.png)

What is important in the whole experiment, is that once the `spellright.groupDictionaries` is ACTUALLY set to false the list of languages displays language codes beside language names! And yours does not!

DON'T you have PER CHANCE a workspace settings which override global settings?

**Comment by kaimdx** [comment]
This is all the 'user settings' I have currently:

![screen shot 2017-08-26 at 22 12 43](https://user-images.githubusercontent.com/1853740/29745177-f8925b36-8aab-11e7-8570-cc621193b5c2.png)

And the 'workspace settings' is empty

![screen shot 2017-08-26 at 22 15 58](https://user-images.githubusercontent.com/1853740/29745197-3994d348-8aac-11e7-9f39-269e3c369c25.png)

**Comment by bartosz-antosik** [comment]
No, these are not workspace settings for SpellRight! Some extensions, SpellRight included, use they local files in .vscode folder, under workspace folder. SpellRight uses `spellright.json` file. Please check whether you have no `spellright.json` in your workspace's .vscode folder.

Using separate file is easier to copy the settings e.g. to other, new workspace.

Definetly your settings are overridden - there should be language codes on the list.

**Comment by bartosz-antosik** [comment]
I did another test, on freshly installed VSCode on macOS. Seems that setting `spellright.groupDictionaries` to `false` does show regional variations of the languages. Please look around because it looks like there may be some issue with your settings, as suggested above. Otherwise it looks strange.

**Comment by kaimdx** [comment]
Yes, I found the spellright.json file in the .vscode directory. It has `"groupDictionaries": true`, which probably overrwrites the settings. I can see different English options now once change that to `"groupDictionaries": false`. Thanks!

![screen shot 2017-08-27 at 13 46 40](https://user-images.githubusercontent.com/1853740/29749919-385f2956-8b2e-11e7-9429-dad21a4a726f.png)

![screen shot 2017-08-27 at 13 47 45](https://user-images.githubusercontent.com/1853740/29749924-564c5f2e-8b2e-11e7-8fc4-06c63d0397e3.png)
