### ISSUE TITLE
Select the correct spelling from the right-click menu or mouse-over message?

### ISSUE THREAD

**Issue by kaimdx** [bartosz-antosik/vscode-spellright#57]
I just started using Spell Right on Mac. It will be really convenient if I can select the correct spelling from the mouse-over message or the right-click menu. Currently I can see the spelling suggestions in the mouse-over message but then have to type it in or copy-n-paste. Did I miss something?

**Comment by kaimdx** [comment]
I just realised you can select the spelling options from the light bulb at the beginning of the line.

**Comment by bartosz-antosik** [comment]
Please have a look at the README file (it is basically what is displayed in the description of the extension) - there is this information: "Use **F8** or **Shift-F8** to jump to next/previous spelling error. Press **Ctrl+.** or click *Lightbulb* to see context menu with suggestions." This Ctrl+. is especially convenient.

I personally would prefer context menu for corrections but it is the nature of VSCode which is an obstacle here. Extensions simply have no access to context menu. Mouse over is also faulty but you can read about it towards the end of aforementioned README file (See *Known Issues*).

**Comment by kaimdx** [comment]
Thanks, Bartosz.
