### ISSUE TITLE
Spell Right stops working after saving a file (won't spell check files stored on disk)

### ISSUE THREAD

**Issue by colbyn** [bartosz-antosik/vscode-spellright#579]
## Overview:

I don’t know if this is me or not.

When I crate a new (unsaved) file, spell right correctly highlights and warns me of misspelled words.

But as soon as I save the file, spell stops working. 

VSCode recently updated, for a few days following the update spell right stepped working, but now its sorta working, but it won’t spell check files (unless they not saved to any file) makes no sense. 

Again, as soon as I save a file, spell right just shuts down, it won't spell check files that are stored on disk. It only works for scratch files (or whatever they're called i.e. files opened in memory).

## Platform Details:

**OS:** MacOS 14.5

**VSCode Information:**

Version: 1.90.1 (Universal)
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:02:41.372Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 23.5.0

Thanks!

**Comment by bartosz-antosik** [comment]
Hi! Tried the described scenario (New document, errors highlighted, saved as .txt, spelled and highlighted again) and it seems to work for me. The OS is Linux. Do not have MacOS around. Could you please provide more details?

**Comment by MarviMcFly** [comment]
I can not reproduce this issue on my MacBook Pro despised the fact that it seems that I have issues with .tex files (see #580).

**Comment by colbyn** [comment]
oh weird, at any rate this is no longer a prompt with my text editor so I suppose I'll close the issue.

Thanks for all your work!
