### ISSUE TITLE
'Add to workspace dictionary' doesn't make red squiggle disappear immediately

### ISSUE THREAD

**Issue by Eldaw** [bartosz-antosik/vscode-spellright#58]
After choosing 'Add to workspace dictionary' for a work, the red squiggle didn't disappear immediately. Only after I changed to a different tab and came back, did it then disappear? Expected?

**Comment by bartosz-antosik** [comment]
What OS are you using?

**Comment by Eldaw** [comment]
Windows 10.

**Comment by bartosz-antosik** [comment]
Version 1.1.25 has something reasonable changed about it. Please give it a try.
