### ISSUE TITLE
Extension fails to read workspace/project dictionary

### ISSUE THREAD

**Issue by kmactane** [bartosz-antosik/vscode-spellright#584]
I am in a project that has an existing .vscode/spellright.dict file in the project's root directory. That file includes over 100 items (although I now see there are quite a few repeats, presumably because of this bug).

Nonetheless, in the file I'm editing, a word is being flagged that's in the spellright.dict file 3 times already. (It's "Kuang", a person's surname.)

I add the item in question again, using `Ctrl+.`, then 'Add "Kuang" to workspace dictionary'.

Then I hit Enter and the word I just added immediately gets a red squiggle under it again.

I have checked on a word that's in my user dictionary in my home directory, and that one _does not_ get a red squiggle, so apparently it's reading user dictionaries just fine. However, I'd really rather not add a huge number of words that are specific to this project into my global user dictionary.

**Comment by spaceman1313** [comment]
I'm running into the same problem, but with one difference.

After I add a word to the workspace dictionary, the squiggles correctly disappear from the file I'm editing.  They do not disappear from other open files.  If I close the file I'm editing, and reopen it, the squiggles for the workspace dictionary word are back.

**Comment by ch-e-mistry** [comment]
Same issue here.

**Comment by RasmusB** [comment]
I'm seeing the same issue on my machines. It also allows me to add the same word to the workspace dictionary over and over again. It's like it can find the file and write to it, but is not reading from it.

**Comment by JukkaJurvansuu** [comment]
Same issue here. Using Windows 10.

**Comment by LokiMidgard** [comment]
Is there a way to enable some kind of logging, I assume `SPELLRIGHT_DEBUG_OUTPUT` needs to be set hardcoded in src?

**Comment by LokiMidgard** [comment]
I also had the Problem on my Windows 11 machine, on Ubuntu it works as expected.

**Comment by rotemdan** [comment]
After several months of experiencing the issue, I've took some time to investigate this myself. It seems to be an issue with the `glob` package not properly handling standard windows paths, which include backslashes `\`. This causes the glob pattern not to match any dictionary files.

I've made a [pull request](https://github.com/bartosz-antosik/vscode-spellright/pull/592) that should fix it by replacing backslashes (`\`) with forward slashes (`/`) in the glob pattern. That seems to fix the issue on my Windows 11 system.

**Comment by JukkaJurvansuu** [comment]
> After several months of experiencing the issue, I've took some time to investigate this myself. It seems to be an issue with the `glob` package not properly handling standard windows paths, which include backslashes `\`. This causes the glob pattern not to match any dictionary files in the local workspace.
> 
> I've made a [pull request](https://github.com/bartosz-antosik/vscode-spellright/pull/592) that should fix it by replacing backslashes (`\`) with forward slashes (`/`) in the glob pattern. That seems to fix the issue on my Windows 11 system.

Thanks for this. It solved the problem and I can continue using spellright.
