### ISSUE TITLE
`spellright.notificationType` vs. `spellright.notificationClass`

### ISSUE THREAD

**Issue by James-Yu** [bartosz-antosik/vscode-spellright#61]
Currently the configuration endpoint in `package.json` is `spellright.notificationType`. However, the readme and code use `spellright.notificationClass`.

ref:
https://github.com/bartosz-antosik/vscode-spellright/blob/1ef5575fd8d39845b9e411b18e6acc459e614269/package.json#L72
https://github.com/bartosz-antosik/vscode-spellright/blob/1ef5575fd8d39845b9e411b18e6acc459e614269/src/spellright.js#L696

**Comment by bartosz-antosik** [comment]
Many thanks for spotting this! I swear I have tested the feature, but maybe have not realized the name discrepancy...
