### ISSUE TITLE
Treat tilda as space in LaTeX files

### ISSUE THREAD

**Issue by Ethefor** [bartosz-antosik/vscode-spellright#62]
In LaTeX ~ (tilda) is used as non breaking space. 
Unfortunately vscode-spellright treat e.g. `I~am` as one word, not two separate words. 
It would be very nice if spellright will treat tildas as spaces for LaTeX files :)

Thanks for very great extension, btw :)

**Comment by bartosz-antosik** [comment]
Should be fine from version 1.1.32 on. Let me know in comments below despite the thread will be closed.

**Comment by Ethefor** [comment]
Wow, that's was great, you are super fast :) It works fine now, as I expected. Thanks a lot!
