### ISSUE TITLE
Allow Spell Check for D Source Code Files

### ISSUE THREAD

**Issue by SommerEngineering** [bartosz-antosik/vscode-spellright#63]
I use spellright successfully with e.g. LaTeX and Go. But it does not parse e.g. `*.d` files (cf. D language, https://dlang.org). Although, the D syntax for strings as well as for comments is very similar to e.g. Go, C#, etc.

Comments:
```
/**
   xxx
*/
```

```
/*
   xxx
*/
```

`// xxxx`

Strings:

```
`This
is a multi
line string`
```

`"xxx"`
`'x'`

Can I add myself the D language by applying some configurations or must be the plugin extended?

**Comment by bartosz-antosik** [comment]
Sadly you cannot! Extensions do not have access to the syntax information for document classes so it has to be added.

Is D supported by VSCode as it is or is there a need to install some extension to support it? Which extension?

**Comment by SommerEngineering** [comment]
It is the extension `code-d`: https://marketplace.visualstudio.com/items?itemName=webfreak.code-d.

**Comment by SommerEngineering** [comment]
Regarding the spell checker, I would suggest to handle only the `d` extension -- if this is possible. The valid delimiters I mentioned in the first post are valid for such `d` files. 

`diet` files are templates for web programming to generate HTML files. For the first release of spellright with D support, you could consider such files as text files i.e. spell check every word. Strings and comments are not as easy to parse for `diet` files, cf. https://vibed.org/templates/diet

Any other file type, I would ignore i.e. disable spell checking. For instance, `dml` is a sort of XML file which most programers do not use.

I hope this may help you. Thank you very much for you effort.

**Comment by bartosz-antosik** [comment]
Support for 'd' (source code) and 'diet' (plaintext) has been added in version 1.1.34.

Please have a look & let me know in this thread.

**Comment by SommerEngineering** [comment]
Thanks a lot, bartosz. It works great.

**Comment by bartosz-antosik** [comment]
At your service (until other duties will not pull me off SR development ;-))
