### ISSUE TITLE
Add support for Lorem Ipsum

### ISSUE THREAD

**Issue by perryprog** [bartosz-antosik/vscode-spellright#65]
I'm not sure if this is something you can do, but I wanted a spellcheck for the website I'm making and currently there's a lot of filler text which is all Lorem Ipsum. It would be nice if those were in the dictionary by default.

**Comment by perryprog** [comment]
For now put [this](https://gist.github.com/perryprog/caf98144443a8eed90b77d7631dfec62) in your user dictionary.

**Comment by bartosz-antosik** [comment]
New, just published version 1.2.2 has the ability to read all *.dict files from workspace directory (`.vscode`). You can put e.g. `lorem.dict` there and have it done for development time, then remove it and spelled things "comme il faut".

**Comment by perryprog** [comment]
Awesome! This is perfect.

**Comment by bartosz-antosik** [comment]
You are welcome! A review is always welcome! ;-)
