### ISSUE TITLE
Trying to ignore camelcase words in JS using spellright.ignoreRegExps

### ISSUE THREAD

**Issue by jsangaritar** [bartosz-antosik/vscode-spellright#67]
I want to avoid all camelcase words in a JS file. I am trying to use:

`spellright.ignoreRegExps: ["/[a-z]+[A-Z0-9][a-z0-9]+[A-Za-z0-9]*/g"]`

But it does not work.
Is there any way i can achive that?

Thanks.

**Comment by jsangaritar** [comment]
By the way, this is the only SpellChecker that actually works in Spanish. Thanks.

**Comment by bartosz-antosik** [comment]
Could you please show me a comment/string part (or a screenshot of those) that get spelled and you do not want them to?

**Comment by jsangaritar** [comment]
These are some examples:

`/**
* @cfg {Boolean} [**blForceReadOnly**=false]
* indica si se fuerza a que la celda sea readonly
*/
**blForceReadOnly**: false
`

`/**
 * @docauthor  13-03-2017    jangarita  402586  [Modificación]
 * @docauthor   [constructor,**updateBlEditable**,**RenderValue**,**BuildCell**,**BuildEditableCell**]: se modifican los parámetros de entrada.
 * @docauthor   - **RenderValue**: se actualiza el label de la columna
 * @docauthor   [Adición]
 * @docauthor   - **BuildFieldComponent**
*/`

I will appreciate your help with this.

**Comment by bartosz-antosik** [comment]
It seems that exactly your regular expression is doing the job:

![regexp-enabled](https://user-images.githubusercontent.com/20492548/30387117-da6d7272-98ab-11e7-8624-ade62b692e02.png)

But you put this in global configuration. Don't you have a workspace spellright.json where the value of `ignoreRegExps` could be overridden?

**Comment by jsangaritar** [comment]
OMG im so sorry, you are right in some configuration in the workspace the property was declared but without any value.

It works perfects, thanks.
