### ISSUE TITLE
Support for Julia

### ISSUE THREAD

**Issue by kaitian-xie** [bartosz-antosik/vscode-spellright#68]
The extension works pretty well and I like it. I think could it could be better if support for Julia ([Julia comment syntax](https://docs.julialang.org/en/release-0.4/stdlib/punctuation/)) is added .

**Comment by bartosz-antosik** [comment]
I understand that Julia support (syntax coloring etc.) is added by an extension. Which?

**Comment by kaitian-xie** [comment]
[Julia](https://marketplace.visualstudio.com/items?itemName=julialang.language-julia)

**Comment by bartosz-antosik** [comment]
This extension registers (besides Julia source code) a .jmd (juliamarkdown) file type. Can you provide a description/example (e.g. Code section etc.)?

**Comment by kaitian-xie** [comment]
https://docs.julialang.org/en/stable/search/?q=markdown

**Comment by bartosz-antosik** [comment]
Everything should be in just published version 1.2.2. Let me know if anything is not as it should.
