### ISSUE TITLE
command "spellright.*" not found

### ISSUE THREAD

**Issue by swarnendubiswas** [bartosz-antosik/vscode-spellright#69]
Hi, I am trying to use Spell Right on Visual Studio Code on CentOS 7. But I cannot seem to get the extension working, and I encounter `command 'spellright.selectDictionary' not found ` errors.

Visual studio code version is 1.16.1, spell right version is 1.2.2.

I tried `chmod a+x spellchecker-linux-1.*` in the extensions directory. Executing `./spellchecker-linux-1.7.4-x64.node` lead to a `Segmentation fault (core dumped)` (although I maybe misusing it).

Note that I have the extension working on a Ubuntu 17.10 system, so my hunch is that this could be a CentOS related issue.

**Comment by bartosz-antosik** [comment]
Could you locate file `extension.js` of the extension and flick `global.SPELLRIGHT_DEBUG_OUTPUT` to `true` and show me what does the `DEBUG CONSOLE` show?

**Comment by bartosz-antosik** [comment]
And no, these binary bindings (`*.node` files) should not be executed directly.

**Comment by bartosz-antosik** [comment]
And of course - is SELinux ON? What does it's log say (`/var/log/audit/audit.log)? Are there any AVC lines?

**Comment by swarnendubiswas** [comment]
SELinux is disabled. And I do not see any additional console output after having turned on the debug flag.

**Comment by bartosz-antosik** [comment]
Could you maybe compare libc versions between systems? What version of CentOS is this?

**Comment by swarnendubiswas** [comment]
The CentOS details are: `CentOS Linux release 7.3.1611 (Core)`  and `GNU C Library (GNU libc) stable release version 2.17`. I will share the version information from the Ubuntu system after some time, I do not have access to it right now.

**Comment by bartosz-antosik** [comment]
Could you please download a test version from here:

https://drive.google.com/file/d/0B9u6OGMG7xHcb0FoTkpnWDh2UWs/view?usp=sharing

Install it from VSIX file and see if it produces anything (e.g. Array[6]...) to DEBUG CONSOLE.

**Comment by swarnendubiswas** [comment]
I tried it out, but I could get no information. 
![screenshot from 2017-09-18 17-06-03](https://user-images.githubusercontent.com/7343807/30567060-45802f28-9c94-11e7-96de-580d7e00ba54.png)

**Comment by bartosz-antosik** [comment]
This is very incomprehensible. Looks like the `activate` method of the extension is not called at all! 

Thank you for all the efforts! I am pursuing this as I had about a month ago a similar case - two Windows 10 side by side on one it is working on other it is not! But really I am clueless!

Could you please try to disable all the other extensions for a test?

I will probably eventually try to install virtual CentOS and see if it is replicable.

**Comment by bartosz-antosik** [comment]
Could you also please start VSCode with verbose option (`code --verbose`) and post the output here?

**Comment by swarnendubiswas** [comment]
I ran `code --verbose` with just `spellright` enabled. The version of spellright is 1.2.4. Well, it still seems to make no difference. 
![screenshot from 2017-09-19 10-17-31](https://user-images.githubusercontent.com/7343807/30600081-1a50159e-9d24-11e7-954f-12c74f283fbb.png)

Note that I do not have administrative rights on this machine.

**Comment by bartosz-antosik** [comment]
Thank you. I will see what can I get out of it.

**Comment by bartosz-antosik** [comment]
Would be very useful if you could test the version from the link above and let me know if it works for you. The whole thing was reproduced by me on virtual installation of CentOS and it seems that rpm based distributions need separate build of binding libraries. And they are filled in the above build.

**Comment by swarnendubiswas** [comment]
Nice, version 1.2.6 works. The extension is activated, and I can invoke commands. 

However, I have a different issue. The extension is not highlighting misspelled words on a LaTeX document that I am testing with, although it shows the language settings and says "spell checking - on". Any ideas what could I be doing wrong?

**Comment by bartosz-antosik** [comment]
Great (about that it works). About LaTeX - really have no idea. Does it spell other documents?

![image](https://user-images.githubusercontent.com/20492548/30653914-b56fe262-9e2c-11e7-9215-9d506f9302ca.png)

**Comment by swarnendubiswas** [comment]
Ok, I have fixed it. The name of the dictionary was wrong. Thanks for helping.

**Comment by swarnendubiswas** [comment]
Well, I am curious about your choice of using hunspell instead of aspell. Could you comment on that? Thanks.

**Comment by bartosz-antosik** [comment]
I think quite a good explanation can be found here [#20266](https://github.com/Microsoft/vscode/issues/20266).

**Comment by bartosz-antosik** [comment]
Bindings for RPM based Linux system will be included in next release.

**Comment by swarnendubiswas** [comment]
Thanks.

**Comment by bartosz-antosik** [comment]
You are welcome.

**Comment by einarmagnus** [comment]
I get this same error message. I'm running this: 
~~~
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
~~~
and installed spellright in WSL. Any `spellright.<command>` command results in a popup with `command 'spellright.<command>' not found`

**Comment by eric-belhomme** [comment]
> and installed spellright in WSL. Any `spellright.<command>` command results in a popup with `command 'spellright.<command>' not found`

Same here. My WSL environment is a Debian Buster, with hunspell dictionaries installed, and symlink as described in the doc: /home/rico/.config/Code/Dictionaries -> /usr/share/hunspell

**Comment by michalfapso** [comment]
I had the same issue. My VSCode was installed from official Ubuntu repository (version 1.38.0-1567547996). Then I switched to this ppa: https://github.com/tagplus5/vscode-ppa, upgraded the `code` package and SpellRight started to work right away. So maybe it was just a problem of an older code version.

**Comment by bwegge** [comment]
I seem to be having the same issue with VS Code 1.48.0 on Windows 10 (64 bit), connected inside my Windows Subsystem for Linux WSL running Ubuntu 20.04. Like eric-belhomme described, any spellright.<command> command results in a popup with command 'spellright.<command>' not found. Setting global.SPELLRIGHT_DEBUG_OUTPUT to true appears to makes no difference.

Below are the details from VS Code's about dialog. Electron version is 7.3.2, but in the extension's lib/bin folder inside WSL, I only see `spellchecker-{deb,rpm}-{7.1.7,9.1.0}-{ia32,x64}.node` binaries, but nothing explicitly for 7.3.2 (in case this matters).
```
Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
