### ISSUE TITLE
Spell check does not ignore punctuation.

### ISSUE THREAD

**Issue by zkirkland** [bartosz-antosik/vscode-spellright#7]
If I have an unknown word such as a technical word like "flyout" at the end of a sentence as shown:

    This opens a flyout.

The spell checker includes the punctuation. Even if I add "flyout" to the dictionary, it does not work because the spell checker still considers "`flyout.`" to be an incorrect spelling.

**Comment by bartosz-antosik** [comment]
Should be fine in version 1.0.8.

**Comment by zkirkland** [comment]
Works great! Thanks!
