### ISSUE TITLE
Words with dashes are not spell-checked as a whole

### ISSUE THREAD

**Issue by borekb** [bartosz-antosik/vscode-spellright#70]
I'm not sure if this is a SpellRight or deeper system issue but I cannot get the word "wp-admin" spelled correctly:

![image](https://user-images.githubusercontent.com/101152/31113219-7ce1f390-a818-11e7-9c18-b62343705151.png)

I tried adding "wp-admin" as a whole to the user dictionary via _Add Selection to User Dictionary_ but it doesn't help.

Might be similar to the issue https://github.com/bartosz-antosik/vscode-spellright/issues/66 which was about camelCased words.

**Comment by bartosz-antosik** [comment]
Dash currently separates words like a class of other symbols (e.g. tilda, hash etc.) I will think of a way to refine this, although I am not sure whether this will not backfire somehow...

**Comment by bartosz-antosik** [comment]
Please test version 1.2.11. It should behave as you wished.

**Comment by borekb** [comment]
Wow that was fast! Works as expected, thanks.

**Comment by bartosz-antosik** [comment]
As usual - please let me know if it resolves the request & if you have any side notices.

**Comment by bartosz-antosik** [comment]
Oh, sorry, you responded above & I have missed bot the fact and e-mails with notifications.

**Comment by bartosz-antosik** [comment]
As a comment - parsers are flexible in this matter - separators can be moved up and down processing so it was quite easy to perform.

**Comment by Crissium** [comment]
As mentioned in #323 #458 #472 perhaps only hyphens (U+002D, U+00AD and U+2010) should not be treated as separators.
