### ISSUE TITLE
Git commit Messages are not spell checked

### ISSUE THREAD

**Issue by Roang-zero1** [bartosz-antosik/vscode-spellright#71]
If using vscode as default git editor the opened commit messages are not spell checked.
Currently, the language git-commit returns a null for fromLanguage:
https://github.com/bartosz-antosik/vscode-spellright/blob/cae1c191d6b853911d88187b01819ef6d736fb25/lib/doctype.js#L81-L84

Considerations:

- Plain text at the start of the file should be checked
- Lines that start with a `#` should be ignored
- Lines after a verbose divider `# ------------------------ >8 ------------------------` should be ignored

**Comment by bartosz-antosik** [comment]
Could you please show me a generic example of such a comment? 

I know how does the commit message with line comments look like, but these dividers are not clear to me.

**Comment by Roang-zero1** [comment]
Sure, here is a quick example of how a verbose commit would look like in the editor:

```
Initial commit

This should be spellchecked
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
#
# Initial commit
#
# Changes to be committed:
#	new file:   example.txt
#
# ------------------------ >8 ------------------------
# Do not touch the line above.
# Everything below will be removed.
diff --git a/example.txt b/example.txt
new file mode 100644
index 0000000..e69de29
```

**Comment by bartosz-antosik** [comment]
Much clearer now. Thank you.

**Comment by bartosz-antosik** [comment]
It should be done in freshly published version 1.2.15. Drop me a lie here whether it works for you, please.

**Comment by Roang-zero1** [comment]
Thanks, works perfectly.

That was a really quick turnaround, keep up the good work!

**Comment by bartosz-antosik** [comment]
Rating the extension would not hurt! ;-)

**Comment by Roang-zero1** [comment]
Done ;)

**Comment by bartosz-antosik** [comment]
Yes, I saw this. Thank you!
