### ISSUE TITLE
Python multi line strings are not checked

### ISSUE THREAD

**Issue by Roang-zero1** [bartosz-antosik/vscode-spellright#73]
In python files it is possible to define a multi line string like this:
```
print("""A string.
It will be on
multiple lines""")
```

These strings are currently not spell checked,
Normal strings like `'here'` or `"this"` work fine.

**Comment by bartosz-antosik** [comment]
Thanks for this. I have missed this somehow (I personally hate multi-line strings ;-)) for which I blame this "string in some places is comment" phenomenon of Python. Never mind. Should be fixed tomorrow.

**Comment by bartosz-antosik** [comment]
It should be resolved in version 1.2.17. Please let me know if it works ok for you. Thanks.

**Comment by Roang-zero1** [comment]
I can confirm the multiline strings are now spellchecked.
Thanks for the fix.

**Comment by bartosz-antosik** [comment]
Thanks fo the update!
