### ISSUE TITLE
I'm not sure how this works

### ISSUE THREAD

**Issue by icuurd12b42** [bartosz-antosik/vscode-spellright#75]
I installed this because of the html spelling, but I cant get this to run... 

I installed it, it's enabled, yet I see nothing showing up like in the screenshot in the details page

Full disclosure, none of the spell checkers I tried actually work so this may be due to the way I installed MS Visual Code... Meaning it's not on the c: drive which is OS files ONLY but on my D: drive... 

![image](https://user-images.githubusercontent.com/6321426/31366777-ed61aaa2-ad40-11e7-8ee4-54344ba6d27b.png)

**Comment by bartosz-antosik** [comment]
Thanks for extended description of your situation, not just complaint!

I do not think that installation on D: should affect the way Spell Right works. I will ask few questions and maybe will ask you to do some tests. Then I will try to reproduce the issue.

Spell Right is OFF by default for HTML/XML documents. You have turned it ON for HTML, right (with status bar button, appropriate command or configuration settings)?

**Comment by icuurd12b42** [comment]
I'm a Visual Code total newb. I see the option bottom right! Thanks! I turned it on. Seems to work.

I love visual code but this command and hot key centric system is a little overwhelming... this statement will become ironic in 5 seconds...

...Slight issue with it detecting half my app's name as bad :)

![image](https://user-images.githubusercontent.com/6321426/31373915-dec07806-ad69-11e7-84d6-34b262ebb86c.png)


Even after I added it :)

![image](https://user-images.githubusercontent.com/6321426/31374005-35fdc11e-ad6a-11e7-8979-bcbbed86a1a1.png)

It's nothing worth fussing over though. as long as the thing can fix my numerous daily typos.

Thanks for the help and the extension!

**Comment by bartosz-antosik** [comment]
You are welcome! Happy I could (partially) help!

That's bit strange what you observe - when I put `HotKeySpeak's` in a text or XML document it spells correctly! Could you confirm this?

![image](https://user-images.githubusercontent.com/20492548/31376274-a8e88198-ada4-11e7-9ad0-2b48c0ffa4d0.png)

**Comment by icuurd12b42** [comment]
html, xml or text, it only dislikes the "Speak's" part
![image](https://user-images.githubusercontent.com/6321426/31377528-4c1dcc26-ad76-11e7-9707-59a819dc4410.png)

Was system are you using? is it using components off of the OS? It could be a localisation or something... My Localisation is Canada and language US English

**Comment by bartosz-antosik** [comment]
It's Windows 10, EN-US as default language, the language in Spell Right is en, without specific region - Windows Spell Checking API allows this. I will recheck with US region.

I did. It still spells correctly:

![image](https://user-images.githubusercontent.com/20492548/31377971-219df500-adaa-11e7-8c7a-11e08a20bf62.png)

**Comment by icuurd12b42** [comment]
Don't fret it, I am a legend when it comes to weird program behaviors. It's like my stuff runs in an alternate reality where Murphy's law is the norm
