### ISSUE TITLE
macOS Sierra: new language (Hungarian) added sucessfully to the System, but can't be selected with Spell Right

### ISSUE THREAD

**Issue by andrasna** [bartosz-antosik/vscode-spellright#76]
Hi,

I am trying to make Spell Right work with Hungarian on macOS Sierra.

- I have followed the System instructions of adding new languages: I have copied dictionary files (`hu_HU.aff`, `hu_HU.dic`) to `~/Library/Spelling`.

- I have confirmed that the language has be added to the System: 
  - Hungarian ("Magyar") can be selected in System Preferences / Keyboard / Text
  - Hungarian spellcheck works now with Mail

- I have tried setting `spellright.groupDictionaries` to `false` (just as a guess)

I would like to ask, if you could help find out where the problem lies.

Thanks,
Andras

![screen shot 2017-10-14 at 11 43 01 am](https://user-images.githubusercontent.com/13708820/31574853-a887dbb8-b0d8-11e7-8f3a-5e7bb23cfc82.png)
![screen shot 2017-10-14 at 11 44 42 am](https://user-images.githubusercontent.com/13708820/31574854-a8a46274-b0d8-11e7-9e72-da7ec56f1d2d.png)

**Comment by bartosz-antosik** [comment]
Hm. MacOS is not my specialty. Looks like the system speller does not list dictionaries installed in the `Library` path, when asked. Looks like there is a Pull Request for the thing in the library I use there seems to be, however, some reluctance in adding the patch.

Have you tried, despite it is not listed, setting `spellright.language` to `hu_HU` or `hu-HU`?

**Comment by andrasna** [comment]
Yes, I forgot to mention, I have tried setting spellright.language to Magyar, Hungarian, hu_HU and now hu-HU as well, just in case. If I do so, it falls back to English.

**Comment by bartosz-antosik** [comment]
I have got no time so far to see what can be done about it in the extension itself, but [here](https://stackoverflow.com/questions/31214926/how-to-add-language-to-nsspellcheckers-available-languages/31383060#31383060) is another confirmation that what you report is a bug of `NNSpellChecker` on macOS.

**Comment by bartosz-antosik** [comment]
I have finally managed to have a deeper look into the issue and it seems that this is a [bug](http://stackoverflow.com/a/31383060) of `NSSpellChecker` which does not allow to list/use the spelling dictionaries installed in the Library folder. Possibly [this patch](https://github.com/atom/node-spellchecker/pull/42) could serve as workaround for the issue but it requires installing binary dependence of nodobjc which installs only on macOS.

This would require help of someone on macOS with some JavaScript and node.js experience.

I will make appropriate notice in README and until someone helps a bit Spell Right will not be able to spell in Library Installed language.

Side question: Is your macOS purchased in Hungary? I had hazy impression that macOS provides spelling dictionaries for the market it is sold on?

**Comment by andrasna** [comment]
Thanks, I probably have to look into this a bit myself, to see how I could be of help.

Yes, it is purchased in Hungary, oddly enough, with Hungarian keyboard.

**Comment by bartosz-antosik** [comment]
If you could maybe help then first step would be to test if you can install NodObjC node.js module, e.g.:

`npm install nodobjc`

Then application of the [patch](https://github.com/atom/node-spellchecker/pull/42/files) should be doable. Then it could be tested whether [node-spellchecker](https://github.com/atom/node-spellchecker) works with setting `hu_HU` as language. 

It would then in turn open some way to think how to do this inside Spell Right.

Still I am not sure whether this can be done as [node-spellchecker](https://github.com/atom/node-spellchecker) maintainers have not integrated the patch so maybe there is some catch.

**Comment by martinboksa** [comment]
Any new update, please?
