### ISSUE TITLE
Don't spell check HTML inside Markdown

### ISSUE THREAD

**Issue by borekb** [bartosz-antosik/vscode-spellright#78]
Not sure if doable at all but from a human perspective, this piece of HTML inside a Markdown file shouldn't be spell-checked:

![image](https://user-images.githubusercontent.com/101152/31611829-ddfd9cbe-b27d-11e7-80be-800d120e4b84.png)

**Comment by bartosz-antosik** [comment]
Don't you think this can be done using `spellright.ignoreRegExps` which for some time works globally, not only on words spelled? 

To be a nice solution it would call for a "perClass" setting for `ignoreRegExps` though.

**Comment by borekb** [comment]
I missed `spellright.ignoreRegExps`, thanks. You're right that having this "perClass" feels the best.

**Comment by bartosz-antosik** [comment]
In just released version 2.0.0 there is new setting item: `spellright.ignoreRegExpsByClass`. Have a look, should be an extended response to the issue.

**Comment by bartosz-antosik** [comment]
As usually if you would have a chance to test it & have comments, please let me know.

**Comment by borekb** [comment]
Thanks, I'll check it.

**Comment by borekb** [comment]
Nice, this pattern specifically resolves my issue:

```
"spellright.ignoreRegExpsByClass": {
    "markdown": ["/<[^>]+>/g"]
}
```
