### ISSUE TITLE
Global/Workspace dictionary(ignoreWords)

### ISSUE THREAD

**Issue by Nikaas** [bartosz-antosik/vscode-spellright#8]
When clicking on the "Add ??? to global dictionary" the spell checker adds the word to both global (settings.json) and workspace (spellright.json) ignore lists.

Additionally, in the global options file (settings.json) the ignoreWords list is created with a wrong name "spellchecker.ignoreWords" when the accepted one is "spellright.ignoreWords".

**Comment by bartosz-antosik** [comment]
Should be fine in version 1.0.8.
