### ISSUE TITLE
[Question] How to customise the key binding for correcting spelling errors

### ISSUE THREAD

**Issue by weakish** [bartosz-antosik/vscode-spellright#82]
How can I change the keyboard shortcuts for correcting spelling errors (`ctrl/cmd+.`) to something else?

**Comment by bartosz-antosik** [comment]
I think, if you choose File -> Preferences -> Keyboard Shortcuts then when you enter Ctrl+. you will see:

"command": "editor.action.quickFix".

I suppose this binding has to be changed to change the shortcut. But this is rather VSCode's thing, not related to Spell Right or any extension.

Spell Right (as all other spell checking extensions) work by producing something that is called "diagnostics". This "diagnostics" mechanism is a global mechanism that allows extensions to produce information about various aspects of content (e.g. syntax hints, etc.) The keystroke to invoke diagnostics remedy is set not by the extension but by VSCode itself.

**Comment by weakish** [comment]
Thanks for your patient and detailed explanation. I should have tried to first edit the shortcut for vscode's internal quickFix before opening an issue.

Thanks a lot.
