### ISSUE TITLE
Not Working with Madoko Document Type

### ISSUE THREAD

**Issue by kvn-s** [bartosz-antosik/vscode-spellright#85]
I'm using the [Madoko for VSCode](https://marketplace.visualstudio.com/items?itemName=maelvalais.madoko) extension and having trouble getting the spell checker to work.

It's actually working fine with Markdown and other formats. Just Madoko seems to make trouble. I already tried enabling it by default for the document type using `"spellright.documentTypes": ["madoko", "markdown", "latex", "plaintext"]` and the status bar info suggests it's activated. However absolutely no error is shown for obviously wrong words.

Any ideas on what might be wrong?

**Comment by bartosz-antosik** [comment]
Unknown document types cannot be enabled without adjusting the code. This is VSCodes limitation. 

I will do this as soon as possible.

**Comment by kvn-s** [comment]
Thanks for your reply. I'm not sure if I'm understanding you correctly but the extension actually adds a new document type, no?!

See this excerpt (from [here](https://github.com/maelvalais/madoko-vscode/blob/master/package.json)):
``` json
"contributes": {
    "languages": [
        {
            "id": "madoko",
            "aliases": [
                "Madoko",
                "madoko"
            ],
            "extensions": [
                ".mdk",
                ".madoko"
            ],
            "configuration": "./language-configuration.json"
        }
    ],
    "grammars": [
        {
            "language": "madoko",
            "scopeName": "source.madoko",
            "path": "./syntaxes/madoko.tmLanguage"
        }
    ]
}
```

**Comment by bartosz-antosik** [comment]
If I understand things correctly the extension for Madoko you pointed out adds new document class `madoko`. My extension would create an null parser for such a class whereas it should create a markdown parser. So I have to do small change in my extension to incorporate new type.

The problem with VSCode is that so far it does not gie an access to all the registered (by the editor itself and by the extensions) document classes. It would be great if VSCode would give access e.g. to semantical inforamtion like how are line/block comments constructed etc.

**Comment by kvn-s** [comment]
Okay, I think I know what you mean. :)

**Comment by bartosz-antosik** [comment]
Added in just released version 2.0.0. Please give some feedback if it works for you.

**Comment by kvn-s** [comment]
Thanks, it's working now. Though some Madoko specific syntax is checked too.

Would it be possible to use the [Madoko syntax support](https://marketplace.visualstudio.com/items?itemName=maelvalais.madoko) instead of Markdown (if installed)?

**Comment by bartosz-antosik** [comment]
As I have noted above first part of the problem is that VSCode does not allow extensions to use the information about document class (e.g. line/block comments, strings, quoting etc.) So there is no way to parametrize my parsers to an unknown language.

Can you show me a sample (both screenshot & source of the document) demonstrating the problem?

**Comment by kvn-s** [comment]
Sorry for the late reply.

Of course, here is an example (source [Test.mdk.txt](https://github.com/bartosz-antosik/vscode-spellright/files/1465962/Test.mdk.txt)):
![issue with madoko](https://user-images.githubusercontent.com/32765095/32714687-44c07a66-c84f-11e7-9146-dc0857579442.PNG)

It would be great if all the errors would go away. Ideally only headlines and text blocks (excluding special inline blocks such as references) would be checked.
