### ISSUE TITLE
Project-Specific Dictionaries?

### ISSUE THREAD

**Issue by kvn-s** [bartosz-antosik/vscode-spellright#86]
I'm trying to add words that are for a specific project only. I'm putting the "spellright.dict" into the root (where ".gitignore" etc. is) but it's not recognized. Is there a way to do it?

**Comment by bartosz-antosik** [comment]
`spellright.dict` should be in .vscode directory. There can actually be more than one `*.dict` file there! Please have a look into README.md to see more on this.

Best option is probably to use one of commands to add words (and create file if it does not exists)  to the workspace dictionary.

**Comment by kvn-s** [comment]
Yeah, I read that but am unsure if it's serving my purpose. Isn't it kind of *global* too? I thought about something specific to a project folder (like .gitignore) that is automatically recognized if available.

If it's not possible yet, I would actually make this a feature request. Don't you think it could be useful?!

**Comment by bartosz-antosik** [comment]
There are two `spellright.dict` files: One is located in User settings folder, another in workspace's `.vscode` folder. First one is global the second (which can be actually multiple `*.dict` files) is workspace's local. Is there something I do not understand?

**Comment by kvn-s** [comment]
Sorry, my bad. Thought you were talking about `C:\Users\me\AppData\Roaming\Code\User\` and `C:\Users\me\.vscode\`...

Just a suggestion but maybe you could reword it a little? I would call it project folder or something. Also the "Add to workspace" command didn't work properly (probably because `.vscode` sub-folder didn't exist yet) so I got confused a little.

Thanks again for your help.

**Comment by bartosz-antosik** [comment]
I see. This mentioned by you `.vscode` is nothing but extension repository. So I have not event thought about it. It took me to get familiar with this User/Workspace dualism a while but now I think it is clear to me.

I will have to see the problem with nonexistent `.vscode` directory. Thanks.
