### ISSUE TITLE
Persistent settings are problematic

### ISSUE THREAD

**Issue by borekb** [bartosz-antosik/vscode-spellright#87]
2.0 [introduced settings persistence](https://github.com/bartosz-antosik/vscode-spellright/commit/efd4f19d744fb06ec7e337d5cddaf2298ee1d1f0#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR7) which is problematic for us: we normally don't check certain document types but locally, sometimes I want to turn it on. Before 2.0, I could just click the "eye" icon in the status bar and change it to whatever I found convenient locally. With 2.0, this immediately writes to `.vscode/settings.json` which is a Git-versioned file so I get changed Git state. Even if there was no workspace settings and SpellRight would write to my user settings, that would also be problematic because I synchronize my settings between computers and this would create a lot of noise.

The previous approach was better, IMO. I could experiment with various levels of spell checking and only when I'm happy with them, manually write those to either user or workspace settings.

**Comment by bartosz-antosik** [comment]
I must say, that I partially agree with you. I love the change to workspace settings, it is much more clearer now. So I will definitely not go back to `spellright.json` settings which was closely related to the `Update settings` command. I think for many casual users what is now may be far more acceptable as it does not require getting any knowledge about the extension's internals, they just want to spell something and have it spelled whenever the editor opens...

As usually - I will think of something.

**Comment by bartosz-antosik** [comment]
I had same problem with font size between lo/high DPI monitors. Luckily [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) has the ability to exclude certain settings from synchronization.

**Comment by bartosz-antosik** [comment]
I did the changes, but with the multi root workspaces thing like this (changing settings independently of what is in the configuration files) is very complicated & possibly faulty. Please, test whether it works for you and whether there any issues related to this. All is contained under `spellright.updateConfiguration` setting.

It will be present in just released version 2.0.2.

**Comment by borekb** [comment]
Works great! Thank you.
