### ISSUE TITLE
No light bulb for single character misspellings

### ISSUE THREAD

**Issue by jwood13** [bartosz-antosik/vscode-spellright#89]
Several single Letters (T,W,M) register as a spelling error with the dictionary I am using (English AU), however they do not produce the light bulb that you would normally use to add words to the dictionary. This doesn't regardless of whether the cursor is immediately before or after the letter. The mouse over text does appear.

**Comment by bartosz-antosik** [comment]
Could you tell me the OS? Could you maybe post screenshot?

**Comment by bartosz-antosik** [comment]
Oh, I can reproduce this! It was easier than I have anticipate! Just write non-capital i with any English spelling dictionary... Let me have a look!

**Comment by bartosz-antosik** [comment]
Just published version 2.0.4 should resolve this. Please let me know in this thread whether it works OK for you.

**Comment by jwood13** [comment]
Yes this has resolved the issue. Thankyou
