### ISSUE TITLE
Fail to start

### ISSUE THREAD

**Issue by neilsustc** [bartosz-antosik/vscode-spellright#9]
This is the console output

```
Activating extension `ban.spellright` failed: The module 
'\\?\C:\Users\username\.vscode-insiders\extensions\ban.spellright-1.0.8\node_modules\spellchecker\build\Release\spellchecker.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 50. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`)..
```

Windows 10 & vscode-insider build 2017-04-20

**Comment by bartosz-antosik** [comment]
Sorry but it will not work in the insiders build if it has different Node.js or Electron version than the main distribution version. The reason for this is described in more details in the first post of [#20266](https://github.com/Microsoft/vscode/issues/20266).
