### ISSUE TITLE
Adding `word` to dictionary doesn't make it recognize `word's`

### ISSUE THREAD

**Issue by janpio** [bartosz-antosik/vscode-spellright#90]
Nice extension!

I have a document with the words `Fastlane` and `Fastlane's`, both marked as misspelled. 
I added "Fastlane" to my user dictionary which made the spell checker ok with that word. 
"Fastlane's" unfortunately stays underlined as it doesn't seem to understand this is the same word.

Bug or feature?

**Comment by bartosz-antosik** [comment]
Just published version 2.0.7 should deal with it.

**Comment by janpio** [comment]
Confirmed, works.

Thanks!
