### ISSUE TITLE
Contractions flagged as incorrect

### ISSUE THREAD

**Issue by tasgoon** [bartosz-antosik/vscode-spellright#93]
Every time I write a word such as "don't", or "I'll", this plugin flags it as incorrect. Is there any way to fix this?

**Comment by bartosz-antosik** [comment]
This is probably a side effect of the very last update. I will have a look at this tomorrow.

**Comment by bartosz-antosik** [comment]
Version 2.0.8 should fix it.

**Comment by tasgoon** [comment]
Sweet, thanks a bunch. I was waiting for this fix to use VS Code as my main editor.

**Comment by bartosz-antosik** [comment]
My sentiment exactly! Just I was waiting for the spell checker. ;-) The whole story [here](https://github.com/Microsoft/vscode/issues/20266).

Of course [reviews](https://marketplace.visualstudio.com/items?itemName=ban.spellright#review-details)/[ratings](https://marketplace.visualstudio.com/items?itemName=ban.spellright#review-details) are welcome!
