### ISSUE TITLE
RMarkdown support

### ISSUE THREAD

**Issue by rensa** [bartosz-antosik/vscode-spellright#94]
Hi! Spell Right seems great, but I can't get it to work with RMarkdown (`.rmd`) files. They're Markdown files interspersed with chunks of R code.  The chunks are delimited by lines starting in ```, like:

    # My classy book report
    
    I did a bunch of research and stuff! Then I:
    
    - organised the research, and
    - made up some words!
    
    ```{r my_chunk some_option = TRUE}
    pandoc.table(mydata)
    ```
    
    Then I wrote some more stuff. The End.

I tried opening an `.rmd` file and choosing a Spell Check language, but nothing happened. It would be great if SpellCheck could support these files! Thanks :)

**OS:** macOS 10.13.1
**VSCode:** 1.18.1
**Spell Right:** 2.0.8

**Comment by bartosz-antosik** [comment]
Hi! Thanks for returning with the issue & providing great input (esp. the RMarkdown example)!

Version 2.0.10 has added RMarkdown [rmd] document type. Here's your example:

![image](https://user-images.githubusercontent.com/20492548/33263159-0f600f7e-d369-11e7-9c9e-a4184e226a0f.png)

Sorry for it might have been confusing, but the situation you encountered is semantically "as designed". The switch is to globally switch language to al the types Spell Right understands. So it to some extent acted as it should. 

The situation pushed me to add an information popup to notify that particular document type is yet not supported and suggestion to start an issue. Also I think some future version will allow to configure the use of generic parsers on the configuration level for document types that are not known at the time.

The real trouble is that spelling just everything has little sense according to me and VSCode does not allow extensions to see syntactic information of registered document types (e.g. how are strings & quoted delimited, code block & comments delimiters etc.) Hence a bit of a dead end you hit.

**Comment by rensa** [comment]
Thanks very much for so promptly implementing this! it works great when I select a language.

Is it possible to have it turned on by default for `.rmd` files? I've tried adding both of the following to my user settings:

```
// Document types for which spelling will be turned ON by default.
  "spellright.documentTypes": [
    "markdown",
    "latex",
    "plaintext",
    "rmd"
  ]
```

```
// Document types for which spelling will be turned ON by default.
  "spellright.documentTypes": [
    "markdown",
    "latex",
    "plaintext",
    "rmarkdown"
  ]
```

But neither seems to turn on spell checking on startup (after restarting, of course).

**Comment by bartosz-antosik** [comment]
Please check whether Workspace settings do not override User settings in some way!

Setting it as you shown on first attempt above (the class name is `rmd`) works (I just did a test copying exactly your example into my User settings.

Workspace settings override User settings in every way, so if you have something set there it will just ignore User settings (not add, as the it would not be possible to remove classes).

Let me know if it worked for you.
