### ISSUE TITLE
Right-click option list (feature request)

### ISSUE THREAD

**Issue by ThomasBeauduin** [bartosz-antosik/vscode-spellright#97]
Right click on underlined spelling should have 'add to dictionary' option.
Command line 'SpellRight: Add Selection to User dictionary' is non-intuitive (time consuming selection necessary).

**Comment by bartosz-antosik** [comment]
Hi! I am not sure if I understand thing entirely so I will explain it the way I understand it and please correct me if I am worng: Extensions so far have no access to right click menu. What Spell Right (and other spell checkers) produce are "diagnostics" - something that the editor understands how to manage. Once you are with the cursor on the misspelled word, you can either click the lightbulb symbol or press Ctrl+. (see README.md for other OSs variants of this command) to show the diagnostics context menu. In this menu you have proposed corrections and options to add the word to either dictionary:

![image](https://user-images.githubusercontent.com/20492548/33530787-1ae357c2-d885-11e7-8258-b022d3166d07.png)

P.S. I am sure right click menu would be far more intuitive & coherent with common experience but that's something which is beyond me, that is, you may try to search & maybe up-vote (I think it exists somewhere among VSCodes issues).

**Comment by bartosz-antosik** [comment]
Hope the explanations were helpful!
