### ISSUE TITLE
Spellright stopped working

### ISSUE THREAD

**Issue by texjoachim** [bartosz-antosik/vscode-spellright#98]
I installed the plugin and added the UTF8 dictionaries. It worked like a charm. Then after a few days, the plugin can't find the dictionaries any more and I can only deactivate the spellcheck. 

What happened?

**Comment by bartosz-antosik** [comment]
Hi! Could you tell more about VSCode's & OS's versions, dictionaries location?

**Comment by texjoachim** [comment]
No problem:
openSUSE Tumbleweed
VSCode: Version 1.18.1
Commit 929bacba01ef658b873545e26034d1a8067445e9
Datum 2017-11-16T18:34:22.110Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

My dictionaries are in ~/.config/Code/Dictionaries.

**Comment by bartosz-antosik** [comment]
It may be a side effect of the recent change (described at the end of #53). Let me have a look.

**Comment by ribelo** [comment]
I have the same problem, and the same version. It appeared after last extensions update.

**Comment by bartosz-antosik** [comment]
Thanks for reporting. I will have a look.

**Comment by bartosz-antosik** [comment]
Should be fixed in 2.0.13. Please let me know if it is.
